### PR TITLE
replaced Jack with Jill

### PR DESCRIPTION
**Pull request by Lumak**

### CODE REVIEW

**Comment by eugeneko** [comment]
Huh... Any screenshots?

**Comment by 1vanK** [comment]
@eugeneko 

https://sketchfab.com/models/4f313a3619be4669a3ea700516737265

**Comment by Lumak** [comment]
Screenshot wouldn't do justice. I'd recommend running the sample and see for yourself. You do have to verify that the content submitted for PRs anyway, don't you?

I have to say, though, that there are somethings that I dislike.

**Comment by yushli** [comment]
Not sure why this PR is closed. It looks like interesting to have some new models to show up.

**Comment by cadaver** [comment]
Yeah it'd be fine to me to add models. Don't think Jack needs to be removed though, as it's a humorous link to the realXtend project. Also I think I'd be rather knocking down Jacks in the ragdoll demo.

**Comment by Lumak** [comment]
I closed this because I realized that 06 sample also demonstrates LOD feature, which the new model doesn't have. I couldn't justify not showcasing that important feature just to show a pretty Asian girl with Naruto run. I'll revisit this when I figure out how to create skinned LOD models in maya/assetimporter.

**Comment by MonkeyFirst** [comment]
Better to seeing a "pretty Asian girl with Naruto run" then LODs, Lol )

**Pull request closed without merging**
