### PR TITLE
Static check for PODVector

### PR DESCRIPTION
**Pull request by 1vanK**
@eugeneko ?

### CODE REVIEW

**Comment by eugeneko** [comment]
Do you have clear steps how it can be reproduced?
Compiler cannot just confuse two different types. If it "does", you probably need to investigate why and find the root cause.

So far I don't see what the bug is and how this PR fixes it.

PS. No need to have 3 exact copies of the code next to each other, 1 would be enough.

**Comment by 1vanK** [comment]
> Do you have clear steps how it can be reproduced?

remove NotPODVectorToArray and rename calls NotPODVectorToArray to VectorToArray

**Comment by eugeneko** [comment]
@1vanK I believe you have hit this "feature" of C++:
https://stackoverflow.com/questions/36298211/static-assert-triggering-during-function-name-resolution

Still, solution is really ugly. Just make first parameter of `VectorToArray` template and remove second (and third) copy of this function.

**Comment by 1vanK** [comment]
https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/AngelScript/APITemplates.h#L72

**Comment by eugeneko** [comment]
If you wanted to make a point by the latest comment, sorry, I didn't get it.

My point is that both versions of `VectorToArray` are identical and therefore you don't need two of them, only one.

The "propper" fix for this compiler "bug" would be to use `enable_if` and template specializations instead of `static_assert`, but it's ugly as hell and is overkill in this specific case.

**Comment by 1vanK** [comment]
> Just make first parameter of VectorToArray template

T is used and I can not just replace it to something else

**Comment by eugeneko** [comment]
> T is used and I can not just replace it to something else

Functions may have more than one template parameter

**Pull request closed without merging**
