### PR TITLE
Added operator overloads for multiplying IntVectors

### PR DESCRIPTION
**Pull request by Modanung**
This PR allows for `IntVector2` and `IntVector3` to also be multiplied by vectors of the same type instead of only scalars. With `Vector2` and `Vector3` this was already possible.

### CODE REVIEW

**Comment by eugeneko** [comment]
Could you write bindings?
I know, everybody hates writing binding, but...

**Comment by Modanung** [comment]
Can now! :wink: 
Are there more bindings required apart from the AS ones?

**Comment by eugeneko** [comment]
Probably you could also add non-assignment ops to Vector2.pkg and Vector3.pkg

**Comment by Modanung** [comment]
Done!
Also added IntVector2 constants and removed line 19 from Vector2.pkg, which occured twice:
```
Vector2 operator / (const Vector2& rhs) const;
```

**Pull request merged**
