### PR TITLE
Added rendering scale to UI

### PR DESCRIPTION
**Pull request by ninjastone**

### CODE REVIEW

**Comment by cadaver** [comment]
Can you add script bindings and check that touch events take the scale into account correctly?

**Comment by ninjastone** [comment]
Yes I can, let me add it. so far touch events are working in HelloGUI and my project.

**Comment by ninjastone** [comment]
Mouse positions are okay, but touch events are not. I'll fix it.

**Comment by cadaver** [comment]
Thanks, that's fine if you have ready access to a touch-enabled machine.
In case you get trouble with it, I can fix those too.

**Comment by ninjastone** [comment]
It should work now.

**Comment by cadaver** [comment]
Thanks. Will check (soon), add some minor documentation section on it, and merge.

**Comment by cadaver** [comment]
Implemented resizing the root element when scale changes, fixes related to scissoring, fix to Console to handle the resize properly (it was assuming Graphics resolution) and Lua bindings. Merge imminent.

**Pull request merged**
