### PR TITLE
Minor fix and helper function

### PR DESCRIPTION
**Pull request by eugeneko**
Added helper function to get an axis/angle from Quaternion.
Also fixed a bug when Urho crashes if AS ScriptObject throw an exception from ctor.

### CODE REVIEW

**Comment by cadaver** [comment]
Looks good.

**Comment by eugeneko** [comment]
Any ideas why it's failed?

BTW, @weitjong, may you somehow grant me an ability to re-start jobs in AppVeyor?

**Comment by weitjong** [comment]
Most probably it was just a technical error. The CI jobs come in pair of group. A genuine error would usually trip in pair. So when you see a lone CI Job error for no obvious reason then don't think too much about it. Of course, if you want to be sure then the job(s) can be re-triggered. I have just done that.

Which come to your next question. Currently no one else can retrigger beside myself. The whole setup in Urho3D is in fact using my personal AppVeyor account, i.e. I have cloned my personal setup for Urho3D. I think it is good idea to setup a separate account for Urho3D as an org or team so we could have multiple users or collaborators. Will do that when I have time.

**Comment by eugeneko** [comment]
Thank you!

**Pull request merged**
