### PR TITLE
Draw navigation debug geometry in Editor

### PR DESCRIPTION
**Pull request by 1vanK**

### CODE REVIEW

**Comment by 1vanK** [comment]
If I understand correctly, NavigationMesh and DynamicNavigationMesh always connect to root node.
But SceneRebuildNavigation() search components recursive.

**Comment by 1vanK** [comment]
Also NavMesh does not write log message
```
URHO3D_LOGERROR("CrowdManager is a scene component and should only be attached to the scene node");
```
like void CrowdManager::OnSceneSet() when attached to not root node

**Comment by 1vanK** [comment]
fixed

**Comment by cadaver** [comment]
Thanks! I was indeed missing something like this when debugging the Obstacle OnMarkedDirty() implementation.  Are the UI XML changes intentional?

**Comment by 1vanK** [comment]
> Are the UI XML changes intentional?

yes, just style fix, it is not directly related to the patch

**Comment by cadaver** [comment]
Merged.

**Pull request closed without merging**
