### PR TITLE
Area lighting and Quality improvements to IBL

### PR DESCRIPTION
**Pull request by dragonCASTjosh**
This commit includes the following:

-Sphere Area Lighting
-Tube Area Lighting
-Mip selection based on epics approach for higher quality
-Physically accurate attenuation
-Improve Cubemap seams on d3d9 and opengl, as mentioned in #1646 
-Update scene to demonstrate area lighting
-Re-import all textures to fix normal map artifacts

Screenshots:
screenshot_sat_nov__5_05_52_15_2016
screenshot_sat_nov__5_05_52_21_2016
screenshot_sat_nov__5_05_52_35_2016
screenshot_sat_nov__5_05_53_02_2016
screenshot_sat_nov__5_05_53_22_2016
screenshot_sat_nov__5_05_56_13_2016

### CODE REVIEW

**Comment by eugeneko** [comment]
There are some tabs and probably garbage lines in Batch.cpp and Light.cpp..

**Comment by dragonCASTjosh** [comment]
ill take a look, although its a bit odd the only some files have the issue.

**Comment by dragonCASTjosh** [comment]
hopefully i didnt miss anything else

**Comment by cadaver** [comment]
I'll test in detail hopefully soon. Meanwhile, the Light's "radius" & "length" only have an effect when it's an area light, right? Please explain this in the setters in Light.h, because otherwise looking at the Light class is going to get confusing for people who don't know how it's supposed to work. As there's the "range" parameter already from before.

**Comment by dragonCASTjosh** [comment]
It's currently set up so that if the radius is above 0 then it will run area lights, this is handled by an if in the shaders. I understand this has a slight overhead but it's nowhere close to the area lighting code. Epic also take this same approach in their shaders. At a later date I'd like to understand the define system and set it to only run on a define the same way as shadows but i was unable to work it out.

As for what the values mean. The radius is the size of the light source and the length is the length of the light source. The existing range parameter is used for the range the light effects, in other words, the attenuation.

Hopefully that makes sense.

**Comment by cadaver** [comment]
Yes, makes sense, but assume a user hasn't read the relevant forum threads + discussion of this PR, so that same info should be either in the class API doxygen comments, or in an added documentation section :)

**Comment by dragonCASTjosh** [comment]
That makes sense im just not good with writing learning resources and am not even sure how to do docs

**Comment by cadaver** [comment]
The least work will be to cram all the most vital information in the one-liner header comments.

**Comment by dragonCASTjosh** [comment]
hopefully that covers what you was asking for

**Comment by cadaver** [comment]
Yeah that should part be good now. 

Since the area light calculation is kept inside the PBR paths it's acceptable to me to do the branching in pixel shader, if you have personally tested the performance of ordinary lights under PBR to not suffer much. Though using a shader compile flag would still be preferable.

As isAreaLight_ is not actually used, it should not be defined as an attribute, since that's unnecessary operations being done in serialization for every lights, and it increases the memory payload of the Light component. Easiest is to just remove. You could still have IsAreaLight() which checks for the radius / length parameter values.

Also, in IBL shader code, it would be preferable to fix spelling mistake + function name not following convention of the rest: GetMipFromRougness() -> Roughness and fix_cube_lookup -> FixCubeLookup.

**Comment by dragonCASTjosh** [comment]
Should be good now.

**Comment by cadaver** [comment]
Thanks. Think I'll perform additional cleanup before merge, because I don't think there should be commented out lines in the engine classes (doesn't inspire confidence), or unused variables. But that should be a minor change, you don't have to touch it.

**Comment by dragonCASTjosh** [comment]
Any update on when it will be merged :) im exited to get started on more goodies

**Comment by cadaver** [comment]
Sorry, I've been away a bit due to extreme finish line stretch in http://www.nanowrimo.org but I hope it should be imminently soon. Will also need to check how much the repo will grow.

**Comment by cadaver** [comment]
Ok, back. Checked that the Autoload/LargeData folder is now 700MB, I think that's a *bit* too much considering the old one is about 40MB. Due to the extremely large .png's the demo also takes a long time to start up. Or did I make a mistake in merging? Got a shader compile error (complaining of finalColor) on non-deferred PBR, OpenGL 3. The engine code changes themselves are looking fine.

**Comment by dragonCASTjosh** [comment]
i felt the need to change the textues as the old one has a lot of artifacts from being exported as 8-bit jpg files. most of the textures are to the same resolution as a modern game outside of the 1 4k textures because i could see alot of pixels in the 2k version. If you are unable to merge the textures id recomend making the samples as a sepereate repo or download posible. As for the shader error im not sure what would cause that nothing in the None-PBR shaders should of changed.

**Comment by OldSnake22** [comment]
You can just use DDS DXT1 format for albedo and PBR maps and for normal maps just save them in DDS DXT5 'XGXR' format. This will remove normal maps artifacts and you will save a huge file size amount. This is the workflow that i am using in my project and it is working fine.

Infos for xGxR format conversion here: https://urho3d.github.io/documentation/1.4/_materials.html

**Comment by cadaver** [comment]
The shader error can be a result of the minor changes that were applied for soft particle support, can recheck that.

**Comment by cadaver** [comment]
I could merge this without the texture changes first. If you want to convert them to DXT for smaller size you could do that later in a separate PR. Ok?

**Comment by dragonCASTjosh** [comment]
that sounds fair

**Comment by cadaver** [comment]
Merged.

**Comment by 1vanK** [comment]
Lighting looks different with different distances (I tested DX9 version only)

**Comment by 1vanK** [comment]
same problem with GL3

**Comment by dragonCASTjosh** [comment]
@1vanK can you make the floor surface of that area to use the roughness 0.5 material it will make it easier to see whats happening

**Comment by 1vanK** [comment]
bug

**Comment by 1vanK** [comment]
hm, I removed "cast shadows" from sunlight and problem was solved xD

**Comment by dragonCASTjosh** [comment]
that seams very odd as it only affects the tube light and it uses the same shadow system as every other light

**Pull request closed without merging**
