### PR TITLE
Optimize Editor work with temporary objects

### PR DESCRIPTION
**Pull request by eugeneko**
Related to #1664 
I'ven't managed to fix bottleneck in Hierarchy View. However, I've optimized temorary nodes and how Editor deal with them. Since procedural nodes like terrain pathces are temporary, these changes are pretty good workaround for my issue.
Please, review changes in **EditorHierarchyWindow.as** for possible unwanted side effects.

### CODE REVIEW

**Comment by cadaver** [comment]
Shouldn't be anything wrong with this. Feel free to merge to master.

**Comment by cadaver** [comment]
One thing, did you check toggling the "show temporary" checbox in the editor at runtime, does it work as before? If yes then there shouldn't be any other possibilities for trouble.

**Comment by eugeneko** [comment]
Seemed to work OK for me too.
BTW I added the same checks to HandleNodeNameChanged, HandleNodeEnabledChanged and HandleComponentEnabledChanged. It shouldn't be a problem too. Then I'll build it and merge.

**Comment by cadaver** [comment]
Yes, makes sense.

**Pull request merged**
