### PR TITLE
Add anchor and pivot to UIElement.

### PR DESCRIPTION
**Pull request by ninjastone**
I implemented new feature mentioned in #1366. New attribute mode AM_FILEREADONLY is used for keep compatibility with older layout files.

Please take a look at my changes. If it's not bad, I'll add script bindings as well.

### CODE REVIEW

**Comment by cadaver** [comment]
Nice. And dangerous :) Will check in detail later. For my sanity I'd probably want to postpone this after the coming release.

This looks a bit suspicious (GetPosition get accessor and editor only), is this as intended? URHO3D_ACCESSOR_ATTRIBUTE("Min Offset", GetPosition, SetMinOffset, IntVector2, IntVector2::ZERO, AM_EDIT);

Read-only attributes are incompatible with binary serialization, since the structure being read and written is different. If they're only used for UI elements it's fine, but a note should be added of this.

**Comment by cadaver** [comment]
Tested already since the PBR is still ongoing. It's excellent how you managed to keep this compatible to the existing UI features. However I couldn't quite understand how the max anchor parameter works. I think this needs better documentation in the class setters/getters, ie. explain briefly what they do.

**Comment by ninjastone** [comment]
"Min Offset" line is intended, I wanted to add way to edit left/top positions of UI elements without touching their right/bottom positions.

As for read-only attribute mode, my bad, I didn't think about binary serialization. Is adding some notes to constant enough? Maybe I should change it's name also.

Thanks for testing. The max anchor is starting positions of right/bottom sides relative to their parents. The max offset is added afterwards. I'll add explanations how rectangles of UI elements are calculated.

**Comment by cadaver** [comment]
Yes, it's enough if you add a note that this mode is not to be used with binary-serialized objects. Practically, anything that can live in the Scene.

**Comment by yushli** [comment]
When will this be merged into main branch? I know it may be after the coming new release, but good to know if the merge can happen soon.

**Comment by cadaver** [comment]
After release. I still have concerns that the new attributes may be dependant on setting order, on the other hand if you don't use them, then nothing breaks at least in old UI layouts.

**Comment by cadaver** [comment]
@ninjastone One thing that could be good to add besides the script bindings, would be a brief paragraph to the UI documentation page (in Reference.dox).

**Comment by cadaver** [comment]
Tested this a bit more, and found out that the new attributes interfere with saving and reloading some of the layouts that used to work. For example, try loading Data/UI/EditorHierarchyWindow.xml into the editor, set the size to for example 400x600 and observe that the content inside it looks correct. Now save that with another filename, then load the just saved layout. The sizes of elements within the layout aren't restored correctly. @ninjastone Can you look into that?

**Comment by ninjastone** [comment]
Conditions I added to serialize function was wrong. Give me some days to fix it. I don't have much time to work on hobby projects this week.

**Comment by cadaver** [comment]
Thanks for looking into it, no hurry!

**Comment by cadaver** [comment]
The PR seems to now be in conflict, can you look into that still?

**Comment by ninjastone** [comment]
sure

**Comment by cadaver** [comment]
Thanks for the work. There's one thing that confused me, that having maxOffset zero doesn't let the anchor positioning work. I'll see if that can be cleared up. Maybe I'll set an explicit boolean enable for the anchoring, that way there is also no question that existing layouts would break, since it'd be disabled by default.

**Comment by cadaver** [comment]
Also, I think the size not getting saved in layouts anymore is not desirable (for elements that are not anchor-positioned), so I'd rather remove the "readonly" mechanism and think for some other solution, if possible.

**Comment by cadaver** [comment]
I believe I succeeded. The merge with modifications will be pushed soon to master.

**Comment by cadaver** [comment]
Merged.

**Comment by ninjastone** [comment]
thank you :)

**Comment by 1vanK** [comment]
How to use it right?

**Comment by 1vanK** [comment]
Ah, I understood. I had to use offsets for spaces.

**Comment by 1vanK** [comment]
Why not use Rect for anchor and offsets? At the moment top and left bounds store in one variable, and right and bottom in another. I think this is illogical.

**Comment by cadaver** [comment]
Yes, you can use a mixture of anchor and offset. For an absolute sized but anchored element min/max anchor could be the same and offset would define the actual pixel size.

**Pull request closed without merging**
