### PR TITLE
Civetweb update.

### PR DESCRIPTION
**Pull request by cosmy1**

### CODE REVIEW

**Comment by cadaver** [comment]
Have you tested that basic http requests still work as expected?

**Comment by cosmy1** [comment]
Yes I tested it and works.

**Comment by cosmy1** [comment]
What about making a HTTP request sample?

**Comment by cadaver** [comment]
It would be good for regression testing, yes. If you want to do one, feel free to.

**Comment by cosmy1** [comment]
I just made a basic sample that request date and time but I had other ideas which require HTTPS, like printing Urho3D contributors by using GitHub APIs. If is ok for you I just PR that basic sample or if you have other ideas let me know :smiley:

**Comment by cadaver** [comment]
A basic sample is fine.

**Pull request merged**
