### PR TITLE
Implementing RibbonTrail

### PR DESCRIPTION
**Pull request by ucupumar**
This is implementation for ribbon trail on Urho3D. I've implemented two types of trail, face camera and bone type. Face camera trail is always facing camera just like billboard. Bone trail will emit trail between child and it's parent, it's pretty useful for sword slashing effect. I've been adding column option too to minimize artifacts. Also, I add new sampe 44_RibbonTrailDemo to show you the effects. The commits are still messed up, I'll rebase them soon.

Face camera Trail:
face_camera_trail

Bone trail:
bone_trail

Anyway, RibbonTrail icon for editor is still sucks, I'm not that good at pixel art. If you can to make better one, feel free to contribute. :smile:

### CODE REVIEW

**Comment by cadaver** [comment]
Nice! Will likely look at this after the weekend in earliest, so take your time.

**Comment by ucupumar** [comment]
Okay. Anyway, do anyone know why PBR materials included in list of changed files? I don't change anything on those files.

**Comment by ucupumar** [comment]
Oh, and why the Travis CI failed?

**Comment by weitjong** [comment]
Click on the Details link on the right. It appears that for the build using Clang compiler toolchain, some of the test runs have segfaulted. This indicates there is illegal memory access somewhere in your code.

**Comment by ucupumar** [comment]
I think I see all the samples (not only mine) are get segfaulted. Why that's happen?

**Comment by weitjong** [comment]
Not very sure myself without actually looking into the code in detail.

**Comment by 1vanK** [comment]
may be 
```
MAX_GEOMETRYTYPES = 8
```
should be
```
MAX_GEOMETRYTYPES = 7
```

(it seems that it depends with size of "geometryVSVariations" array)

**Comment by ucupumar** [comment]
Yeah, you're right, I messed up that one. I'll fix it now and see can this solve the problem.

**Comment by ucupumar** [comment]
Okay, it built successfully now. Thanks @1vanK !
To next question, why PBR materials included in changed files list regardless I didn't change anything to those files? Is it okay or not?

**Comment by 1vanK** [comment]
Sometimes git change end of line chars (unix '\n' to windows '\r\n' or vice versa). I don't know why

**Comment by ucupumar** [comment]
I think that was ok then, I'll just go with the rebase now.

**Comment by ucupumar** [comment]
Okay, I'm done with the rebasing. Now it still had bad icon issue. I'll look into @Modanung submission again.

**Comment by ucupumar** [comment]
Wait a minute, it looks like the diff is messed up. Some files is diff-ed completely eventhough I only added few lines. Is it okay or not?

**Comment by weitjong** [comment]
Probably not. We sometime need to use the "git blame" to find out who changes which line.

**Comment by ucupumar** [comment]
So, what should I do then? Should I redo the rebase or not? Actually, I'm not using rebase, I'm using patch to another branch and force push it to this branch.

**Comment by ucupumar** [comment]
Okay, the problem seems more than this, some files actually missing now, I'll find out a way to fix it.

**Comment by ucupumar** [comment]
I think it should be fine now. Tomorrow I'll review the icon.

**Comment by cadaver** [comment]
Looked through the file changes, seems solid.

**Comment by ucupumar** [comment]
Thanks @cadaver!
I already commit @Modanung icon and for me it looks really good. :smile:

**Comment by cadaver** [comment]
Tested, sample works fine. Excellent work.

However found 2 issues which should be resolved before merging:
- On initialization, RibbonTrail tries to set the material Materials/TailGenerator.xml which doesn't exist?
- RibbonTrail tries to create an index buffer with huge size, which probably is from a negative int being used as the index count. I saw this when testing D3D9 build and opening the log window while the .exe version sample was running.

**Comment by ucupumar** [comment]
@cadaver thanks for the follow up. I pushed new commit to fix those problems.

**Comment by cadaver** [comment]
Merged!

**Comment by ucupumar** [comment]
Thanks! :+1:

**Comment by 1vanK** [comment]
I think is some problem with bounding box (trail is invisible in some camera positions)

**Comment by ucupumar** [comment]
I see, I'll look into that one.

**Comment by ucupumar** [comment]
@1vanK I created new pull request #1425 to address this issue

**Pull request closed without merging**
