### PR TITLE
fix shader parameter cache bug

### PR DESCRIPTION
**Pull request by aimoonchen**

### CODE REVIEW

**Comment by eugeneko** [comment]
So, what's the bug?

**Comment by iSLC** [comment]
I don't think he means bug. More like an optimisation.

**Comment by eugeneko** [comment]
@iSLC More like pessimization, because now it does more work.

**Comment by 1vanK** [comment]
> I don't think he means bug. More like an optimisation.

```
if (globalFrameNumber != frameNumber_ || graphics_->GetLastShaderProgram() != this)
```

No, it looks like trying to fix some kind of bug, because added new activation conditions

**Comment by aimoonchen** [comment]
> @iSLC More like pessimization, because now it does more work.

@iSLC @eugeneko It doesn't work when i change the graphic backend to bgfx. I guess the unifom cache policy doesn't work well when shader changes.

**Comment by eugeneko** [comment]
> It doesn't work when i change the graphic backend to bgfx

I don't get it... Urho doesn't have bgfx backend.

**Comment by eugeneko** [comment]
Oh, I see.
What purpose this code serves in Urho master branch? Except possible performance degradation.
I mean, PRs are supposed to make things better, not worse. It says "fix bug", but there's no bug to be fixed.

**Comment by aimoonchen** [comment]
Sorry, this is not a bug in urho master branch, the OpenGL specification says : "... Uniforms are program object-specific state. They retain their values once loaded, and their values are restored whenever a program object is used, as long as the program object has not been re-linked ...".
But in bgfx, the uniform is not program object-specific state, it is global state, so it does't work in my bgfx branch.

**Pull request closed without merging**
