### PR TITLE
Replacing list of contributors by link

### PR DESCRIPTION
**Pull request by 1vanK**
Motivation:
* Current text list is incomplete
* Current text list requires manual modification
* Github's list contains more complete information (which commits were made and when)

### CODE REVIEW

**Comment by eugeneko** [comment]
The list you removed has 1.5 times more people than the link you added.
Are you sure that GitHub list of contributors is complete? It's built automatically, it will not count a person unless they have actual commit in history.

**Comment by 1vanK** [comment]
Are you planning to actualize the text lists?

> Contributors who got their commits squashed or pushed by maintainers will be lost to history.

These authors are listed in the commit names / descriptions / icons.

https://github.com/urho3d/Urho3D/commit/f8cb13f49afa1a77743c4fc06582bc1bbc11ed29

**Comment by 1vanK** [comment]
You always can get full list by `git log` if you are interested. Let's be honest, this is not interesting to anyone. Have you read this list, which takes up 70% of the start page, at least once? https://github.com/urho3d/Urho3D

**Comment by eugeneko** [comment]
> Let's be honest, this is not interesting to anyone. Have you read this list, which takes up 70% of the start page, at least once?

This list in not here for reading, it's to credit contributors. It's like movie credits.
Some people may find it offensive to have their names removed. Or maybe I'm overthinking it and no one would care.

Although I agree that this list shouldn't be in README, it's just informational garbage.
Perhaps move it to separate file?

> You always can get full list by git log if you are interested

I didn't check whether git log shows all the people from the list of contributors.
I can imagine scenario when a contributor will not show up in the contributor list (e.g. if commit was manually cherry-picked)

**Comment by eugeneko** [comment]
Having said that, I don't think we really _need_ this list. [Some projects do it](https://github.com/skypjack/entt/blob/master/AUTHORS), [some don't bother](https://github.com/electronicarts/EASTL).

PS. EnTT is good example, actually. I'm listed in AUTHORS and I'm _not_ listed in git history in any form because I never pushed my commits to master branch, only to vs2015 branch.

**Comment by 1vanK** [comment]
> Perhaps move it to separate file?

I'll just remind you that text list is not complete and has not been updated. Someone will see this list and think that these are all authors.

> I'm listed in AUTHORS and I'm not listed in git history in any form

https://github.com/urho3d/Urho3D/commits?author=eugeneko

https://github.com/urho3d/Urho3D/graphs/contributors

**Comment by 1vanK** [comment]
>  I'm listed in AUTHORS and I'm not listed in git history in any form

```
git log >../Log.txt
```

```
commit 708072e3b5f9edf6cea469a450412835fa23fbbd
Author: Eugene Kozlov <nekoeuge@gmail.com>
Date:   Tue Jun 18 20:03:17 2019 +0300

    Fix UB causing crashes with some compilers. (#280)
    
    It's not allowed (Undefined Behavior) to call memmove with null pointers even if the size is 0.
    In vector::DoInsertValueEnd memmove is called via eastl::uninitialized_move_ptr_if_noexcept unconditionally even for null pointers (when vector is empty).
    Therefore, further checks for p in vector::DoFree and allocator::deallocate get optimized away which leads to crashes.
```

**Comment by 1vanK** [comment]
https://github.com/electronicarts/EASTL/commits?author=eugeneko

**Comment by 1vanK** [comment]
Ah, I am looking to another repository

**Comment by 1vanK** [comment]
> I never pushed my commits to master branch, only to vs2015 branch.

I have not found this branch in the repository. So is your code in the repository or not?

**Comment by 1vanK** [comment]
Also if someone took your code and submitted it on their own, they should say it in the commit title:

https://github.com/urho3d/Urho3D/commit/861a85fb1f5adbd82b1a3ba8160bad5b6fcc0da4

https://github.com/urho3d/Urho3D/commit/ab675170e74b6a8470603584b15133b75cf4ed5e

**Comment by eugeneko** [comment]
> I have not found this branch in the repository. So is your code in the repository or not?

It was in repository for a while when support of vs2015 was feasible, then it was removed.
I don't know if it should count as contributing. My code **was** used by other people, in the end.

> Also if someone took your code and submitted it on their own, they should say it in the commit title

Git doesn't care about commit title (or so I think), so these people wouldn't go into git statistics.
They should actually author the commit (or be a part of squashed commit) to be counted.

**Comment by 1vanK** [comment]
The point is that you can always find information about the author in the log, if the need arose. Even if the commit was made by another person, original author is written in title. From this point of view, there are no actual lists of authors, except `git log`. Text list is incomplete. https://github.com/urho3d/Urho3D/graphs/contributors is incomplete. So we can just remove text list and link also since they are unreliable.

**Pull request merged**
