### PR TITLE
Update Bullet physics to 2.89.

### PR DESCRIPTION
**Pull request by rokups**
As title says.

### CODE REVIEW

**Comment by 1vanK** [comment]
Is this ready and why is it missing in rbfx?

**Comment by 1vanK** [comment]
I haven't fully explored this, but noticed that you forgot to restore some changes

```
SIMD_FORCE_INLINE   long    btVector3::maxDot( const btVector3 *array, long array_count, btScalar &dotOut ) const
{
#if (defined BT_USE_SSE && defined BT_USE_SIMD_VECTOR3 && defined BT_USE_SSE_IN_API) || defined (BT_USE_NEON)
    #ifdef BT_USE_SSE	// Urho3D - to be consistent with the function return below
```

is missing in your PR

**Comment by 1vanK** [comment]
I suggest updating libraries in a separate repository and move all our commits on top of upstream commits
```
git pull https://github.com/bulletphysics/bullet3 master --rebase
git push origin master --force
```
and the copy to Urho3D. This way we will always know which commits we made and why. At the moment it is rather difficult to understand how the code looked before our intervention.

**Comment by 1vanK** [comment]
Or just store old code in sources (comment but not delete)

**Comment by 1vanK** [comment]
By the way, there is version 3.06+ already

**Comment by 1vanK** [comment]
I am sorry that only now there was time to check the PR. Since there is already a newer version, I created another PR with a newer version.

**Comment by rokups** [comment]
> Is this ready and why is it missing in rbfx?

I could add it to rbfx, or could add it to Urho3D and get it in rbfx too. Choice was to benefit two projects instead of one :)

> I suggest updating libraries in a separate repository and move all our commits on top of upstream commits

Anything would help. I was keeping plain patches in the repo along with source code myself.

> Or just store old code in sources (comment but not delete)

This is what i already suggested in the forum too.

**Comment by 1vanK** [comment]
> This is what i already suggested in the forum too.

Indeed, I found your message on the forum where you talked about it

**Pull request closed without merging**
