### PR TITLE
fix typo in Quaternion opSub

### PR DESCRIPTION
**Pull request by lieff**

### CODE REVIEW

**Comment by eugeneko** [comment]
Good catch, but...
How did you notice it?

**Comment by lieff** [comment]
Just trying to use Quaternions from script :)

**Comment by lieff** [comment]
For example, for rotation interpolation: Qres = a*Q1 + (1-a)*Q2.

**Comment by eugeneko** [comment]
I wouldn't expect any predictable result from linear interpolation of quaternions. `Slerp/Nlerp` shall be used instead.
Indeed, these functions are implemented via some kind of linear interpolation internally, but I see no reason to use linear interpolation in user code.

**Comment by lieff** [comment]
Yes, It's not linear interpolation of angles (scale interpolated normally though). But sometimes this is what we need.

**Pull request merged**
