### PR TITLE
Initial commit of WebP image support

### PR DESCRIPTION
**Pull request by carnalis**
https://developers.google.com/speed/webp/

Urho3D Resource loading of WebP lossless and lossy formats (*.webp).
Enabled with cmake build option (-D URHO3D_WEBP=1).
Default checks with Valgrind.
SaveWEBP() placeholder, not yet implemented.

### CODE REVIEW

**Comment by cadaver** [comment]
Thanks, will look into this now.

**Comment by cadaver** [comment]
I've pushed "webp" branch to Urho for CI testing across platforms. Made some small changes; I default the library on and SaveWEBP is always in Image's public API, though it will error (differently) if support is not compiled in.

**Comment by cadaver** [comment]
@weitjong Can you comment on the OSX CI build error here, is it related to adding the WebP library, or something else? https://travis-ci.org/urho3d/Urho3D/builds/256338347

**Comment by weitjong** [comment]
That build failure was caused by our old workaround (hack) for CMake/Xcode generator which is not needed anymore by CMake version 3.9. After you merged commits from latest master branch, all is good now.

**Comment by cadaver** [comment]
Thanks. I'll merge to master and we'll see then how it goes, if any further issues on some platforms / with some users.

**Comment by cadaver** [comment]
@carnalis: Merged to master now. Feel free to complete the save functionality in separate PR in the future.

**Pull request closed without merging**
