### PR TITLE
Initial commit of updating to SDL 2.0.4

### PR DESCRIPTION
**Pull request by boberfly**
Initial commit of updating to SDL 2.0.4, I recommend not to pull this in just yet, just keep this here for safe-keeping so there's no duplicate work later once 2.0.4 is stable.

This is based on this revision:
https://hg.libsdl.org/SDL/file/734c90ea9990

The reasoning behind this is I wanted GLES 3.1 context-creation which has been patched for 2.0.4, but instead of just grabbing the latest EGL-related code I just dumped the latest SDL 2.0.4 on top and brought back the Urho3D-specific changes on top, except for a few which seem to be fixed or the code-base differs greatly. Some things like hard-code disable of the emulated mouse for Android has been omitted, as there's now a way to set this using a hint (haven't patched or tried this yet). Also some iOS 8 'hack' has been omitted as the code-base differs also.

Also changed the SDL_SendKeyboardKey function so the 'raw' keycode is called raw instead of keycode (the function now uses this variable name for something else internally). And I also patched the backends which didn't have this modification.

As always, test this code first (I haven't got every platform to test this against).

### CODE REVIEW

**Comment by boberfly** [comment]
- I forgot about SDLActivity.java that will need to be somehow munged up with the changes...

**Comment by cadaver** [comment]
Thanks, will be watching this!

**Comment by hdunderscore** [comment]
It appears there is a SDL 2.0.4 stable release now.

**Comment by boberfly** [comment]
Aha, something to do on the weekend if I get some time...

**Comment by hdunderscore** [comment]
I'm interested in seeing this progress, I would like to try out Urho3D on my Windows Phone eventually-- although that will probably require a few extra steps after this PR.

**Comment by vincentwx** [comment]
I hope Windows 10 UWP support is coming so that I try it on my windows phone as well.

**Comment by weitjong** [comment]
@boberfly May I know whether you actually made any necessary code change or you just merge the changes from 2.0.4 then applying our local changes on top of the merged result?

I had a brief discussion with @cadaver a few weeks ago about using git subtree approach for our 3rd-libraries (whenever possible) to facilitate future upstream merge process. I would like to try to locally do that for SDL, therefore the above question.

**Comment by valera-rozuvan** [comment]
Hey there @boberfly ! Great work = ) I am also working on this in https://github.com/urho3d/Urho3D/pull/1172 . Also, if you haven't seen this for yourself, take a look at the diff betwen Urho3D SDL 2.0.3 and the Official SDL 2.0.3: https://github.com/valera-rozuvan/SDL_203/pull/1 .

Do you want to work together on getting SDL 2.0.4 into Urho3D? = )

**Comment by boberfly** [comment]
@weitjong very sorry for not seeing this sooner! I merged whatever was in the latest HG at the time on top of what Urho3D had, and then fine tooth combed the custom changes whenever I saw a 'Modified by <developer> for Urho3D.' Some files had to be removed and the CMakeLists was tweaked for Android because there was some shuffling there. Some stuff like the iOS integration was vastly different, same for the Android java bits so I tried my best to get something in the middle. Untested on iOS but it seemed to do something workable on Android. I also needed to modify the EGL stuff so I could get an ES 3.0 context, as well as incorporating the RaspPi funky EGL stuff.

@valera-rozuvan also sorry for not replying sooner! I think weitjong's branch is in a good place now.

On the bright side, I'll make sure to do a pull request of my ES3.0 changes once SDL 2.0.4 lands...

**Comment by weitjong** [comment]
No worry. I just want to find out what "original" bits that you have put into your initial attempt. For sure they are not in the SDL-2.0.4-upgrade branch that I am working on. 

> On the bright side, I'll make sure to do a pull request of my ES3.0 changes once SDL 2.0.4 lands...

But I think you have that covered.

**Comment by boberfly** [comment]
Yeah I don't remember now to be honest. I don't think I put in any original bits apart from the EGL stuff, which might be still with me here locally as I thought it was too dodgy to put in the push. If something does come up, I can just send over patches atop of yours.

**Pull request closed without merging**
