### PR TITLE
Added EventProfiler

### LINKED ISSUE #1360: EventProfiler
hey 
What do you think of an EventProfiler ? It just inherits from the profiler class (for now) to create a new class. 
The problem was that i had to somehow save the eventnames (if StringNames are used for the event IDs, that would be easier to implement), so i used a static HashMap ...

modified:
> // Object.h
> /// Register event names.
> struct EventNamesRegistrar
> {
>     static StringHash RegisterEventName(const char* eventName);
>     static HashMap<StringHash, String> eventNames_;
> };
> 
> /// Describe an event's hash ID and begin a namespace in which to define its parameters.
> #define URHO3D_EVENT(eventID, eventName) static const Urho3D::StringHash eventID(EventNamesRegistrar::RegisterEventName(#eventName)); namespace eventName

and added 
> // Object.cpp
> void Object::SendEvent(StringHash eventType, VariantMap& eventData)
> {
> ...
> #ifdef URHO3D_PROFILING
>     Urho3D::AutoEventProfileBlock autoEventprofileblock(GetSubsystem<Urho3D::EventProfiler>(), EventNamesRegistrar::eventNames_[eventType].CString());
> #endif
> ...

thats how it looks
http://imgur.com/NbPJfrY

### PR DESCRIPTION
**Pull request by svifylabs**
hey this resolves #1360 
It is my first try for an event profiler. 
It uses the same logic as the profiler. 
It collects events from Object::SendEvent(StringHash eventType, VariantMap& eventData).

Event names are collected in a global HashMap see EventNameRegistrar in Object.h.
Should EventNameRegistrar be in a URHO3D_PROFILING block as well ? 

I dont like the activation and deactivation process, if possible i want just use RegisterSubsystem and  RemoveSubsystem for that. What do you think?

### CODE REVIEW

**Comment by cadaver** [comment]
The initial performance hit comes already from trying to look up the EventProfiler subsystem. That's why I suggested a static bool flag in Object class (could also be a static in EventProfiler), to avoid the lookup if event profiling is not wanted. I agree that the mechanism to activate/deactivate EventProfiler as its instance member function is unnecessary.

**Comment by cadaver** [comment]
There seems to be a misunderstanding. I don't think subsystems should be queried for statically. Rather I just suggested having a static bool be checked first for whether event logging should be done. If that bool is true, then get the subsystem normally.

**Comment by svifylabs** [comment]
ah sry i just had to test something ... did forget to branch it out sry. will remove that.
but is that something usefull or really bad to do ?

**Comment by cadaver** [comment]
I think it's better to require an access to Context for normal (non-static) subsystem query. Sending events requires a valid Object in any case, which means it will have Context instance access.

Logging is the only exception; it holds a Log instance pointer itself so that logging can be called statically without a valid Object.

**Comment by 1vanK** [comment]
Hm,
```
         screenshot.SavePNG(fileSystem.programDir + "Screenshot_" +
                            time.timeStamp.Replaced(':', '_').Replaced('.', '_').Replaced(' ', '_') + ".png");
```
does not works, when path contains cyrillic chars (and no any warnings in log), but
```
screenshot.SavePNG("Screenshot_" +
                            time.timeStamp.Replaced(':', '_').Replaced('.', '_').Replaced(' ', '_') + ".png");
```
works.

By the way, log.Error() is missing in doc http://urho3d.github.io/documentation/HEAD/_lua_script_a_p_i.html

**Comment by cadaver** [comment]
WriteRaw is "Print" in AngelScript API. Could also expose at least the basic form of WriteRaw.

SavePNG is stbi_image_write territory, which may not support utf8 paths as expected. It would be preferable to get just a memory buffer from it and handling file IO with Urho files.

**Comment by 1vanK** [comment]
> WriteRaw is "Print" in AngelScript API. Could also expose at least the basic form of WriteRaw.

I understood my mistake, that I opened wrong doc page (LUA insted AS) XD

**Comment by cadaver** [comment]
It seems we can write images to memory and save to file manually, which could work more reliably.

**Comment by weitjong** [comment]
After merging and reviewing this commit, I feel there are too many code duplication in the EventProfiler and EventProfilerBlock classes. So, I decided to refactor them to subsclass from Profiler and ProfilerBlock classes, respectively, and have been successful in doing so. However, IMHO, what left behind after my refactoring do not really warrant for creation of new classes at all. I feel I can go further to eliminate them but still preserving the new "event profiling" functionality some how. Should I go further?

**Pull request merged**
