### PR TITLE
Limit number of channels to avoid issues on multichannel audio device

### PR DESCRIPTION
**Pull request by gleblebedev**
Limit number of channels to avoid issues on multichannel audio device (5.1, 7.1, etc)

The issue is present on, for example, Logitech G933 headphones with surround sound enabled. 

Bug: https://github.com/urho3d/Urho3D/issues/2718

### CODE REVIEW

**Comment by 1vanK** [comment]
I see problems here and discuss them in private messages with Gleb

**Comment by eugeneko** [comment]
Code looks okay tho. What's wrong with it?

**Comment by 1vanK** [comment]
1. The source of the bug is unknown
2. Even without delving into the search for a bug, the initialization should occur to other way
2.1 If stereo required request exactly 2 channels
2.2 If wailed or mono required request exactly 1 channel

But even this way is not very good, because it would be to find the source of the bug and save access to 8 channels for future use in SoundSource3D.

Currently correct bugfix should be using 2 channels only if more than 2 are available

**Comment by gleblebedev** [comment]
`Currently correct bugfix should be using 2 channels only if more than 2 are available`

I don't agree with that. 

The Logitech g933 headphones report to system as 7.1 setup but actually then mix 8 channels into 2 applying some variation of HRTF to provide surround sound effect. Using only 2 channels may apply unnecessary distortion to the sound.

When played via proper 7.1 setup and using only 2 channels would result in playing only on left and right speakers. Initializing stereo device on 7.1 setup would enable single processing where lower sounds would go to subwoofer and the rest would be distributed between all speakers.

Let hardware do it's thing.

**Comment by 1vanK** [comment]
Ok, then just fix initialization

**Pull request merged**
