### PR TITLE
Extra NavigationMesh pathfinding options

### PR DESCRIPTION
**Pull request by hjmediastudios**
This adds a new function to the `NavigationMesh` class to return flagged points. This allows waypoints in the calculated path to be recognized as off-mesh connections, for example; an AI-controlled character could perform a jump action, climb a ladder, or so on triggered by arriving at a special off-mesh connection.

### CODE REVIEW

**Comment by cadaver** [comment]
You'll need to resolve this PR's conflicts now that the other navigation PR was merged first.

**Comment by weitjong** [comment]
I believe he has included the commits for this PR into the PR #1083 that you just merged, making this one now redundant.

**Comment by cadaver** [comment]
The changes were there for a while, but I believe the final commits in that branch reversed the changes. E.g. there is no NavigationPathPoint struct in NavigationMesh.h now.

**Comment by hjmediastudios** [comment]
Let's see if that did it; my latest changes should have resolved the conflicts.

**Comment by weitjong** [comment]
Something is fishy about the commit history. The PR now also contains changes from your other branch.

**Comment by cadaver** [comment]
In case the features are hard to separate properly, I don't have problems with taking this and the JSON changes as one PR. In this case the another of them should be closed.

**Comment by hjmediastudios** [comment]
I'll separate them out when I get home from work today; any errors are just me clumsily using Git wrong.

**Comment by cadaver** [comment]
Merged as squashed.

**Pull request closed without merging**
