### PR TITLE
Add support of arbitrary data in Sound, Animation and Texture resources.

### PR DESCRIPTION
**Pull request by eugeneko**
I found it useful.
Please, review. Discussion about naming is open.

It would be great to have such ability for all binary resources, but I don't know nice way to implement it.

Example:
```
Animation@ anim = cache.GetResource("Animation", "Animations/Kachujin_Idle.ani");
Print(anim.metadata["speed"].GetFloat());
anim.metadata["dir"] = Variant(Vector3(1, 1, 1));
Array<Variant> vec;
vec.Push(Variant("String"));
vec.Push(Variant(10));
vec.Push(Variant(15.0));
anim.metadata["vec"] = Variant(vec);
anim.Save(cache.resourceDirs[0] + anim.name);
```

### CODE REVIEW

**Comment by cadaver** [comment]
It's a good idea. Would probably be worth it to use this mechanism to replace all the existing resource "side-by-side" xml's, e.g. textures and sounds too, but that would be a larger work.

**Comment by cadaver** [comment]
If you want to merge this before release, it's OK by me, as it's still useful, and expanding it to encompass more resources would be a large work.

**Comment by eugeneko** [comment]
I'll look into this PR this day, then decide.

**Comment by eugeneko** [comment]
Ok, I implemented this that way.

I dislike names like `ObjectWithSomething`, but I don't know better name. I decided to integrate this feature into main hierarchy to avoid copy-paste and keep hierarchy simple.

It is also possible to make metadata container class outside of hierarchy and use multiple inheritance to attach it to resources. However, this makes hierarchy more complicated and probably causes problems e.g. in C# facade.

**Comment by cadaver** [comment]
Looks fine. Should also be fairly safe as nothing in the existing side-by-side xml parsing changes. Can go in to master by me.

**Comment by eugeneko** [comment]
Ok, I tested it a bit. I'll merge it now, I hope I won't break anything.

**Pull request merged**
