### PR TITLE
Feature/state machine

### PR DESCRIPTION
**Pull request by KatekovAnton**
PR contains:
- Unit testing target (separate pr is opened here https://github.com/urho3d/Urho3D/pull/2665 )
- State machine classes
- Tests for state machine
- Sample scene project (55)
- Extra assets for good looking scene

The idea is - you modify parameters - state machine change its state

### CODE REVIEW

**Comment by gleblebedev** [comment]
Preview

**Comment by eugeneko** [comment]
Can we avoid copy-pasted shaders? We have more than enough shaders to maintain, we don't need more.
Also, what's the license of assets? If assets are yours, fine. If not, please link to asset source and license.

**Comment by gleblebedev** [comment]
@eugeneko shaders and techniques are duplicates. @KatekovAnton you can remove shaders and techniques (except water) as they been merged into urho main branch already.

**Comment by KatekovAnton** [comment]
@eugeneko done. it was not copy-pasted - it was created by exporter. @gleblebedev we can now only export BRDF and PBRWater since shaders are merged

**Comment by KatekovAnton** [comment]
Hold on. I will add one more thing

**Comment by 1vanK** [comment]
What license is the content distributed under?

**Comment by 1vanK** [comment]
> bin/HouseScene/Content/Houses/CanyonHouse/testHouse0Стекла.005.mdl 

Cyrillic in the paths

**Comment by KatekovAnton** [comment]
> Cyrillic in paths

Content creator did in this way. As far as I can see it is supported by the engine.

**Comment by 1vanK** [comment]
Yes, but agree, you would be surprised if you saw hieroglyphics or Arabic text.

Anyway, I think the external repository is the best place for your example.

**Comment by KatekovAnton** [comment]
@1vanK I have removed Cyrillic from assets.
@eugeneko I have removed shaders and techniques.

Should be good now

**Pull request closed without merging**
