### PR TITLE
Ambient occlusion in PBR techniques

### PR DESCRIPTION
**Pull request by gleblebedev**
PBR techniques generated via script https://gist.github.com/gleblebedev/c01fa7c9a1c5bff273c9cbd3020d3b89
It adds all possible permutations and fix existing techniques.
Also AO made to use same texture coordinates as all other textures except lightmap texture.

### CODE REVIEW

**Comment by ChrisDenham** [comment]
Yay! I was about to ask about the missing AO techniques in PBR. Spotted this PR, just in time. 👍

**Comment by 1vanK** [comment]
Before merging I need test some scene with AO. Can you provide any? (Not as PR, just drop zip here in comments or to any file hosting)

**Comment by gleblebedev** [comment]
Test scene for AO: https://github.com/gleblebedev/Urho3DPBRTestScene

**Comment by gleblebedev** [comment]
@ChrisDenham @1vanK https://discourse.urho3d.io/t/ao-to-use-first-set-of-texture-coordinates/6263

**Comment by ChrisDenham** [comment]
I just got around to trying AO in PBR techniques. Thank you for adding this. :-)

**Pull request merged**
