### PR TITLE
Some issues fixed

### PR DESCRIPTION
**Pull request by igorsegallafa**
I did some modifications to fix the issues that I found:

- Fixed a bug where painting brush on Terrain Editor is always active
- Fixed some warnings caused on Sample2D and changed the code to pass structs by reference, instead of by value (when possible)
- Fixed a bug where CharacterMap::Load is always returning false
- Fixed a bug on AnimatedSprite2D animation (alpha animation was not working properly)
- Fixed a bug on vertical progress bar orientation
- Increased the messages ID's range available (unsigned int instead of byte)

### CODE REVIEW

**Comment by eugeneko** [comment]
Can you fix formatting in PR, please?

**Comment by igorsegallafa** [comment]
> 
> 
> Can you fix formatting in PR, please?

I changed the PR right now, if you can tell me what you need specifically I will be grateful, because this is my first PR for Urho3D. 

Thanks.

**Comment by eugeneko** [comment]
@igorsegallafa I was talking about indentation in files. Just open "Files changed" tab and you will see all the places where it is broken.

**Comment by igorsegallafa** [comment]
> 
> 
> @igorsegallafa I was talking about indentation in files. Just open "Files changed" tab and you will see all the places where it is broken.

Aah I didnt noticed that you guys use identation with spaces instead of tab. Fixed.

**Comment by eugeneko** [comment]
Can you also explain changes in xml file?

**Comment by igorsegallafa** [comment]
> 
> 
> Can you also explain changes in xml file? This piece of PR is quite hard to read.

I added the reset button to Terrain Window, this is the only difference. Button will set edit mode to "Raise or lower terrain" and clear selected brush.

Everything else is the same, I am sure.

terrainwindow

**Comment by iSLC** [comment]
Seems to be a spacing issue there as well. Probably done by some IDE or editor automatically.

**Comment by igorsegallafa** [comment]
> 
> 
> Seems to be a spacing issue there as well. Probably done by some IDE or editor automatically.

Hmm I don't think so, I changed all issues with indentation to use spaces instead of tab. About XML I edited the window with Urho editor, so indentation is correct. Probably has more changes than a simple button, because the order of UI elements has changed (I had to recreate Close button to keep after of Reset button).

**Comment by iSLC** [comment]
I meant that the XML has changed indentation from spaces to tabs. That's why it appears that the whole XML file was changed.

I was aware that you fixed the indentation from the code.

**Comment by eugeneko** [comment]
> I meant that the XML has changed indentation from spaces to tabs. That's why it appears that the whole XML file was changed.

@iSLC There's more. We had hand-crafted XML before, but now we have XML saved from Editor.

I'm not sure, however, what's the best way to go: maintain hand-crafted XML or replace it with generated XML.

**Comment by igorsegallafa** [comment]
I can maintain the hand-crafted XML for now and later we can decide about it. Because for use the generated XML we will need to re-save everything, but I guess this is not the purpose for this PR.

**Comment by igorsegallafa** [comment]
The latest commit I did a modification at Urho networking. Now is possible to use more ID's on Urho Messages, from unsigned byte, for unsigned int. Only urho messages was affected, SLikeNet messages keep the same.

For bigger games, 121 messages ID's available (255-134) may be too little, for this I did this modification.

**Comment by weitjong** [comment]
Thanks for your PR. I think you need to separate the proposed changes into individual PRs because your commits seem to be unrelated to each other.

**Comment by igorsegallafa** [comment]
It was my purpose when I tried close the PR, but didnt work. So I will have to create temporary branches to separate PRs. I will do this.

**Pull request closed without merging**
