### PR TITLE
Replaced tab with spaces

### PR DESCRIPTION
**Pull request by Modanung**
I found a tab and replaced it with spaces.

### CODE REVIEW

**Comment by nem0** [comment]
I suggest replacing all spaces with tabs, since tabs are way superior. For example it makes it harder for disabled people to use screenreaders on the code.

**Comment by Modanung** [comment]
Down with tabular supremacy!
..._space_, space, _space space_...

**Comment by weitjong** [comment]
If you want to be thorough, there are two more files with tab(s) in the "Sample" directory.

```
[weitjong@aurora Urho3D]$ git grep -l ' ' upstream.master -- Source/{Samples,Urho3D}
upstream.master:Source/Samples/53_LANDiscovery/LANDiscovery.cpp
upstream.master:Source/Samples/53_LANDiscovery/LANDiscovery.h
upstream.master:Source/Urho3D/AngelScript/NetworkAPI.cpp
upstream.master:Source/Urho3D/Network/NetworkEvents.h
upstream.master:Source/Urho3D/Resource/Image.cpp
upstream.master:Source/Urho3D/Urho2D/AnimatedSprite2D.cpp
upstream.master:Source/Urho3D/Urho2D/CollisionChain2D.cpp
```

**Comment by nem0** [comment]
> Down with tabular supremacy!
> ..._space_, space, _space space_...

You need 4 spaces to replace one tab. That alone proves that tabs are 4 times more valuable.

**Comment by Modanung** [comment]
@nem0 Spaces are versatile, flexible and stand the test of time.

**Comment by weitjong** [comment]
Thanks!

**Pull request merged**
