### PR TITLE
Add WEBP image format support

### PR DESCRIPTION
**Pull request by cosmy1**
Saw this as feature request so I decided to implement it.

### CODE REVIEW

**Comment by cosmy1** [comment]
Tested with libwebp-0.4.4 binary version.
libwebp doesn't support CMake build system so I don't know how to deal with CMake scripts.

**Comment by cadaver** [comment]
The library looks like quite huge for just the support of one (relatively little-known) image format, so I don't think I'd be comfortable including it in Urho3D in any case. 

In this case you could make Urho3D's build detect if the developer has libwebp (via CMake's find_package function) and if so, set the URHO3D_WEBP define and include the functionality.

**Comment by cosmy1** [comment]
I don't know CMake scripting so if someone want to deal with it would be cool so this PR can be merged and close #713 .

**Comment by JSandusky** [comment]
It'd be a nice courtesy to print the expected chunk ID when it fails to find WEBP (similar to "Sound"s declaration that it was trying to load a WAV file) or enforce the use of the webp extension for webp loading.

ANI and AVI are both valid uses of the RIFF container that are plausibly loadable into Image and RIFF is still pretty heavily utilized as a container for proprietary data as well. Logging the expected chunk ID will at least indicate that the wrong resource type was assigned or that something was overlooked.

**Comment by cosmy1** [comment]
Ok. Now it prints expected and found header chunk ID.

**Comment by cosmy1** [comment]
Closing this as is not a very common format for game development

**Pull request closed without merging**
