### PR TITLE
unsynchronized_jacks

### PR DESCRIPTION
**Pull request by juj**
Make Jacks not walk in synchronized lockstep timing in 06_SkeletalAnimation sample.

### CODE REVIEW

**Comment by cadaver** [comment]
It would be preferable to make the same change in AngelScript & Lua versions of the samples too.

**Comment by juj** [comment]
Thanks, updated. However I don't know how to run the AngelScript and Lua versions, does the API look correct for them?

**Comment by JSandusky** [comment]
Just tested angelscript version. It's correct.

**Comment by cadaver** [comment]
To run the scripts: urho3dplayer <path_to_scriptfile>. Both versions seemed to be OK.

**Pull request merged**
