### PR TITLE
Feature/state machine #1

### PR DESCRIPTION
**Pull request by KatekovAnton**
Following up https://github.com/urho3d/Urho3D/pull/2669 

PR contains:
- Unit testing target (separate pr is opened here https://github.com/urho3d/Urho3D/pull/2665 )
- State machine classes
- Tests for state machine
- Sample scene project (55)
- Extra assets for good looking scene

The idea is - you modify parameters - state machine change its state

### CODE REVIEW

**Comment by UkoeHB** [comment]
Hi, I plan on trying out your unit testing PR this weekend. One comment in passing: this PR seems to be 3 PRs rolled into one. There is duplicate code from PR #2665, the state machine implementation, and a sample for the state machine. It may be easier to review if the duplicate code is removed and this is split into two PRs for the implementation and sample. Or even three PRs, for implementation, state machine unit tests, and sample.

**Comment by KatekovAnton** [comment]
@UkoeHB hi
> There is duplicate code from PR #2665
its not a duplicated, I just need my another PR to be merged to cover state machine with unit tests. My assumption was that   PR #2665 will be merged first. But it was delayed.

**Comment by KatekovAnton** [comment]
bump

**Comment by 1vanK** [comment]
Your PR does not follow Urho's code style. It is also not a necessary part of the engine and should not be in this repository. We could include the code to the Urho3D-CE, but I feel like it will be abandoned soon. We don't have people who would like to tidy up someone else's code.

**Pull request closed without merging**
