### PR TITLE
Fixed event data names in AS sample 25

### PR DESCRIPTION
**Pull request by Modanung**
Liberates emitter from screen corner.

### CODE REVIEW

**Comment by weitjong** [comment]
Thanks for your PR. Can you do the same for the LUA sample as well.

```
$ git grep eventData -- bin |grep -P '"(?:x|y)"'
bin/Data/LuaScripts/25_Urho2DParticle.lua:        local x = eventData["x"]:GetInt()
bin/Data/LuaScripts/25_Urho2DParticle.lua:        local y = eventData["y"]:GetInt()
bin/Data/Scripts/25_Urho2DParticle.as:        float x = eventData["x"].GetInt();
bin/Data/Scripts/25_Urho2DParticle.as:        float y = eventData["y"].GetInt();
```

**Comment by Modanung** [comment]
No

**Comment by Modanung** [comment]
Well, ok then.

**Comment by weitjong** [comment]
Thanks!

**Pull request merged**
