### PR TITLE
Add view matrix

### PR DESCRIPTION
**Pull request by hjmediastudios**
Added a view matrix uniform to the shader code. The impetus for this is to allow me to convert world-space normals into view-space normals to perform SSAO calculations in the rendering pipeline.

### CODE REVIEW

**Comment by cadaver** [comment]
Shouldn't be a problem to merge. There are a couple of added hashmap lookups every time the camera changes, but the impact shouldn't be significant unless one is changing shaders or camera for every drawcall, which would be bad anyway.

**Comment by ucupumar** [comment]
Nice! I've been looking for default view matrix for quite some time. This will be huge time safer for some of custom shader creation.

**Comment by MonkeyFirst** [comment]
I want to mention one thing.
the matrix
const Matrix3x4& view = camera->GetView(); is already inversed in 
```
const Matrix3x4& Camera::GetView() const
{
    if (viewDirty_)
    {
        // Note: view matrix is unaffected by node or parent scale
        view_ = GetEffectiveWorldTransform().Inverse();
        viewDirty_ = false;
    }

    return view_;
}
```
so your graphics_->SetShaderParameter(VSP_VIEWINV, view.Inverse()); 
is actually double inversing I guess

**Comment by cadaver** [comment]
Using simply GetEffectiveWorldTransform() should work and save the work of double-inverse. Can make that change when merging.

Btw. after merging this the separate CameraPos & CameraRot uniforms could be removed, since they can be derived from the view inverse.

**Pull request merged**
