### PR TITLE
Update Box2D lib, add RigidBody2D::ApplyLinearImpulseToCenter()

### PR DESCRIPTION
**Pull request by 1vanK**
Not completed, just test compiling

### CODE REVIEW

**Comment by 1vanK** [comment]
appveyor uses old version of ThirdParty dir?

**Comment by weitjong** [comment]
Probably, but I am/was expecting CMake to do it's wonder in this scenario. Anyway, sorry for the inconvenience.

**Comment by 1vanK** [comment]
I think it is completed

**Comment by cadaver** [comment]
Thanks, hope to check today or soon.

**Comment by 1vanK** [comment]
But I still doubt about m_useFixtureMass/

**Comment by cadaver** [comment]
I can go back and review the change where it was added. It was to fix a bug with kinematic modes if I remember right. It should be quite obvious to see if it's still needed.

**Comment by 1vanK** [comment]
Hm, I found issue xD https://github.com/urho3d/Urho3D/issues/844

**Comment by 1vanK** [comment]
May be is way to restore mass after CreateFixture() and DestroyFixture() if useFixtureMass is enabled without modify box2 lib. 
It will facilitate the following update of library

**Comment by cadaver** [comment]
If that works, it's better. Lib changes are always nasty.

**Comment by cadaver** [comment]
Merged, thanks!

**Pull request merged**
