### PR TITLE
Changed logo in samples to fish bone logo

### PR DESCRIPTION
**Pull request by Modanung**

### CODE REVIEW

**Comment by cadaver** [comment]
Cool, will check.

**Comment by cadaver** [comment]
Works well and is power-of-two so no trouble on mobiles. Lua implementation was missing but I can add it before merging.

@weitjong Was this variant of the logo OK for you? (the one with thick green outline and black edge outline)

**Comment by weitjong** [comment]
Thanks for asking. I have stated my preferences in the forum. Having said that, I am fine with this one too, if you are OK with it.

**Comment by cadaver** [comment]
I will meditate on these a bit.

**Comment by cadaver** [comment]
Black/white version of fish bone logo (urho3d_nofin) has been put in, with svg source put to SourceAssets.

By me it's now fine if this logo replaces the old everywhere.

**Comment by Modanung** [comment]
I must say I like the dark green outline way better. Especially in the samples. To me it was quite obvious that version was the right one.
Also the green version was no option yet, the last time anyone shared their preference.

**Comment by 1vanK** [comment]
I continue to believe that simple black-and-white version better suited for logotype. Just my opinion.

**Comment by Modanung** [comment]
Have you tried both with several samples?

**Comment by 1vanK** [comment]
no, I chose as a logo, which will be on the site, on splash screen, etc.

**Comment by Modanung** [comment]
Have you tried both on a black background?

**Comment by 1vanK** [comment]
no

**Comment by 1vanK** [comment]
On black bacground (splashscreen) i will use inverted image (white contour)

**Comment by Modanung** [comment]
Ok... tried that: Yulgh

**Comment by Modanung** [comment]
I'll crawl back into my LucKey hole I guess.

**Comment by 1vanK** [comment]
may be make some vote?

**Comment by Modanung** [comment]
All I need to do is make a comparison image and everyone will agree.
Can you believe that, and spare me the work?

**Comment by 1vanK** [comment]
May be add both variants? Colored for samples and BW for logo?

**Comment by Modanung** [comment]
Logo comparison

**Comment by Modanung** [comment]
Ok, maybe the coloured version could use a little slimming down with the extra outline.
Slimmed down logo

**Pull request closed without merging**
