### PR TITLE
Misc terrain speedups

### PR DESCRIPTION
**Pull request by moneromooo**
This one has many patches, you may want to select the ones you want.

### CODE REVIEW

**Comment by eugeneko** [comment]
That's... a lot of code.
I will try to look at it later.

Does it make rendering faster or just terrain creation?
Also, how much faster does it work?

**Comment by moneromooo** [comment]
Terrain creation, I create chunks on the fly. I have no timings, but definitely noticeable when moving around and loading new chunks.

**Comment by eugeneko** [comment]
It may be silly question, but I have to ask. Do you test release or debug builds?

**Comment by moneromooo** [comment]
Release. I did an ASAN build a while ago, too, didn't find anything, though I'm not sure this was before or after the terrain patches.

**Pull request closed without merging**
