### PR TITLE
Add missing translation in editor strings (FR, IT)

### PR DESCRIPTION
**Pull request by cosmy1**

### CODE REVIEW

**Comment by cosmy1** [comment]
It still miss Russian translation... If someone is able to translate "Tags", the editor will be fully localized (again).

**Comment by weitjong** [comment]
> It still miss Russian translation... If someone is able to translate "Tags", the editor will be fully localized (again).

Nope. It also needs zh-CN to be truly fully localized :smiley:

**Comment by 1vanK** [comment]
> It still miss Russian translation... If someone is able to translate "Tags", the editor will be fully localized (again).

Теги

**Comment by cadaver** [comment]
Thanks! Will merge.

**Pull request merged**
