### PR TITLE
Updated sound effects sample to use SetAutoRemoveMode() instead of nodes

### PR DESCRIPTION
**Pull request by Enhex**

### CODE REVIEW

**Comment by 1vanK** [comment]
What about lua and as examples?

**Comment by cadaver** [comment]
Nice code simplification!

**Comment by Enhex** [comment]
There's a bug in the Lua bindings (`AudioLuaAPI.cpp` line `2335`):
```C++
AutoRemoveMode mode = *((AutoRemoveMode*)  tolua_tousertype(tolua_S,2,0));
```
should be
```C++
AutoRemoveMode mode = *((AutoRemoveMode*)  tolua_tousertype(tolua_S,1,0));
```

Lua bindings seems to be automatically generated, and I don't know how it works in order to fix it (in case it isn't just something messed up on my side).

**Comment by eugeneko** [comment]
> should be

I don't understand why.

**Comment by cadaver** [comment]
Looks possibly related to this, and it's an ancient bug: http://lua-users.org/lists/lua-l/2004-01/msg00193.html

**Comment by eugeneko** [comment]
> Looks possibly related to this, and it's an ancient bug

Huh... The @Enhex 's question is about index, but your link is about syntax... I doubt that it is related.

**Comment by weitjong** [comment]
> Huh... The @Enhex 's question is about index, but your link is about syntax... I doubt that it is related.

No, I think I agree with @cadaver that it is related.

**Comment by weitjong** [comment]
Adding these lines in the ```SoundSource.pkg``` seem to correct the auto-generated binding.

```
enum AutoRemoveMode
{
    REMOVE_DISABLED = 0,
    REMOVE_COMPONENT,
    REMOVE_NODE
};
```

**Comment by cadaver** [comment]
I remember we've done that elsewhere too. So that is the reason :)

**Comment by eugeneko** [comment]
May somebody explain what's wrong in generated binding?
I mean in this case, not at posted link.
I don't understand :(

**Comment by weitjong** [comment]
The way I understand it the problem is caused by tolua++ makes a wrong assumption when it first encounters the "AutoRemoveMode" symbol. It didn't know what it is and erroneously assumed it to be one of a user type. By explicitly declaring "AutoRemoveMode" is an enum then tolua++ knows what it is correctly and generates the binding accordingly.

**Comment by eugeneko** [comment]
[offtop] *confused* I haven't noticed any changes in generated files after rebuild.

**Pull request merged**
