### PR TITLE
Console auto complete

### PR DESCRIPTION
**Pull request by Enhex**
Console auto complete feature.

Didn't include binding for Lua.

### CODE REVIEW

**Comment by cadaver** [comment]
Great idea. However Urho itself is not yet mandatorily C++11 so please avoid using auto in engine code. Also it would be preferable to use Urho containers and not leak std containers to Urho headers. There's also a minor compile issue due to a class member being initialized in header, which should be easily fixable.

**Comment by Enhex** [comment]
Working on fixing these issues.
BTW Urho doesn't provide an alternative for std::set, which is ordered (needed for searching results in order).
I'll just replace it with a sorted vector of unique elements, which should increase complexity and insertion removal cost, while reducing search cost.

**Comment by darwikey** [comment]
Or you can use HashSet instead of std::set

**Comment by Enhex** [comment]
HashSet isn't ordered

**Comment by Enhex** [comment]
If you're going to manually order you're better off using vector for better search performance.

Since the vector is sorted search can be optimized with `std::lower_bound` and `std::lower_bound`, but I'm getting compiler errors that seems to be related to Urho3D::Vector's Iterator type.

**Comment by cadaver** [comment]
Merged slightly changed. I got a crash when pressing up in sample 26 as the first thing, and since there were potential problems with iterator invalidation, I changed the system to use a position index. Feel free to make a new PR in case I messed something up.

**Pull request closed without merging**
