### PR TITLE
log message colour in console displayed based on it's type

### PR DESCRIPTION
**Pull request by ArnisLielturks**

### CODE REVIEW

**Comment by eugeneko** [comment]
_offtop_
Why every second contributor ignores codestyle?..

**Comment by ArnisLielturks** [comment]
@eugeneko Thanks for pointing this out!

**Comment by weitjong** [comment]
Is there any special reason why you remove the "hover" attribute in the base console text style? Note the previous highlighted style was based on it so the attributre got inherited. Probably you can use an array of styles indexed by log level instead of using if-else blocks.

**Comment by ArnisLielturks** [comment]
@weitjong Can you take a look at the latest changes? Changed the code according to your suggestion. And relating to "hover" effect, it was removed by mistake since I used the styles from one of the projects that I'm working on.

**Comment by ArnisLielturks** [comment]
Console appearance after these changes: http://imgur.com/a/Eb3AG

**Comment by weitjong** [comment]
It looks ok by me.

**Comment by cadaver** [comment]
Yes, the changes look rather clean/minimal now, and also screenshot is fine.

**Pull request merged**
