### PR TITLE
Multi line

### PR DESCRIPTION
**Pull request by markomiz**
Not perfect yet, better text highlighting is needed in future as well as other little bits. SetMultiLine(bool enable) toggles multi line functionality.

### CODE REVIEW

**Comment by cadaver** [comment]
Tested quickly, basic operation seemed solid.

However it may make more sense to create a new class, for example TextEdit, and keep LineEdit as it is for simple one line editors. The multi-line editor should preferably inherit from ScrollView so that it can show scroll bars (both horizontal and vertical) for large text.

Also, note the code convention! Spaces instead of tabs, brackets on their own line.

**Comment by JSandusky** [comment]
markomiz, would you mind if I picked this up (pushing PRs to your branch)?

**Comment by markomiz** [comment]
Sure, keep me updated.

**Comment by SirNate0** [comment]
Another possible name would be TextArea (from html), but I somewhat favor TextEdit in keeping with LineEdit.

**Comment by Zamir7** [comment]
in Urhosharp from Xamarin upper version 1.0.410,  LineEdit on android is crashed, you know what reason? And multiLine is very needed option... thank you.

**Comment by markomiz** [comment]
If anyone is interested I'm currently using this - MultiLineEdit class I made - I've added some functionality from the commit above. The files attached can be included in your project and don't have to be built with the rest of the game engine.

[src.zip](https://github.com/urho3d/Urho3D/files/339413/src.zip)

**Comment by OldSnake22** [comment]
Hello markomiz, why don't you make a pull request with this new class ? Could be nice to have this in the master branch of Urho :)

**Comment by Zamir7** [comment]
unfortunately I do not know c ++, and use Urhosharp (Urho on c#), i try to translate in C # this class) thank you for great work Markomiz!

**Comment by weitjong** [comment]
The attached code seems to be a little bit dated. We now use key constants in lower cases.

**Comment by markomiz** [comment]
weitjong, in addition to changing names of key constants, having spaces instead of tabs and putting brackets on their own lines are any other changes you would like me to make to make it suitable for a pull request? (I will also move the one function defined in .h file to .cpp)

**Comment by weitjong** [comment]
I think I also agree with @cadaver regarding from where which it should be derived from.

**Comment by markomiz** [comment]
I'm not sure I understand the benefit of inheriting from ScrollView when it is very easy to just set a MultiLineEdit as a content element of the ScrollView?

**Comment by weitjong** [comment]
Very true. I suppose it is from the "ease of use" point of view.

**Comment by m-roberts** [comment]
I must admit, seeing as nothing else appears to inherit from ScrollView, it seems to be that convention is to 'wrap' the scrollable element(s) within a ScrollView.

I'm not sure that it is inherently more sensible from an 'ease of use' point of view to change this in one instance.

**Comment by cadaver** [comment]
Closed as superseded by #1443.

**Comment by weitjong** [comment]
@m-roberts I beg to differ. See http://urho3d.github.io/documentation/HEAD/class_urho3_d_1_1_list_view.html.

**Comment by cadaver** [comment]
ListView inherits from ScrollView. Inheriting ScrollView makes IMO sense from ease of use perspective when there is no anticipated usecase for having composition inside the content element. However, in case we guess wrong and there is indeed a weird usecase, then not inheriting is more flexible.

**Comment by markomiz** [comment]
I use MultiLineEdit sometimes to have several sections of writing, some editable and some not editable, in the same scroll view. In this case I see it as making less sense to inherit from ScrollView. Admittedly though, this is not a very normal use case.

**Pull request closed without merging**
