### PR TITLE
Fix tilemap display problem

### PR DESCRIPTION
**Pull request by Y-way**
The renderer could not properly display tiles that are flipped and rotated.
[#2517](https://github.com/urho3d/Urho3D/issues/2517)

### CODE REVIEW

**Comment by eugeneko** [comment]
Why do we need duplicate conditions for `flipX_`, `flipY_` and `swapXY_`?
This code was unclear even before these changes, now it's even more obscure.

Are you sure it cannot be simpler? Lemme think about this code for a while.

**Comment by Y-way** [comment]
Sorry,I haven`t found any other better way to make it simpler.

**Comment by Y-way** [comment]
Make `StaticSprite2D: : UpdateSourceBatches()` logic clearer

**Comment by Modanung** [comment]
I reordered things a bit, what do you think?
https://github.com/Y-way/Urho3D/pull/1

**Comment by Modanung** [comment]
When testing the tile flipping and saving a TMX with the latest version of Tiled I get:
`ERROR: Invalid version`

**Comment by Modanung** [comment]
The map displays, but the flipping needs some work.

**Comment by Y-way** [comment]
Can this pr be merged?

**Pull request closed without merging**
