### PR TITLE
Bullet update

### PR DESCRIPTION
**Pull request by slapin**
I have updated Bullet to version 2.86.1. Found no issues so far. Urho fixes are applied too.
Found no issues with physics during testing, but probably requires extensive testing anyway.

I was not able to add InverseDynamics library. It is sad, but it depends on Bullet3 stuff - is it OK to merge some of it (Bullet3 stuff) together with InverseDynamics library after this one is merged?

### CODE REVIEW

**Comment by slapin** [comment]
I forgot to mention, but this one
closes #1933

for good.

**Comment by cadaver** [comment]
If you have plans to make Urho components that depend on InverseDynamics, and if any Bullet3 stuff that is pulled in, does not place existing Urho platform compatibility into jeopardy, then by me it'd be OK to work on that.

**Comment by slapin** [comment]
That is long term goal, yes.
It is not something I will do next month though.
I think currently I'm happy with just this update.
I will work with InverseDynamics locally and see the field of work first,
and will proceed with something only after that.

**Comment by Lumak** [comment]
I downloaded and built the stand-alone Bullet release 2.86.1 and there's InverseDynamics example in it, even played with the example that it built.  

Is there another 2.86.1 release without it?

**Comment by slapin** [comment]
@Lumak you don't get it. InverseDynamics requires bullet parts not integrated in Urho (Bullet3 API).
You can look how Bullet is integrated into Urho, that would answer your question.

**Comment by Lumak** [comment]
Yes, I didn't get it because I didn't know what you meant by "Bullet3 stuff." I did look at the src directory in Bullet, though, and see that you are referring to the library folders.

bullet2 86 1libs

There's a whole lot of folders missing compared to the official 2.86.1 release.

**Comment by slapin** [comment]
Well, that is not my invention, you could check how previous versions are integrated in Urho.

**Comment by Lumak** [comment]
Could this PR be even considered as update to Bullet 2.86.1 with all that it's missing? I also don't get that.

**Comment by slapin** [comment]
I don't care as long as it fixes bugs I encounter. This is how bullet is
used to be updated here. If you don't like it, I'm not a person to discuss
that with.

I think you should better do something useful instead of this. Like
intgrating Bullet3 with Urho.
This is what I plan to do later this year, but in case you have so much
time like baseless critiquing what I do,
you could just do that. As for updates, This one is for bugfixes. No
offence, but I'm really tired of the toxity
these days, and I'm no longer going to tolerate baseless attacks. This is
my hobby, not work; Wars are no fun to me.

**Comment by Lumak** [comment]
I'm sorry if your feelings are hurt and for you to take what I pointed out as "baseless" and "toxic" attack.  I'm merely comparing what's in Bullet's official 2.86.1 release to your PR.

**Comment by slapin** [comment]
You'd better read Bullet update history in Urho, that would answer all your concerns.

**Comment by cadaver** [comment]
Before Urho actually uses InverseDynamics related functionality, having the extra files there just increases compilation time. Furthermore they would be stripped away in a shared library build so would likely not be usable in the user's application. This PR is fine for updating Bullet as is.

**Comment by slapin** [comment]
Please don't remove softbodies. They are too good to be not be supported, also they have much less
obstacles than InverseDynamics to have them supported. I always wanted to spend some time making them work...

**Comment by eugeneko** [comment]
> In fact we also have BulletSoftBody there strictly speaking "unnecessarily."

IMO we shall improve Urho or wait for PRs instead of stripping pretty powerful physical engine just to improve (first) compilation time. It would be much easier for users to extend the engine if they have unrestricted version of 3rdparty.

**Comment by Lumak** [comment]
I'm in agreement w/ eugeneko.

**Comment by slapin** [comment]
I wonder where you all have been before?

I think one interested could send PR with full bullet integration,
including Bullet3 API.
That would be big news.
Anyone who wants missing bullet features could work on integrating these
features.
I don't think it is usable to just drop whole bullet into Urho and fight
integration issues all for nothing.
Just having files lying there doesn't change anything.

**Comment by slapin** [comment]
Anyway, this all have nothing to do with this PR. Full bullet is a long term thing, one should open new PR/issue with it. This one is short-term thing fixing my selfish local issues nobody else have,
like #1933 and others.

**Comment by cadaver** [comment]
This update loses some of the Urho3D-related customizations. If you check the diff, you see several of Urho3D-related comments and their accompanying changes missing. For example one of the most extensive ones is optimizing physics debug draw to do an AABB-based cull first.

Can you bring those changes back?

**Comment by slapin** [comment]
Would you be so kind pointing-out some commit IDs? I did a job digging all changes, so I wonder how could I miss some.

**Comment by cadaver** [comment]
I'd have to dig those out, some have been done long ago, so that'd be some work. Typically after updating a library, I'd go manually through the changed files to see where the // Urho3D marked changes are lost, and bring the back manually by e.g. WinMerge.

It's also fine that we discard this PR and I redo the Bullet update when I have time, that can be easier.

**Comment by slapin** [comment]
Well, as this is half-done, I think joint-effort might be a bit better.
If all were commented then I could look at missing comments next few weeks. I checked all commits since previous Bullet update and rebased them, so the only ones which I could miss are somehow added
together with Bullet code not as separate commits. I think it would be better to add them as separate commits later so that re-adding them would be easier. I think I will take original 2.84 and check what is different in that patch in Urho, so I will separate local changes and re-add them.

**Comment by cadaver** [comment]
@weitjong has indeed been converting third-party libraries (most notably SDL) into subtrees so that the upstream changes and our mods can be reconciled in orderly fashion. Unfortunately Bullet has been worked on in "cowboy style" instead so far. I already started going through the 2.86.1 changes and I suppose I get done it rather fast (possibly even today) so you don't necessarily have to do anything.

**Comment by cadaver** [comment]
Done, shall push a feature branch soon. Thanks for your initial work, sorry it went a bit messily.

**Comment by cadaver** [comment]
Merged the independent 2.86.1 update work to master. Thanks one more time for the inspiration!

**Comment by Lumak** [comment]
Got the latest from the head and built it, but there are slew of this warning for every cpp file that's compiled in Urho3D and its samples:
\include\Urho3D\ThirdParty\Bullet/LinearMath/btIDebugDraw.h(173): warning C4305: 'argument': truncation from 'double' to 'const btScalar'

Anyway to clean up or suppress this warning?

**Comment by iSLC** [comment]
It's an old issue that was brought back by the update:

https://github.com/urho3d/Urho3D/issues/1637
https://github.com/bulletphysics/bullet3/pull/1191

**Comment by slapin** [comment]
Can't reproduce here.
Platform: Linux
Compiler:  gcc-5.3

**Comment by Lumak** [comment]
Thanks iSLC. So it might be a while before we get the update in Urho3D. I'm going to make the change locally for now, as I like to see if warnings are actually potential bugs in my builds.

**Pull request closed without merging**
