### PR TITLE
replaced Jack with Jill in 06_SkeletalAnimation sample

### PR DESCRIPTION
**Pull request by Lumak**

### CODE REVIEW

**Comment by Lumak** [comment]
screenshot_wed_dec_28_11_15_31_2016

**Comment by 1vanK** [comment]
I think need add "anisotropic" for ground like
https://github.com/1vanK/Urho3DHabrahabr06/blob/master/MyData/Textures/Ground.xml

**Comment by Lumak** [comment]
I like the submission like it is.

**Comment by cadaver** [comment]
Would you mind if I'd merge this without the plane material? Using the existing stone floor seems to me to make the "black spot" problem less severe.

**Comment by Lumak** [comment]
Nope, don't care as long as I don't have to come up with another texture that may or may not work.

**Comment by cadaver** [comment]
Merged, thanks!

**Comment by 1vanK** [comment]
Is some problem



Also I suggest to change zone and sun colors:
```
zone.ambientColor = Color(0.4f, 0.4f, 0.4f);
light.color = Color(0.6f, 0.6f, 0.6f);
```

**Comment by 1vanK** [comment]
Ok, if you do not mind, I would also like to make model more large

**Comment by cadaver** [comment]
By scaling? Fine by me.

**Comment by 1vanK** [comment]
What about this wariant? (scale = 2)

**Comment by 1vanK** [comment]
just seemed, that new model is much less than jack

**Comment by Lumak** [comment]
Asian girls are "smaller" :smile:

**Comment by cadaver** [comment]
Looks OK. I think it's enough if each sample makes sense in isolation. Though viewed as static models in editor Kachujin appears a bit larger than Jack. Jack should be about 2 world units high.

**Comment by 1vanK** [comment]
Ah, It is an optical illusion :) Jack walks, but gilr crouched  :)

**Pull request closed without merging**
