### PR TITLE
LineEdit: hide cursor when not editable

### PR DESCRIPTION
**Pull request by moneromooo**

### CODE REVIEW

**Comment by eugeneko** [comment]
Explain this change. Why hide cursor for non-editable text element?
User still may want to copy contents.

**Comment by moneromooo** [comment]
Because a cursor means input, no ? The patch changes the display only, it does not disable copying.

**Review by UkoeHB — APPROVED** [review]

**Comment by UkoeHB** [comment]
The cursor still 'exists', it just never gets shown. If it didn't exist between blinks the code would be super broken.

**Comment by eugeneko** [comment]
> Because a cursor means input, no ?

Nope. The cursor means current position for interaction, including selection and copying.
Editability is irrelevant.
image

**Comment by moneromooo** [comment]
That's hardly good evidence, but hey, it's your software, so you decide.

**Comment by eugeneko** [comment]
> That's hardly good evidence

I don't know if it's better to have cursor or not to have.
However, there should be a good reason (e.g. bug in code) to change _any_ kind of existing functionality.
And this specific case is not a bug.

**Comment by moneromooo** [comment]
Fair. I guess it's subjective, and maybe down to whatever software one is used to,

**Pull request closed without merging**
