### PR TITLE
Implement UI/ProgressBar

### PR DESCRIPTION
**Pull request by nerzhul**
Urho have scrollbars, sliders, but not ProgressBar for doing some loading screens, for example.
We have this progressbar working on our project and wanting it to be upstream, then enjoy

### CODE REVIEW

**Comment by eugeneko** [comment]
Maybe you need to fix codestyle first?
E.g. member names and convert tabs to spaces
http://urho3d.github.io/documentation/1.5/_coding_conventions.html.

**Comment by nerzhul** [comment]
@eugeneko hmmm sorry i forget to see tabs should be spaces.
For members i looked at the slider code

**Comment by nerzhul** [comment]
@eugeneko this is now fixed :)

**Comment by cadaver** [comment]
Check http://urho3d.github.io/documentation/HEAD/_contribution_checklist.html. The brace placement is not the same as in existing code, and script bindings are missing. Otherwise looking good. However I'm a bit unsure if this is needed, since you could always implement a bar (with a style of your own choosing) with a BorderImage or two. Opinions?

**Comment by nerzhul** [comment]
@cadaver i will fix the braces soon.
For the ProgressBar the idea is to have this component directly into core. Many users can have this need if we have a component to do this core side it permit everybody to don't reinvent the wheel :)
ProgressBar has the same goal as Slider, simplify the library end user coding :)
This permits to have a common interface for every body to do this work

**Comment by nerzhul** [comment]
@cadaver indent is now fixed. For bidings you mean angelscript & lua ?

**Comment by cadaver** [comment]
Yes.

**Comment by Scellow** [comment]
I think slider is already a progress bar, since it just need a fill between begin and the handle
http://media02.hongkiat.com/jquery-ui-slider/anatomy.jpg
But having a specific control is i think a good idea, slider is for changing value, progress bar is for displaying a progress

**Comment by cadaver** [comment]
Merged the version with added bindings.

**Pull request closed without merging**
