### PR TITLE
Add a 'Typography' sample program

### PR DESCRIPTION
**Pull request by iainmerrick**
Displays text in various sizes, with checkboxes to play with settings that affect the way text is rendered:
- Color (white-on-black versus black-on-white)
- Autohinter
- SRGB output conversion (not available on all platforms)

### CODE REVIEW

**Comment by iainmerrick** [comment]
Not sure if this is the correct style for sample programs (for example, do I need to add a Lua version?)

**Comment by cadaver** [comment]
Thanks! It was not stated in the contribution checklist (added just now), but yes, the idea would be to implement the sample in C++ and both scripting languages. 

In this case the pedagogic need isn't that great, since creating text elements in all APIs has already been demonstrated in earlier samples, and checking the text rendering quality & correctness with different options is the most important point of this sample. But to keep consistency, it would still be good to have the script versions too.

**Comment by iainmerrick** [comment]
Fixed Travis build errors and added Lua and AngelScript versions. Ready for another look now.

**Comment by cadaver** [comment]
Thanks, will see when have time, shouldn't take long.

**Pull request merged**
