### PR TITLE
JS: Add IES cookie generation to RampGenerator

### PR DESCRIPTION
**Pull request by JSandusky**
Adds Gobo/Cookie baking from IES files to RampGenerator.

Part of a series of PRs I'll submit for old functionality I'd like to see merged in.

**Note:** I couldn't figure out how to filter these based purely on the data, the blur could be removed if someone else can sort out this lat/lon ray thing better, I never found a method that dealt with it robustly enough (bollard lights break everything). Blurring is generally sufficient.

I'll be opening a series of issues, they won't be actual issues but more matters of serious discussion regarding merging such as OpenCL, Texture cube arrays, geom/hull/dom shaders, etc.

### CODE REVIEW

**Comment by eugeneko** [comment]
_offtop_ I suggest you to PR other issues. It'd be easier to understand and discuss about.

**Comment by cadaver** [comment]
Very minor code convention issue: sigma3Kernel9x9 (start with lowercase) would be preferable.

**Comment by JSandusky** [comment]
@eugeneko negative, only a few of these are small enough to occur without discussion.

@cadaver is the correction sufficient, would it be preferable to base off of *Image* and include the convolution filter routines (arbitrary gauss calc. is part of that) with this?

**Comment by cadaver** [comment]
No need, this can be taken in now as-is. 

Is it OK to include your name in the contributor list again?

**Comment by JSandusky** [comment]
@cadaver, it's fine with me.

**Comment by cadaver** [comment]
Merged.

**Comment by JSandusky** [comment]
Okay, so the AppVeyor thing was just a build system choke or something of the sort then?

**Comment by cadaver** [comment]
AppVeyor builds are being worked on. I saw the errors had nothing to do with your code so I went ahead.

**Pull request merged**
