### PR TITLE
DotNet bindings

### PR DESCRIPTION
**Pull request by 1vanK**
Just test compiling.

I test another way for combine C++ refCounted and C# garbage collector than UrhoSharp. Also I try to maximize match bindings to original classes. Minamal test app: https://github.com/1vanK/Urho3D_DotNetBindings
(just shows empty Urho3D window and writes message to log)

### CODE REVIEW

**Comment by eugeneko** [comment]
Why not to just turn CI on for your fork?
FYI. To make .NET callbacks without touching it's enough to make this on C++ side

```
class Urho_Application_wrapper : public Application
{
public:
    using Callback = void(__stdcall *)(Application* self);
    Callback onSetup_ = 0;
    Callback onStart_ = 0;
    Callback onStop_ = 0;

    using Application::Application;
    virtual void Setup() { onSetup_(this); }
    virtual void Start() { onStart_(this); }
    virtual void Stop() { onStop_(this); }
};

extern "C"
{

URHO3D_EXPORT_API void ub_Urho_Application_Setup_set(Urho_Application_wrapper* self, Urho_Application_wrapper::Callback callback)
{
    self->onSetup_ = callback;
}

URHO3D_EXPORT_API void ub_Urho_Application_Start_set(Urho_Application_wrapper* self, Urho_Application_wrapper::Callback callback)
{
    self->onStart_ = callback;
}

URHO3D_EXPORT_API void ub_Urho_Application_Stop_set(Urho_Application_wrapper* self, Urho_Application_wrapper::Callback callback)
{
    self->onStop_ = callback;
}

}
```

And this on C# side
```
public partial class Application : UrhoObject
{
    public Application(Context context) : base(ub_Urho_Application_Constructor(context.Handle))
    {
        ub_Urho_Application_Setup_set(Handle, (self) => Runtime.LookupObject<Application>(self)?.Setup());
        ub_Urho_Application_Start_set(Handle, (self) => ((Application)GCHandle.FromIntPtr(self).Target).Start());
        ub_Urho_Application_Stop_set(Handle, (self) => ((Application)GCHandle.FromIntPtr(self).Target).Stop());
    }

    public virtual void Setup() { }
    public virtual void Start() { }
    public virtual void Stop() { }

    [UnmanagedFunctionPointer(CallingConvention.StdCall)]
    delegate void SetupCallback(IntPtr self);

    [UnmanagedFunctionPointer(CallingConvention.StdCall)]
    delegate void StartCallback(IntPtr self);

    [UnmanagedFunctionPointer(CallingConvention.StdCall)]
    delegate void StopCallback(IntPtr self);

    [DllImport(Consts.NativeImport, CallingConvention = CallingConvention.Cdecl)]
    extern static IntPtr ub_Urho_Application_Setup_set(IntPtr self, [MarshalAs(UnmanagedType.FunctionPtr)]SetupCallback callback);

    [DllImport(Consts.NativeImport, CallingConvention = CallingConvention.Cdecl)]
    extern static IntPtr ub_Urho_Application_Start_set(IntPtr self, [MarshalAs(UnmanagedType.FunctionPtr)]StartCallback callback);

    [DllImport(Consts.NativeImport, CallingConvention = CallingConvention.Cdecl)]
    extern static IntPtr ub_Urho_Application_Stop_set(IntPtr self, [MarshalAs(UnmanagedType.FunctionPtr)]StopCallback callback);
}
```

**Comment by 1vanK** [comment]
Thanks it is good idea!

**Comment by 1vanK** [comment]
How to clear spam after pull from official repo to fork?

**Comment by 1vanK** [comment]
Ok I found way:
```
git pull https://github.com/urho3d/Urho3D.git master --rebase
git push origin master --force
````

**Comment by rokups** [comment]
@1vanK are these bindings going to be auto-generated?

**Comment by 1vanK** [comment]
no

**Comment by 1vanK** [comment]
I try to export Variant to C# but not fully understand how it stored in memory:

```
    Variant testValue = 17;

    unsigned char bytes[sizeof(testValue)];
    memcpy(bytes, &testValue, 4 + VARIANT_VALUE_SIZE);
    for (int i = 0; i < 4 + VARIANT_VALUE_SIZE; i++)
        printf("%i = %i\n", i, bytes[i]);
```

```
0 = 1 // First 4 bytes is VariantType (1 = Int it is OK)
1 = 0
2 = 0
3 = 0 
4 = 204 // Another 16 bytes is VariantValue on x32 platform
5 = 204 // Some uncleared memory?
6 = 204
7 = 204
8 = 17 // Why Int not from the beginning of VariantValue union?
9 = 0
10 = 0
11 = 0
12 = 204
13 = 204
14 = 204
15 = 204
16 = 204
17 = 204
18 = 204
19 = 204
```

**Comment by rokups** [comment]
Variant uses union for storing different types to the same memory address. So depending on variant type same memory will contain objects of different types. Just treat address of value as type set to variant.

**Comment by 1vanK** [comment]
@rokups I edited message

> Variant uses union for storing different types to the same memory address.
I know. Why Int stored not from first byte?

Also why VariantValue > 16 bytes?

**Comment by 1vanK** [comment]
Looks like some alignment, how to deal with this?

My C# equivalent
```
StructLayout(LayoutKind.Sequential)]
public struct VariantStorage
{
    public UIntPtr Storage0;
    public UIntPtr Storage1;
    public UIntPtr Storage2;
    public UIntPtr Storage3;
}

[StructLayout(LayoutKind.Explicit)]
public struct VariantValue
{
    [FieldOffset(0)]
    public VariantStorage Storage;

    [FieldOffset(0)]
    public int Int;

    [FieldOffset(0)]
    public bool Bool;
}

public enum VariantType
{
    None = 0,
    Int,
    Bool,
    Float,
    Vector2,
    Vector3,
    Vector4,
    Quaternion,
    Color,
    String,
    Buffer,
    VoidPtr,
    ResourceRef,
    ResourceRefList,
    VariantVector,
    VariantMap,
    IntRect,
    IntVector2,
    Ptr,
    Matrix3,
    Matrix3x4,
    Matrix4,
    Double,
    StringVector,
    Rect,
    IntVector3,
    Int64,
    CustomHeap,
    CustomStack,
    MaxVarTypes
}

[StructLayout(LayoutKind.Sequential)]
public struct Variant
{
    public VariantType Type;
    public VariantValue Value;
    
    public Variant(int value)
    {
        Type = VariantType.Int;
        Value = new VariantValue();
        Value.Int = value;
    }

    public Variant(bool value)
    {
        Type = VariantType.Bool;
        Value = new VariantValue();
        Value.Bool = value;
    }
}
```

**Comment by eugeneko** [comment]
> Looks like some alignment, how to deal with this?

It's guaranteed that all Variant members are aligned to the beginning of VariantValue.
You shan't rely on anything else.

**Comment by 1vanK** [comment]
Manual hack helped me:
```
[StructLayout(LayoutKind.Explicit)]
public struct Variant
{
    [FieldOffset(0)]
    public VariantType Type;
    
    [FieldOffset(8)]
    public VariantValue Value;
   
    public Variant(int value)
    {
        Type = VariantType.Int;
        Value = new VariantValue();
        Value.Int = value;
    }

    public Variant(bool value)
    {
        Type = VariantType.Bool;
        Value = new VariantValue();
        Value.Bool = value;
    }
}
```
but I'm not sure about cross platform

================================

Another problem:

When I send this struct to c++
```
[StructLayout(LayoutKind.Explicit)]
public struct VariantValue
{
    [FieldOffset(0)]
    public VariantStorage Storage;

    [FieldOffset(0)]
    public int Int;

    [FieldOffset(0)]
    public bool Bool;
}
```
value always = 1,

but when
```
[StructLayout(LayoutKind.Explicit)]
public struct VariantValue
{
    [FieldOffset(0)]
    public int Int;

    [FieldOffset(0)]
    public bool Bool;

    [FieldOffset(0)]
    public VariantStorage Storage; // Shoul be last???????
}
```

all works

**Comment by 1vanK** [comment]
Is any ideas why

```
// Works
URHO3D_API void VariantMap_GetValue(VariantMap& nativeInstance, StringHash key, Variant& value)
{
    value = nativeInstance[key];
}

// Not works (return trash in value)
URHO3D_API void VariantMap_GetValue(const VariantMap& nativeInstance, StringHash key, Variant& value)
{
    value = nativeInstance[key];
}
```
C#
```
    [DllImport(Consts.NativeLibName, CallingConvention = CallingConvention.Cdecl)] 
    private static extern void VariantMap_GetValue(IntPtr nativeInstance, StringHash key, out Variant value);
```

**Comment by KonstantinTomashevich** [comment]
As I know, const version of operator [] returns pointer to value (or nullptr).

**Comment by 1vanK** [comment]
After some time of work app crash with System.AccessViolationException. I call GC.Collect() manually in HandleUpdate() and get exception immediately. In google I found explanation: C# optimizer can destroy objects with unmanaged function calls thinking it unused. But recommended recipes (GC.KeepAlive, MethodImplOptions.NoOptimization) works only in some cases.

**Comment by 1vanK** [comment]
Sample https://github.com/1vanK/Urho3D_DotNetBindings/blob/master/Samples/Sample.cs
now show sprite and debug hud.

**Comment by eugeneko** [comment]
C++-to-C# transitions are quite debuggable via Visual Studio. Just F11 into your call and get know.

**Comment by eugeneko** [comment]
I tried to make some bindings on my own and all important C++ and C# code was in single solution. Breakpoints were hit, debugging was fine.

**Comment by 1vanK** [comment]
Question to C++ 11 experts

https://github.com/1vanK/Urho3D/blob/f1b0f8f926068175f0d53cfbb8fa77c6c75aa465/Source/Urho3D/DotNet/Core/Object.cpp#L32

I change
```
URHO3D_API void Object_SubscribeToEvent(Object* nativeInstance, StringHash eventType, void_function_VariantMap function)
```
to
```
URHO3D_API void Object_SubscribeToEvent(Object* nativeInstance, StringHash eventType, void_function_VariantMap* function)
```
and program still works normal.

Same when I change
```
EventHandlerImplDotNet(void_function_VariantMap* function) : EventHandler(nullptr, nullptr)
```
to
```
EventHandlerImplDotNet(void_function_VariantMap function) : EventHandler(nullptr, nullptr)
```
Compiler even does not cause any warnings...

Why "type" is equialent "type*"?

**Comment by eugeneko** [comment]
Your function pointer is not event a pointer, I don't see any stars in `using`
Don't know why it is valid, but you probably should avoid such tricks. Function pointers are quite weird.

**Comment by 1vanK** [comment]
http://www.lysator.liu.se/c/rat/c3.html#3-3-2-2

any form convert to function pointer when function_ = function (function_ is pointer)

**Comment by 1vanK** [comment]
https://github.com/1vanK/Urho3D_DotNetBindings/blob/master/Samples/04_StaticScene/StaticScene.cs

C# slightly slower than AS :(
It seems PInvoke is too heavy operation

**Comment by 1vanK** [comment]
I was hoping that C# would give performance advantages over AngelScript, but they are not so insignificant but add dependency from large .Net environment. So I'm not interested in continuing development of bindings.

**Comment by 1vanK** [comment]
Moved to https://github.com/Dviglo/Dviglo/tree/CSharp if someone interesting with it

**Pull request closed without merging**
