### PR TITLE
Refactor Vector and PODVector implementation.

### PR DESCRIPTION
**Pull request by eugeneko**
Related to #1556.
I re-organized vector code to prevent old buffer destruction in case of reallocation until new buffer is constructed. I also removed this hacky macro and added one new ctor for both vectors.
**Upd:** I smoke-tested Editor and all demos.

### CODE REVIEW

**Comment by cadaver** [comment]
Appreciated very much! The code became much less repeated, too.
I believe List-like containers also have a potential problem with the next/prev links when self-inserting, but I can look into that separately.

**Comment by eugeneko** [comment]
What kind of problems do you expect from List?
As far as I see, List always copies passed element and then initializes its links.

**Comment by cadaver** [comment]
Yes, I meant range self-insertion, which currently works one-by-one. I think it could be made workable by first constructing copies of all the elements in the range, and simply chaining them to each other, then fixing the links into the rest of the list as the final step.

**Comment by 1vanK** [comment]
I am sorry for offtopic, why not use std containers?

**Comment by cadaver** [comment]
It's explained in the documentation, there are a few reasons, such as guaranteed binary size for constructing inside a Variant.

**Comment by 1vanK** [comment]
Thanks  for the clarification, I found docs article

**Comment by cadaver** [comment]
Briefly tested self-range insertion with List and didn't see problems, at least in a simple case. Added just a self-assignment check to containers to prevent mistaken clearing.

**Comment by eugeneko** [comment]
PS: I notced that I've written an assert in Vector::InsertElements but not in PODVector::InsertElements. Please add this forgotten assert when you commit something next time.

**Pull request merged**
