### PR TITLE
Added light temperature

### PR DESCRIPTION
**Pull request by dragonCASTjosh**
screenshot_tue_aug__9_18_14_10_2016

The image should explain things well enough, if not then i have added physically based light temperature to lights, it changes the hue based on the kelvin scale.

Reference scale:
http://www.jozifolk.com/resources/kelvin-chart.jpg

### CODE REVIEW

**Comment by dragonCASTjosh** [comment]
no idea how to handle lua

**Comment by cadaver** [comment]
Does this do anything else than modulate the light RGB color with the temperature formula? In that case it seems unnecessary to repeat the calculation per pixel in the shader.

I'd rather recommend something like this:
- Add bool attribute "Use Temperature" to Light, can default to false to not cause unintended effects. When enabled, the temperature modulation is calculated on the CPU in Light's GetEffectiveColor() function.
- No shader changes should be necessary if I understand right.

**Comment by dragonCASTjosh** [comment]
The default value should be white light although I was considering adding a bool. I also tried moving the calculation to light.cpp and apply it at the same place as brightness although Color * Color caused some issues I don't have time to look at this week.

**Comment by dragonCASTjosh** [comment]
@cadaver committed a version with no shader changes, and made temperature values optional

**Comment by cadaver** [comment]
Thanks, implementation looks good now. However there's tabs being used in Light.h / Light.cpp (please use spaces) and you should revert the shader changes completely, if you check the changed files list there's still shader changes.

**Comment by dragonCASTjosh** [comment]
i changed visual studio to use spaces under c++ so im not sure whats up there

**Comment by cadaver** [comment]
Use Edit -> Advanced -> View White Space in VS to be sure. Maybe you touched the files with another editor that uses tabs?

**Comment by dragonCASTjosh** [comment]
@cadaver fixed spacing and removed shaders should all be good now

**Comment by cadaver** [comment]
Thanks. I'll check it and add Lua bindings, likely today.

**Comment by dragonCASTjosh** [comment]
thanks, and where would i look for doing lua bindings for future reference

**Comment by cadaver** [comment]
Look at the .pkg files in Source/Urho3D/LuaScript/pkgs . In easy cases this means just copy-pasting the new function declarations from header files. Note that we may change Lua binding system, but that's still upcoming until the build problems are resolved for all supported platforms.

**Comment by dragonCASTjosh** [comment]
@cadaver im am also working on implementing lumans for optional physical based light brightness, if you want to hold of on the merge i can push it here and change the use temperature option to use physical values and add lua

**Comment by cadaver** [comment]
That's fine, I'm in no hurry to merge.

**Comment by dragonCASTjosh** [comment]
light color is in kelvin and is now multiplied with with the standard color to allow for artist tweeking. 
light brightness is in lumens power

all physical values are only used if the use physical value check box is used.

**Comment by cadaver** [comment]
Merged.

**Pull request closed without merging**
