### PR TITLE
Compact viewport mode

### PR DESCRIPTION
**Pull request by Liichi**

### CODE REVIEW

**Comment by eugeneko** [comment]
Sooo... what's it?

**Comment by Liichi** [comment]
It is a layout that puts the viewport area in the center of the screen (not fullscreen), the hierarchy window on the left and the attribute inspector window on the right.
This layout also deactivates the ability to move or scale the hierarchy window and the attribute inspector.
PS: sorry for my english.

preview

**Comment by cadaver** [comment]
Looks useful. However, can you edit the code to match the engine code convention (e.g. braces)? The idea is to use the same convention in both C++ code and scripts.

**Comment by Liichi** [comment]
Yes, of course, i will also comment on the code.

**Comment by Liichi** [comment]
I have a problem with the grid. I do not know if it's a problem with my code or an editor issue.
grid

**Comment by Liichi** [comment]
I think everything is ready.
Preview:
preview2

**Comment by eugeneko** [comment]
Let's squash commits when you finish. Dozen of non-functional commits like codestyle fixup IMO decrease readability of repo tree.

**Comment by Liichi** [comment]
It's ready.

**Comment by weitjong** [comment]
Just want to chip in on Eugene's point. I understand this could be a personal habit to commit as frequent as possible. However, one don't have to push to remote repository on each commit, especially when a PR has been submitted to upstream. Each push would not only send a notification to all of repo watchers' email accounts, but also trigger a CI build unnecessarily. It increases our carbon footprint :)

**Comment by Liichi** [comment]
I agree, I had not thought of that :( . So should I edit the files locally?
PS: sorry for email and CI flood. C:

**Comment by 1vanK** [comment]
How to squash https://github.com/urho3d/Urho3D/pull/1733#issuecomment-269802300

**Comment by cadaver** [comment]
I would have one suggestion, when switching from Compact mode back to the others, could you reset inspector & attribute editor window sizes to the defaults (same which is done on editor startup)? It's a bit of a pain to resize them manually after they've been expanded to the window edges.

**Comment by cadaver** [comment]
Thanks, will test again!

**Comment by cadaver** [comment]
Merged as squashed.

**Pull request closed without merging**
