### PR TITLE
Expanded DDS support

### PR DESCRIPTION
**Pull request by JSandusky**
- DX10 format support (only data formats compatible, DXT-1/3/5 and RGBA + sRGB variation)
- sRGB flag on Images if indicated by DDS DXGI format
- Images may be "chained" as a list off of the first image (DDS
cubemaps, texture arrays)
- Direct3D9 cubemap loading from DDS standard cubemap

### CODE REVIEW

**Comment by OldSnake22** [comment]
Thanks a lot for this

**Comment by cadaver** [comment]
Can you make the same changes to D3D11 and OpenGL?

**Comment by JSandusky** [comment]
Certainly.

Will commit once I've finished testing all the scripting bindings and GL/DX11.

**Comment by JSandusky** [comment]
I'm unable to test OpenGL and Lua.

**Pull request merged**
