### PR TITLE
Updated the ProgressBar PR to include Lua and AngelScript bindings

### PR DESCRIPTION
**Pull request by victorholt**
I've created a new PR for the progress bar from the following PR: https://github.com/urho3d/Urho3D/pull/1419

I've also added the ability to turn on/off the percent text. This is my first time updating the Urho UI, so please let me know if I've missed anything.

Original credit goes to @nerzhul

untitled-1

### CODE REVIEW

**Comment by nerzhul** [comment]
Thanks !

**Comment by cadaver** [comment]
Nice work, looks very much mergable now.

**Comment by victorholt** [comment]
Awesome! This really helped me gain an understanding of what's needed when building UI elements. Thanks to you as well @nerzhul for your original work. I'm using this feature already in my game :)

**Comment by nerzhul** [comment]
No problem @victorholt i forgot this commit which was working but partial it's great you like it :)

Thanks @cadaver for review

**Comment by nerzhul** [comment]
Thanks

**Pull request merged**
