### PR TITLE
SDL 2.0.12

### PR DESCRIPTION
**Pull request by gleblebedev**
An attempt to update SDL to 2.0.12.

### CODE REVIEW

**Comment by gleblebedev** [comment]
@weitjong I think it's ready for review.

**Comment by gleblebedev** [comment]
@weitjong I see new CI already in place. Nice, let's see if I've missed anything this time.

**Comment by weitjong** [comment]
Yes, but there is still teething problem on macOS runner. GitHub has upgraded the macOS runner VM on the day we made the cut over and somehow it breaks a few build jobs as the result. Until the dust is settled down, just ignore the build failure from the macOS runner.

**Comment by weitjong** [comment]
Bummer. It is not just the VM upgrade, it is in fact Xcode version upgrade.

```
4,5c4,5
< -- The C compiler identification is AppleClang 12.0.0.12000032
< -- The CXX compiler identification is AppleClang 12.0.0.12000032
---
> -- The C compiler identification is AppleClang 11.0.3.11030032
> -- The CXX compiler identification is AppleClang 11.0.3.11030032
361c361
< --  EXTRA_LIBS:    m;iconv;/Applications/Xcode_12.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreVideo.framework;/Applications/Xcode_12.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Cocoa.framework;/Applications/Xcode_12.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/IOKit.framework;/Applications/Xcode_12.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/ForceFeedback.framework;/Applications/Xcode_12.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Carbon.framework;/Applications/Xcode_12.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreAudio.framework;/Applications/Xcode_12.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AudioToolbox.framework
---
> --  EXTRA_LIBS:    m;iconv;/Applications/Xcode_11.7.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreVideo.framework;/Applications/Xcode_11.7.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Cocoa.framework;/Applications/Xcode_11.7.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/IOKit.framework;/Applications/Xcode_11.7.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/ForceFeedback.framework;/Applications/Xcode_11.7.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Carbon.framework;/Applications/Xcode_11.7.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreAudio.framework;/Applications/Xcode_11.7.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AudioToolbox.framework
```

I don't have Mac to test locally at the moment. I will see whether I can fix this by guessing from the CI build log.

**Comment by gleblebedev** [comment]
@weitjong I have Mac, I can try to fix it.

This is the failing command, am I right?
xcodebuild -project Urho3D.xcodeproj build -target install -configuration Release -hideShellScriptEnvironment

**Comment by weitjong** [comment]
There are two separate issues. One for iOS/tvOS build and one for macOS build with Makefile (instead of xcode project). I suspect the former issue is caused by the so-called "universal binary build" support. Last time I managed to pull this off when I still a working Mac Mini to test. Basically it attempts to combine iphoneOS + iphoneSimulator into one by using the "lipo" tool. Something might have changed in the latest Xcode 12 that breaks the whole thing. This is just my guest only though.

The former issue is somewhat a known issue for zlib. But somehow in the past our auto-detect is able to set thing up correctly for the Makefile to work. Apple is attempting to remove legacy build support. They have already made their header files not easily accessible from outside Xcode. I was just lucky to find a workaround to get those headers back in the runner. However, it seems something has changed in the header which causing this known zlib issue to surface again. I am this close to just remove the Makefile support all together. So, this last issue is not the priority. The former issue is more important. If we cannot test install the library then it means we cannot test the rest of the scaffolding steps too.

**Comment by weitjong** [comment]
Forgot to mention one more thing. Base on the build log, I suspect the lipo tool complained about combining the lib for a same arch twice. i.e. for some reason instead of iphoneOS + iphoneSimulator, it is trying to do iphoneOS + iphoneOS again. I could be wrong though.

**Comment by weitjong** [comment]
I think I know why already. The root cause of the issue is Xcode 12 now also builds "arm64" arch for "iphoneSimulator" sdk instead of just "x86_64" arch like in the prior version. I guess Apple is trying to get Apple Silicon ready for big time, including the ability to simulate arm64 iOS on the new chip. I see whether I can fix this issue today before taking a break.

For you, I suggest you concentrate on the SDL 2.0.12 upgrade. Getting all the checks on CI/CD is one thing, but making sure there is indeed no regression is another, especially for those platforms that we cannot actually CI test run the result like Android and Web. I have a reason to believe your PR will cause issue on the Android/Shared build config because you have reverted a few of my local modifications. Having said that, I am happy to be proof wrong.

**Pull request closed without merging**
