### PR TITLE
Platform-specific system query functions

### PR DESCRIPTION
**Pull request by Florastamine**
Continuation of PR #1931 

Looks good on my machine. Only supports Windows and Linux platform at the moment. The Windows API used requires Windows 2000 Pro/XP or higher.

### CODE REVIEW

**Comment by Florastamine** [comment]
It builds and runs fine on my local machine, as well as on Travis g++. Don't know why Travis MinGW rejected it. :(

**Comment by cadaver** [comment]
You could try downgrading to the exact same compiler version as used by CI. If it barfs on the typedef specifically, could you write the function pointer the hard way into the function, instead of using a typedef at all?

**Comment by Florastamine** [comment]
Ok. I have pushed out a patch which fixed the `NTSTATUS` typedef issue. I took a quick look at the CI MinGW headers (`x86_64-w64-mingw32-gcc-4.6.3-2`, same version) and found out that they also defined it. So it wasn't about `NTSTATUS` being left out in earlier MinGW releases but I suspect that they changed the definition/location of `NTSTATUS` (it's in `<ntdef.h>`, but my MinGW 6.3.0 and 5.3.0 went fine without including that header, whereas the CI version which is 4.6.3 fails if the header wasn't explicitly included).

**Comment by cadaver** [comment]
Good! Could push this then into a feature branch for full CI tests.

**Comment by Florastamine** [comment]
So... is there anything left I should do?

**Comment by cadaver** [comment]
The branch is pushed now, we'll see how it compiles in the full CI battery.

**Comment by cadaver** [comment]
You can look at the branch build status at https://travis-ci.org/urho3d/Urho3D/branches . OSX failed due to missing include. Android failed too apparently, but I didn't look in detail.

**Comment by Florastamine** [comment]
Corrected. I forgot to exclude other platforms, so when building on OSX the Linux headers got accidentally included.

**Comment by cadaver** [comment]
Android fails due to HOST_NAME_MAX being undefined. I did a fast search through one version of NDK and didn't find it in any of the include files, which was surprising.

**Comment by Florastamine** [comment]
Strange. These functions are only meant to support Windows and Linux. So I isolated the appropriate headers (in `ProcessUtils.cpp`, at the beginning). But the headers weren't somehow isolated, which would cause `HOST_NAME_MAX` being "leaked out" in the Android build and thus caused the error. Same as with OSX, the missing header was intended for Linux. Would you mind checking the most recent commit (specifically the `#ifdef`-header include to see if there's anything I'm missing?

**Comment by Florastamine** [comment]
```
#if defined(_WIN32)
	#include <windows.h>
	#include <io.h>
	#if defined(_MSC_VER)
		#include <float.h>
		#include <Lmcons.h> // For UNLEN. 
	#elif defined(__MINGW32__)
		#include <lmcons.h> // For UNLEN. 
		#include <ntdef.h> 
	#else 
	#endif 
#elif defined(__linux__)
	#include <pwd.h> 
	#include <unistd.h>
	#include <sys/sysinfo.h>
	#include <sys/utsname.h>
	#include <limits.h> // For HOST_NAME_MAX. 
#else
#endif
```

This is what I've got in the lastest commit, don't know if there's something wrong. Linux headers are not supposed to "leak" into the OSX/Android build.

**Comment by cadaver** [comment]
Linux would also be defined on Android I believe.

**Comment by weitjong** [comment]
> Linux would also be defined on Android I believe.

I can definitely confirm that.

**Comment by Florastamine** [comment]
Thanks. The build should be smooth now.

**Comment by cadaver** [comment]
You also need to exclude the functionality, if it does not work without the includes.

**Comment by Florastamine** [comment]
Problem is I don't have the appropriate platforms for proper implementation (e.g. OS X). Might need some time for all the functions to have full support for whatever systems Urho can be compiled.

**Comment by cadaver** [comment]
Yes, in that sense Urho has a significant barrier to contribution, when it's not something that is e.g. covered by SDL for all platforms automatically. I'll see if I get inspired / if I have time / if it's easy to add OSX corresponding functionality, but no hard promises.

**Comment by cadaver** [comment]
Fixed enough of the OSX functions so that I'm satisfied. I didn't bother with the OS version for OSX at least for now. Pushed the changes to the feature branch and we'll see how the build of all platforms goes now.

**Comment by Florastamine** [comment]
Great, thanks! By the way, two things: 

I took a quick glance at your code and noticed you were using `getenv()`, which is quite unreliable. A user could alter the `USER` variable (for whatever purpose) during the current session and `GetLoginName()` would return the wrong result. 

```
NDMKs-Mac:Desktop ndmkhoi$ ./Urho3DPlayer PlatformAPI.lua
Logon:     ndmkhoi
Computer name:     NDMKs-Mac.local
NDMKs-Mac:Desktop ndmkhoi$ export USER="NewName"
NDMKs-Mac:Desktop ndmkhoi$ ./Urho3DPlayer PlatformAPI.lua
Logon:     NewName
Computer name:     NDMKs-Mac.local
NDMKs-Mac:Desktop ndmkhoi$ 
``` 

- I have access to a borrowed Mac now, which means that I'll be able to inspect and fill in the missing details for `GetOSVersion()` and also correct `GetLoginName()`.

**Comment by cadaver** [comment]
Ok, thanks. Please use the platform-query-functions branch as a base for further modifications.

**Comment by Florastamine** [comment]
Done. Please review. In `OSGetVersion()` I have added detection support for Mac OS X Lion (10.7) and higher, but older versions can be added with very minimal effort. 

Result from my device: 
```
Login name:     ndmkhoi
Computer name:     NDMKs-Mac.local
Total useable memory:     4096     (MiB)
OS version:     macOS/Mac OS X El Capitan 10.11.6  (Darwin kernel 15.6.0)
```

**Comment by cadaver** [comment]
You could use ToInt() from StringUtils.h instead of calling atoi() manually to be more "Urho-like". Will review in detail later, hopefully this day.

**Comment by cadaver** [comment]
Pushed into the Urho feature branch and fixed compile on iOS.

**Comment by cadaver** [comment]
CI is down for the moment, but did manual builds to verify, and should be OK now (had to just fix iOS to not attempt calling unsupported functions related to the login name.) Thanks for the work!

**Pull request merged**
