### PR TITLE
Hsv color wheel

### PR DESCRIPTION
**Pull request by MonkeyFirst**
This feature allow to change "basic colors" in fastest way for such components as: Light, Static mesh, Zone in view port on hotkey Alt+W

Please check out this, maybe it may to be merged.

### CODE REVIEW

**Comment by friesencr** [comment]
You have some merge conflicts.

**Comment by MonkeyFirst** [comment]
Yes I see that "This branch has conflicts that must be resolved"
But that this mean? who must solve this and how ? 
I may only to re-create my fork and add my code in new brunch and do new pull request.

**Comment by weitjong** [comment]
Since it is your code changes that conflict with other, logically it should be easier for you to resolve the conflict as you know where and what are those changes.

There is no need to re-fork, re-apply, and resend the PR, provided if you know how to do it properly. But I guess is whichever works best for you.

Hint: setup your local repository to have two remote: "origin" pointing to your fork and, say, "upstream" pointing to original Urho3D repo. This way, you can pull the latest from upstream and use it to rebase your branch locally before pushing back to your fork. I know it is confusing, at first :smile: .

**Comment by MonkeyFirst** [comment]
Oh wow, easier to me is recreate a fork :)
I'm playing before with upstream, but there is some kind errors with fetch or something else...

**Comment by 1vanK** [comment]
Sorry, I commented in the repository MonkeyFirst not think that comment gets here

**Comment by MonkeyFirst** [comment]
Я пересоздам форк, а там посмотрю что можно будет сделать.

**Pull request closed without merging**
