### PR TITLE
WebGL Module.arguments not work on Urho3DPlayer.

### PR DESCRIPTION
**Pull request by abdllhbyrktr**
Hi,

When I attempt to pass arguments to Urho3DPlayer web sample, It fires unexpected application failure. So I changed and tested the related source file. Now it works.

### CODE REVIEW

**Comment by cadaver** [comment]
Thanks for noticing the issue. It can perhaps be solved more elegantly by removing the earlier ifdef which prevents Web build from initially reading the arguments, and only making it so that Web build doesn't attempt to load CommandLine.txt from filesystem.

**Comment by cadaver** [comment]
Check if it works now in the master branch.

**Comment by abdllhbyrktr** [comment]
Yes it works, Thank you!

**Comment by cadaver** [comment]
Thanks for checking. Will close this now.

**Pull request closed without merging**
