### PR TITLE
Add tags to UIElement

### PR DESCRIPTION
**Pull request by 1vanK**
For now without bindings and attributes. Any notes?

### CODE REVIEW

**Comment by 1vanK** [comment]
It is possible to make acessor_atribute for Vector<String> ?

**Comment by cadaver** [comment]
This looks OK. Actually we could follow the same approach for the node tags; judging from this it would be OK to be a straightforward string-based multi-tag operation instead of being extremely optimized. The idea being that if you don't use tags, you don't pay cost for them (except for storage of the tags vector in each node, which is lightweight if empty)

Vector<String> is not directly convertible to a Variant. You can use dedicated functions for the attribute get/set access which aren't actually part of the API (see functions like SetMaterialsAttr, GetMaterialsAttr in StaticModel for example) and convert the string vector to a VariantVector.

Another possibility, which would be good for editing, would be to mark the attribute as a string and convert/deconvert it to a to a comma- or space-separated list in the accessors.

**Comment by 1vanK** [comment]
Squashed

**Comment by 1vanK** [comment]
In Editor the tags are separated by ';'

**Comment by cadaver** [comment]
Seems to work great also in practice. I'll rename IsTagged() to HasTag() to be more typical of the existing API convention.

**Comment by cadaver** [comment]
Merged.

**Comment by 1vanK** [comment]
> This looks OK. Actually we could follow the same approach for the node tags; judging from this it would be OK to be a straightforward string-based multi-tag operation instead of being extremely optimized. The idea being that if you don't use tags, you don't pay cost for them (except for storage of the tags vector, which is lightweight if empty)

Unlike a interface, scenes usually has many childred in root. So without hash table "tag -> nodes" it can be slowly (unlike GetChild(name) we need look ALL nodes, but not first founded). But with this hashtable it is necessary to look all children when node is parented / unparented (some cost even without tags). Also nodes has components and vars, so in my small practics i yet never needed tags in scene.

**Pull request closed without merging**
