### PR TITLE
Bullet RaycastVehicle support

### PR DESCRIPTION
**Pull request by slapin**
Hi!

This is initial release of RaycastVehicle component, which is wrapping of Bullet btRaycastVehicle.

Many features are missing, which will be added later.
The commit contains C++ code and AngelScript + Lua binding. But there is no Lua demo yet.
The component is not able to save/load yet (don't know how to do it).

The purpose of this PR is to recieve feedback and review. Please remember that:

It is my first submission and many things can be wrong. Please have patience and explain to me
what is wrong, I'll be more than happy to fix all things. Especially coding style errors might happen.
I'm from C/Linux kernel/MCU scenery and have very little (VERY little) C++ experience.
So please comment on general design errors, if I'm doing something wrong in general.
I have very little experience with gamedev, so I might do things not efficiently because of lack
of experience. Please point me on these, I want to learn.
The motivation behind this PR is current vehicle example is not that effective, and also very rigid.
I can't spawn 100 cars and have no frame drop.
However with this component I can run 100 cars without slowdowns. Also the flexibility is very good.
And it is easier than making everything from scratch.

The code is based on forum example by @Lumak edited and simplified by me to be minimal.
I plan to implement all features provided by btRaycastVehicle and provide Lua demo too. Also I plan to do general cleanup.

This video demonstrates abilities: https://youtu.be/LKjzcN3s65Y
With particles:
https://youtu.be/zC0iSozwiLM

Sorry for spamming, but github did not allow me to reopen for some reason.
A friend helped me to resove the issue with unreferenced symbols. This happens
when btRaycastVehicle.h is included, so I had to reimplement RaycastVehicle class using
opaque data, so no bullet headers are included with RaycastVehicle.h.

Remaining items (working on till weekend (till April 24)):

- [x] Remove CMAKE option, build with URHO3D_PHYSICS
- [x] Update AngelScript API to accomodate C++ changes
- [x] Update Lua API to accomodate C++ changes
- [x] Add Lua demo
- [x] Improve encapsulation (should not require wheel node hand-manipulation
- [x] Resolve motor wheels not rotating if no ground contact (Bullet behavior,
but it is very annoying)
- [x] Fix save/load crash
- [x] Implement wheel dust in demo (use @Lumak offroad vehicle code for this)
- [x] Move component code to physics subdirectory
- [x] Check coding style consistency (is there some automatic tool?)

Well, current wheel handling code is adequate. The problem might arise when simulating vehicles
with differentials, but I need to read more about this, but it could be implemented later.
Wheel blocking by brakes can be easily implemented outside the component, as it is only a few lines and not needed to be put in FixedUpdate. So I put this on post merge "some time later" schedule.

Sometimes later TODO:
1. Block/slow down wheels on intense brakes (component code)
2. Implement skids. (demo code)
3. Implement side momentum (demo code)

### CODE REVIEW

**Comment by slapin** [comment]
Yay! it builds here too, at least for Travis.

**Comment by Modanung** [comment]
I'd say with built-in support for the Bullet RaycastVehicle the Vehicle sample should simply be replaced with this one. Also I wouldn't consider it bulky enough to have it's own CMake flag, rather I simply see it as part of Bullet.

CoreDev feedback may differ

**Comment by slapin** [comment]
Well, @cadaver told me to remove the option, I will do that in a batch with other feedback I hope to collect.

**Comment by cadaver** [comment]
Yes, keep both examples, for history if nothing else.

**Comment by slapin** [comment]
Well, the resolution of not rotating wheels is not great, but works unless good simulation is required.
In this case it is best to rotate wheels manually.

**Comment by slapin** [comment]
Strange, still no feedback :(

**Comment by slapin** [comment]
Please review, I really really want to get feedback from core devs and plans to merge this.

**Comment by Lumak** [comment]
I like your initiative, but I think you're trying to implement way too many features.  You should keep it simple and just port the btRaycastVehicle and leave out the skid marks and dust.

**Comment by Modanung** [comment]
I think RaycastVehicle.h/cpp should be in the Physics subdirectory instead of a folder of its own.

**Comment by slapin** [comment]
@Lumak
I just want to be able to do skids/dust easily, I will not add these to
component, just necessary functions.
I figure them out now. I will add these functions to demo so it looks less
dull, as test for functions.
As I want it to work for AS, Lua and C++ in similar way, I will have to add
all necessary hooks for functions.

**Comment by slapin** [comment]
To be clear - my biggest interest is to have component minimal and feature-complete.
I will not add unrelated functions there, but for some stuff (like skids) we need some data from btWheelInfo
structure, and so on. And I want to have exported all necessary information.
Also, wheel rotation logic in btRaycastVehicle is incomplete and requires tuning,
I want to provide proper wheel rotation model as this is not trivial code for beginner
and without that code the simulation is incomplete in obvious ways. But I will not add skids graphics
representation or dust particle representation in the component, I just want to be sure that
with exported interfaces it is possible to implement these in user code (C++, AS, Lua)
without deep knowledge of internal workings of btRaycastVehicle and component itself.

**Comment by Modanung** [comment]
> About hosting in my own repo [...] So I want it to be in Urho

I feel like this is in reply to me. If not, sorry for misunderstanding. If so, it seems you misunderstood. I am all for default support of the Bullet RaycastVehicle. What I tried to say is that creating a separate folder seems a bit much.
Basically I would `mv Source/Urho3D/RaycastVehicle/* Source/Urho3D/Physics/`.

**Comment by slapin** [comment]
@Modanung nah. it was reply to @Lumak 's "Couldn't you just demo a simple raycast vehicle as intended by Bullet Physics and create your own repo for a more advance vehicle?"

If that feel better I move to physics folder if @cadaver approves.

**Comment by Modanung** [comment]
Check

**Comment by Lumak** [comment]
@slapin It's a pretty ambitious work load, but I'm confident that you can do it. Use whatever you need from my repo. I'm rooting for you.

**Comment by slapin** [comment]
Added dust. Will add skids and we're feature-complete (not mentioning save/load bug) on the component.
Dust xml is directly from @Lumak offroad vehicle demo.

**Comment by slapin** [comment]
@cadaver @Modanung @Lumak 

I have a problem. I have pointer to btRigidBody and need to get pointer to Urho's RigidBody in most
efficient way possible (i.e. not by getting list of all of them and doing GetBody() and comarison).
Any ideas?

**Comment by Lumak** [comment]
It's because btRaycastVehicle doesn't care about what the actual groundObject is but that it hit something and uses static btRigidBody pointer here:
```
		wheel.m_raycastInfo.m_groundObject = &getFixedBody();///@todo for driving on dynamic/movable objects!;
		//wheel.m_raycastInfo.m_groundObject = object;

```

**Comment by slapin** [comment]
Well, it actually can drive on movable objects already... anyway, I think it is better to prepare
proper pointers beforehand than relying on raycast.

Thanks for help, will go for another approach.

**Comment by cadaver** [comment]
Yes, it's preferable to just put RaycastVehicle inside Physics subdir. There are some simple code convention issues to look for, mainly the m_ member variables and parenthesis spacing.

**Comment by slapin** [comment]
Well, this looks like I will not be able to do skids anyway. However, the component itself is feature-complete enough to do these if somebody will dble able to. The main problem is that I'm unable to find way to
get Drawable suitable for AddDecal, also btRaycastVehicle doesn't report actual body which
is raycast intersects. As I don't quite understand that part of it and reason for it I'd leave it for somebody with more knowledge to do, or I could go back for it if I will need it on some stage.

However dust works, so demo is not that dull looking.

**Comment by Lumak** [comment]
the actual ground object:
```
		//wheel.m_raycastInfo.m_groundObject = &getFixedBody();///@todo for driving on dynamic/movable objects!;
		wheel.m_raycastInfo.m_groundObject = object;

```

**Comment by slapin** [comment]
Just to mention, I work on save/load, it is quite complicated code to do right, so it will take some time.

**Comment by slapin** [comment]
Well, save/load done with (I hope) not too many bugs...

**Comment by slapin** [comment]
Also moved to Physics dir and fixed coding style in component. C++ demo code still have m_ variables.

**Comment by slapin** [comment]
Well, it looks like only Lua demo left, then I will clean-up C++ demo code
and after that this PR can be merged (if it passes review).

**Comment by slapin** [comment]
Please give me some feedback

**Comment by Modanung** [comment]
Looking good, almost there, keep going. :)

**Comment by slapin** [comment]
Added Lua demo. Need to fix emitters in there, as for some reason in Lua they won't work
(or I'm doing something wrong). Will get to it later.

**Comment by slapin** [comment]
OK, almost there. Just need to clean thece m_ variables in C++ demo.
video:
https://youtu.be/zC0iSozwiLM

**Comment by slapin** [comment]
Now I believe that is all. I expect full review at this stage. If anything in particular is wrong I'd expect
some particular comments. @cadaver @Modanung @Lumak the ball is on your side now. I go for good long House Party + GTA SA session then very very long sleep...

**Comment by cadaver** [comment]
Thanks, will take a look on the weekend.

**Comment by cadaver** [comment]
One thing: please remove the profanity / joke from RegisterRaycastVehicleAPI().

**Comment by slapin** [comment]
Removed joke profanity.

**Comment by cadaver** [comment]
Ok. Now tested in more depth. Functionality is very good, feels much more responsive than the old rigidbody vehicle demo. Didn't observe problems with load/save in any of the versions either.

However, there's still a bit to do for the final push:

- The emitter handling in Vehicle class seems somewhat scary. It creates the emitters in ApplyAttributes but that may be called multiple times, e.g. in the editor, each time when the Vehicle's attributes are edited. Maybe at least add a check if the emitters already exist? Also, using either weak or shared ptrs for them would seem safer than raw pointers (C++ example.)

- There's some dead function / variable definitions related to the emitter serialization.

- The help text is different between the different sample versions.

- Indenting, line spacing and comments are kind of all over the place. Also some tabs instead of spaces here and there in the scripts. Can you check to make them consistent with existing Urho classes / script examples? In the C++ sample code, I don't think it's necessary to comment every setter or getter or self-evident member variable, since they would be mostly zero-value information, but consistency is key, so either comment all, or none.

**Comment by slapin** [comment]
Well, I've fixed emitters handling in C++ demo code.
Also I fixed text message to be the same for C++, AS, Lua.
Also I split PR to 4 patches (Component, C++ demo, AS demo, Lua demo).
I also passed files through the following script in hope to get something good:
```shell
sed -e 's/\t/        /g' -i bin/Data/LuaScripts/46_RaycastVehicleDemo.lua
astyle --style=allman --unpad-paren --delete-empty-lines --pad-comma --pad-header --indent=spaces=4 --align-pointer=type bin/Data/Scripts/46_RaycastVehicleDemo.as Source/Samples/46_RaycastVehicle/*.{cpp,h}
sed -e 's/ @/@/g' -i bin/Data/Scripts/46_RaycastVehicleDemo.as
```
Also parsed through clang-formatter but see no difference.

About comments - I looked through them but see nothing wrong about them.
Probably I don't understand your point. Anyway, lets handle them one by one in place,
that would be much easier to do than guess what do you mean by consistency...

**Comment by Modanung** [comment]
Line spacing
- [Extreme example](https://github.com/slapin/Urho3D/blob/de037085a238f447c2a285e8e3c7d7122e2a303e/bin/Data/LuaScripts/46_RaycastVehicleDemo.lua#L309-L335)
- [Subtle example](https://github.com/slapin/Urho3D/blob/de037085a238f447c2a285e8e3c7d7122e2a303e/Source/Samples/46_RaycastVehicle/RaycastVehicleDemo.cpp#L65-L67)

**Comment by slapin** [comment]
Strange, looks like these were added by astyle, fixed these.

**Comment by slapin** [comment]
And Lua script was corrupted by Astyle, reverted back to original.

**Comment by cadaver** [comment]
I was talking about header file comments, sorry I didn't make that clear. You can see the Urho "consistent" comment style in practically every engine and sample header file; every member function and variable is commented by a one-liner comment for Doxygen. 

Mostly only the sample's Vehicle.h header suffers from some members being uncommented and some commented, the "engine side" RaycastVehicle.h was already quite consistent, though note that some comments are double slashes, while they should all be triple slashes so they are picked up by Doxygen.

**Comment by slapin** [comment]
About comments - reading docs I got a feeling that internal class members not intended to be used directly can be left without doxygen-generated descriptions. But having comments is useful to people actually reading code, so I used "//" comments for just in-code comments and "///" for comments intended to go to doxygen. So comments for RaycastVehicle.h private stuff were intentionally set as "//"
and they are mostly random variables not intended to be used directly, only through provided public interfaces (even for derived classes), as they generally are utilitary temporary values.

As for Vehicle.h I updated comments.

**Comment by slapin** [comment]
bump

**Comment by cadaver** [comment]
Rather busy at work, will review eventually. Alternatively any other core dev is free to comment / merge if ok.

**Comment by slapin** [comment]
Ah sorry for bothering, my patience just left me. Will wait patiencelessly.

**Comment by cadaver** [comment]
Merged now. Performed still quite a number of formatting edits, try to follow the code convention / existing code files more precisely next time, including class member ordering. The mid-statement line breaks in the sample code were also quite different at parts compared to rest of Urho code, though arguably clear. Lua didn't have them, only AS & C++ did. I undoed most of it for consistency.

The script API is not particularly script-like, meaning that most work is done through functions instead of properties, but I didn't modify it at least now. Contributions to that are welcome.

But all in all, this was a long ago marked feature request, so thanks for seeing it through!

**Comment by slapin** [comment]
Thanks a lot for your work!
Well, it is really hard for me to comply to Urho coding style, however I tried,
it seems it is a long road for me. Some kind of automatic styling configs/check tools
would help. The only coding style I'm used to is Linux kernel style, I'm from C world
and actually don't know C++ at all, so this all stuff is new for me.

About properties/functions. I was looking at Urho code and seen that it is quite common case where
functions are used where props could be, so I did not think it was a priority goal. Also, I read AS docs
and could not find-out how to make 2-3 argument function into a property. I think it should be possible,
but I found no copy-pasteable examples of it, so I did not implement it. I implemented
a property for single-argument function though.

I hope I will learn more things later as I hope to have more contributions to Urho
so please cope with me.
Thanks again for your work!

**Pull request merged**
