### PR TITLE
Fix RigidBody2D failure to apply transforms that would return it to o…

### LINKED ISSUE #1960: RigidBody2D fails to apply transforms that would return it to original configuration
[Here](https://github.com/urho3d/Urho3D/blob/84c8be164b5187c10edf9a1ad04315d094194b34/Source/Urho3D/Urho2D/RigidBody2D.cpp#L600-L603). The code does not agree with the comment when `body_` is not null.

### PR DESCRIPTION
**Pull request by ricab**
…riginal position and rotation; fixes #1960

### CODE REVIEW

**Comment by ricab** [comment]
Hi, could I get some feedback on this please? (other than seemingly unjustified thumbs down by strange person :stuck_out_tongue: )

**Comment by cadaver** [comment]
I will still have to review properly, have had little time. Should be certainly this weekend.

**Comment by cadaver** [comment]
Looked OK, so merged. Thanks!

**Comment by ricab** [comment]
My pleasure

**Pull request merged**
