### PR TITLE
Fixes to PBR demo and HDR option in editor so PBR displays correct

### PR DESCRIPTION
**Pull request by dragonCASTjosh**
Changes include the following:

Removed Bloom from PBR demo,
Set zone texture ambleint to 1,
Added HDR option in editor settings (needed for PBR in editor)

### CODE REVIEW

**Comment by cadaver** [comment]
The AngelScript version of the PBR demo has the ambient slider, which defaults to 5 and overwrites the scene's value. Should it be removed, since there's no ambient slider in C++ & Lua versions?

**Comment by dragonCASTjosh** [comment]
I think adding it into c++ and lua may be better as it shows such a feature exists

**Comment by dragonCASTjosh** [comment]
Although may be best to default to 1

**Comment by cadaver** [comment]
I can work those changes in before I merge, shouldn't be a large job. It's also better to allow Zone::SetAmbientColor() to set the alpha component directly, without having to go through SetAttribute.

**Comment by dragonCASTjosh** [comment]
if your able to work on that then ill start work on area light.

**Pull request merged**
