### PR TITLE
SpritePacker cli

### PR DESCRIPTION
**Pull request by friesencr**
This is a basic cli program that packs a bunch of pngs into a single large one and generates an urho3d specific xml file.

### CODE REVIEW

**Comment by friesencr** [comment]
@Mike3D i have tried to implement stb rect packer.  can you test your images out?  this algorithm looks like it goes out on a line ... hot dog wise !?!  hopefully it has better results.

**Comment by Mike3D** [comment]
Thanks Chris, here is the result:
brawler
It is tightly packed, but unfortunately not efficiently (image width is twice as it should be, area under the 3 biggest sprites is not used).

**Comment by friesencr** [comment]
It now incrementally increases the size and tries to pack.  Hopefully this is the answer.  I am running out of ideas.

robot

**Comment by friesencr** [comment]
@Mike3D  feel free to try your images again and thanks so much for your help.

**Comment by Mike3D** [comment]
Thanks Chris, it gives way better results that way, and should be OK most of the time.

**Comment by friesencr** [comment]
@cadaver This is ready to go.  If you want me to keep or delete robot dude let me know.  I found it really hard to find a series of sprites on the internet to test out this code so I made it for this case.

**Comment by Mike3D** [comment]
@ line 341, we should replace
```c++
root.SetAttribute("imagePath", spriteSheetFileName);
```
by
```c++
root.SetAttribute("imagePath", GetFileNameAndExtension(outputFile));
```
As I mentioned earlier, 'image path' element in the xml file is the relative path to the spritesheet/atlas image.

**Comment by friesencr** [comment]
@cadaver @weitjong the shared lib build is failing.  i don't think it is my fault.

```
‘Urho3D::PASS_LITBASE’ because of ‘dllexport’ attribute
/home/travis/build/urho3d/Urho3D/Source/Urho3D/Graphics/GraphicsDefs.cpp:81:39: error: external linkage required for symbol ‘Urho3D::PASS_LIGHT’ because of ‘dllexport’ attribute
/home/travis/build/urho3d/Urho3D/Source/Urho3D/Graphics/GraphicsDefs.cpp:82:39: error: external linkage required for symbol ‘Urho3D::PASS_ALPHA’ because of ‘dllexport’ attribute
/home/travis/build/urho3d/Urho3D/Source/Urho3D/Graphics/GraphicsDefs.cpp:83:42: error: external linkage required for symbol ‘Urho3D::PASS_LITALPHA’ because of ‘dllexport’ attribute
/home/travis/build/urho3d/Urho3D/Source/Urho3D/Graphics/GraphicsDefs.cpp:84:40: error: external linkage required for symbol ‘Urho3D::PASS_SHADOW’ because of ‘dllexport’ attribute
/home/travis/build/urho3d/Urho3D/Source/Urho3D/Graphics/GraphicsDefs.cpp:85:42: error: external linkage required for symbol ‘Urho3D::PASS_DEFERRED’ because of ‘dllexport’ attribute
/home/travis/build/urho3d/Urho3D/Source/Urho3D/Graphics/GraphicsDefs.cpp:86:41: error: external linkage required for symbol ‘Urho3D::PASS_PREPASS’ because of ‘dllexport’ attribute
/home/travis/build/urho3d/Urho3D/Source/Urho3D/Graphics/GraphicsDefs.cpp:87:42: error: external linkage required for symbol ‘Urho3D::PASS_MATERIAL’ because of ‘dllexport’ attribute
/home/travis/build/urho3d/Urho3D/Source/Urho3D/Graphics/GraphicsDefs.cpp:88:44: error: external linkage required for symbol ‘Urho3D::PASS_POSTOPAQUE’ because of ‘dllexport’ attribute
/home/travis/build/urho3d/Urho3D/Source/Urho3D/Graphics/GraphicsDefs.cpp:89:41: error: external linkage required for symbol ‘Urho3D::PASS_REFRACT’ because of ‘dllexport’ attribute
/home/travis/build/urho3d/Urho3D/Source/Urho3D/Graphics/GraphicsDefs.cpp:90:43: error: external linkage required for symbol ‘Urho3D::PASS_POSTALPHA’ because of ‘dllexport’ attribute
/home/travis/build/urho3d/Urho3D/Source/Urho3D/Graphics/GraphicsDefs.cpp:92:35: error: external linkage required for symbol ‘Urho3D::DOT_SCALE’ because of ‘dllexport’ attribute
make[2]: *** [Source/Urho3D/CMakeFiles/Urho3D.dir/Graphics/GraphicsDefs.cpp.obj] Error 1
make[1]: *** [Source/Urho3D/CMakeFiles/Urho3D.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by friesencr** [comment]
This is ready to merge.

**Comment by cadaver** [comment]
Ah yes, you have nice documentation section too. Will wait for the size reduce.

**Comment by Mike3D** [comment]
Just a thought, maybe we could skip the robots as we already have the coins and the imp to play with in the Urho2D folder.

**Comment by friesencr** [comment]
The robots are gone.  This should be ready to merge.

**Comment by Mike3D** [comment]
Everything is OK for me, I think it's time to merge, thanks Chris :pizza:

**Pull request merged**
