### PR TITLE
Editor: customizable default scene

### PR DESCRIPTION
**Pull request by 1vanK**
Like Blender. It also looks more attractive for new users than black screen :)

### CODE REVIEW

**Comment by MonkeyFirst** [comment]
Nice feature) 
But maybe also add into scene plane w/o any material and set height fog for Zone. Set ambient and fog color near the same value for produce effect as "endless horizont"

but this 2d grid on floor it actually looking awful on far distances, maybe need change alpha for lines of grid if they enough far from camera to 0. As example in unity grid looking pretty well

**Comment by 1vanK** [comment]
> but this 2d grid on floor it actually looking awful on far distances, maybe need change alpha for lines of grid if they enough far from camera to 0. As example in unity grid looking pretty well

in the Editor this grid is a static model, i think updating it every frame inefficiently. We need another method for dinamic drawing of the grid around camera (like SpriteBath http://urho3d.prophpbb.com/topic596.html )

> also will be great if we could fast swap between scenes with such tool bar feature )

Editor using a global variable "editorScene" and required substantial rewriting of the Editor. Aniway we can do it later

> But maybe also add into scene plane w/o any material and set height fog for Zone. Set ambient and fog color near the same value for produce effect as "endless horizont"

ok

**Comment by 1vanK** [comment]
Default settings for shadows is not optimal. 

Why not using good settings as default?

**Comment by 1vanK** [comment]
Note: if u need empty scene on start - just remove "Sample" node and press "Save scene as default"

**Comment by MonkeyFirst** [comment]
>Why not using good settings as default?
I try to play with CSM splits values and find this values, it's seams enough good for PCF


and need to fix 3DGrid add to it little offset 0.001 by Y to avoid z-fighting with users object placed in world's Y zero cords.

**Comment by 1vanK** [comment]
> fix the 3DGrid, with adding to it little offset 0.001 by Y to avoid z-fighting

0.001 too few (for test just create big plane in editor and move it down)

**Comment by MonkeyFirst** [comment]
>(for test just create big plane in editor and move it down)

grid move to down?) no it must to be moved little upper above 0-plane

this works well
~~~
    float lineOffset = -halfSizeScaled;
    for (uint i = 0; i <= size; ++i)
    {
        bool lineCenter = i == halfSize;
        bool lineSubdiv = !Equals(Mod(i, subdivisionSize), 0.0);
        const float offsetDisplace = 0.001;
        if (!grid2DMode)
        {
            grid.DefineVertex(Vector3(lineOffset, offsetDisplace, halfSizeScaled));
            grid.DefineColor(lineCenter ? gridZColor : (lineSubdiv ? gridSubdivisionColor : gridColor));
            grid.DefineVertex(Vector3(lineOffset, offsetDisplace, -halfSizeScaled));
            grid.DefineColor(lineCenter ? gridZColor : (lineSubdiv ? gridSubdivisionColor : gridColor));

            grid.DefineVertex(Vector3(-halfSizeScaled, offsetDisplace, lineOffset));
            grid.DefineColor(lineCenter ? gridXColor : (lineSubdiv ? gridSubdivisionColor : gridColor));
            grid.DefineVertex(Vector3(halfSizeScaled, offsetDisplace, lineOffset));
            grid.DefineColor(lineCenter ? gridXColor : (lineSubdiv ? gridSubdivisionColor : gridColor));
        }
        else
        {
            grid.DefineVertex(Vector3(lineOffset, halfSizeScaled, offsetDisplace));
            grid.DefineColor(lineCenter ? gridYColor : (lineSubdiv ? gridSubdivisionColor : gridColor));
            grid.DefineVertex(Vector3(lineOffset, -halfSizeScaled, offsetDisplace));
            grid.DefineColor(lineCenter ? gridYColor : (lineSubdiv ? gridSubdivisionColor : gridColor));

            grid.DefineVertex(Vector3(-halfSizeScaled, lineOffset, offsetDisplace));
            grid.DefineColor(lineCenter ? gridXColor : (lineSubdiv ? gridSubdivisionColor : gridColor));
            grid.DefineVertex(Vector3(halfSizeScaled, lineOffset, offsetDisplace));
            grid.DefineColor(lineCenter ? gridXColor : (lineSubdiv ? gridSubdivisionColor : gridColor));
        }

        lineOffset  += scale;
    }
    grid.Commit();
~~~

**Comment by 1vanK** [comment]
> grid move to down?) no it must to be moved little upper above 0-plane

no,  I mean the other :)

**Comment by MonkeyFirst** [comment]
look at this CSM splits settings it seams it slice view space range by this values. 
In this case "working camera range" must to be often sliced I guess.

**Comment by 1vanK** [comment]
I used similar values in my commit :)

light.shadowBias = BiasParameters(0.00005f, 0.5f);
light.shadowCascade = CascadeParameters(10.0f, 50.0f, 100.0f, 0.0f, 0.8f);

**Comment by 1vanK** [comment]
with your settings

**Comment by MonkeyFirst** [comment]
Yes, depth const bias is adjustable value and probably need little tweak it +-

**Comment by cadaver** [comment]
IMHO doing it this way gets in the way of getting work done in the editor. You are welcome to resubmit this PR as just an example scene (.xml or .json) into the Data/Scenes folder

**Pull request closed without merging**
