### PR TITLE
add method for circle,cross,quad debug renderering

### PR DESCRIPTION
**Pull request by 299299**
sorry, I`m not familiar with lua scripting, so this pull request only tested with angel script.

### CODE REVIEW

**Comment by cadaver** [comment]
Please fix the typos and coding convention, e.g. for(int i=1; i<=steps; ++i) has missing spaces.

**Comment by cadaver** [comment]
Thanks! Will check this shortly. The Lua bindings should be a fairly easy addition to DebugRenderer.pkg, I'll do it for now.

**Comment by cadaver** [comment]
Circle was still spelled CirCle, which I fixed. Lua binding seemed OK. What contributor name do you want listed?

**Comment by 299299** [comment]
sorry for the spelling issue, I`m already on the contributor list,  Magic.Lixin. 
 I`m a old fan since the time when Urho3D hosted in google code : )

**Comment by cadaver** [comment]
Ok, thanks, I thought you might be the same since I saw "lixin" in the commit messages.

**Pull request merged**
