### PR TITLE
fix issues of Octree::Update while it working with ThreadedUpdate enabled.

### PR DESCRIPTION
**Pull request by guijun**
drawableUpdates_ will be broken if it working with ThreadedUpdate enabled.

### CODE REVIEW

**Comment by cosmy1** [comment]
Hey, I see some (little) indentation issues with the code.

```
void Octree::Update(const FrameInfo& frame)

**Comment by guijun** [comment]
indentation issues were fixed.

**Comment by cadaver** [comment]
Thanks!

**Comment by guijun** [comment]
Yes, we had encountered the issue.
my game is something complex. there are 5 threads running in my game.

**Comment by cadaver** [comment]
Check if the commit https://github.com/urho3d/Urho3D/commit/32904aefec61bb3457a571ffe3005d7ee73d5c4f fixes the issues you're having. 

Note that any addition or removal of scene nodes/components from worker threads is not allowed and is not expected to work. Similarly calling scene update from worker thread should not be attempted. There's now a main thread check to Octree::Update(), it will now simply return if not called from main thread.

**Comment by guijun** [comment]
thanks, 

I'll adjust my source to fit the change.

**Comment by cadaver** [comment]
Did you already test the modified master branch code? Can this issue be closed now?

**Comment by cadaver** [comment]
Since there hasn't been further communication, and the issue should have been addressed by engine changes, closing this.

**Pull request closed without merging**
