### PR TITLE
Tags menu

### PR DESCRIPTION
**Pull request by MonkeyFirst**
now it w/o 1-9 merge commits.
checkout it, may be it ready now.
- common tags now may changed in editor setting
- tag-menu for UIElements also

### CODE REVIEW

**Comment by 1vanK** [comment]
You did it :)

**Comment by MonkeyFirst** [comment]
if you about removing - no, i still have my old repo) after merging or closing i try to move it back

**Comment by weitjong** [comment]
I can sync my fork with just one CLI command: rake git sync ;)

**Comment by MonkeyFirst** [comment]
cool :+1:  you probably God of syncing :)

**Comment by weitjong** [comment]
What I want to say, or actually promote, is that we have now some collection of convenience git commands in the Rakefile. If you sync periodically before making changes then you can avoid this kind of problem in the first place.

**Comment by cadaver** [comment]
Works simple & nice. Thanks for the updated work!

**Pull request merged**
