### PR TITLE
OBJECT -> URHO3D_OBJECT

### PR DESCRIPTION
**Pull request by 1vanK**

### CODE REVIEW

**Comment by cadaver** [comment]
For consistency's sake, I believe similar treatment should then also be given to EVENT, ATTRIBUTE, HANDLER etc. macros. Opinions?

**Comment by 1vanK** [comment]
Maybe I forgot something.

**Comment by cadaver** [comment]
Thanks for the work! Found a couple more: the logging macros like LOGINFO, LOGWARNING etc. and IS_ASSET in File.h (that one is pretty much only internally used)

**Comment by 1vanK** [comment]
What about defined in CMake, like ASSET_DIR_INDICATOR?

**Comment by cadaver** [comment]
Let's leave those for now, so that we don't break intricacies of the build. Having those clash is extremely unlikely.

**Comment by cadaver** [comment]
I am ready to merge this imminently in a few hours so if any objections, please voice them now :) The logging macros become kind of verbose / unwieldy, but on the other hand it would not be surprising to conflict with some other code that also defines logging, and the consistency is nice.

**Pull request merged**
