### PR TITLE
Fix wrong pvrtc data size.

### PR DESCRIPTION
**Pull request by sssooonnnggg**
This caused pvr textures can't display on iOS devices. #2414

### CODE REVIEW

**Comment by eugeneko** [comment]
I cannot really check this fix now.
However, I recommend to use parentheses -- op priority around bit shifts is tricky sometimes.

**Comment by rokups** [comment]
Hey @sssooonnnggg could you please provide a sample texture that failed to load on iOS and now works after fix is applied?

Also you should not mix multiple things in a single PR. etc2 support should be submitted in another PR. Also mind formatting there ;)

**Comment by eugeneko** [comment]
The initial fix cannot work.
It makes me suspicious -- how did you test your fix?

I also wonder if it's possible to use simpler math for `PVRTC`, similar to `DXT` formats. I'm not an expert, tho.

**Comment by sssooonnnggg** [comment]
My bad， I will close this PR and create new PRs.

**Comment by rokups** [comment]
You did not have to close it. You may clean up your branch and force-push it.

**Comment by sssooonnnggg** [comment]
@rokups I didn' realize that I had mix multiple things on the master branch. I have created two separate branches to fix this. Thans a lot . ：）

**Pull request closed without merging**
