### PR TITLE
kNet: Prevent SIGPIPE signal when other end closes connection.

### PR DESCRIPTION
**Pull request by henu**
I'm using kNet in my multiplayer game, but it often crashes the whole server with SIGPIPE signal. I don't see any point in receiving the signal, so this PR just disables it. The error handling that already exists in the code nicely catches and handles the error.

If you have some information what would be the better way to handle this, please let me know. To my knowledge, this happens in a thread created by the kNet lib, so I don't know if it is possible to somehow catch the signal in the code of my game and ignore it.

I have only tested this on Linux, so I have no idea if it works on Windows or Mac. [Some guy claimed  Windows does not have SIGPIPE](https://stackoverflow.com/questions/23911929/writing-to-a-close-socket-didnt-raise-a-sigpipe-as-expected#comment36851122_23911929), and [according to documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/ms740149\(v=vs.85\).aspx) it has no MSG_NOSIGNAL either, so I just ignored this on Windows. 

I also added Lasse Öörni's name to comment, as he has also modified Socket.cpp for Urho3D, but there was no mention about him. Last time when I created a pull request modifying third party lib somebody told me those mentions should always be there :)

### CODE REVIEW

**Comment by weitjong** [comment]
Just done some googling now. It seems that `MSG_NOSIGNAL` flag may be specific to Linux and some UNIX but not BSD/Darwin (read MacOS), if I understood it correctly. If so then we need another code branch for macOS using `SO_NOSIGPIPE` option as follows.

```
int set = 1;
setsockopt(sd, SOL_SOCKET, SO_NOSIGPIPE, (void *)&set, sizeof(int));
```

Which is not so nice. Have you tried `signal(SIGPIPE, SIG_IGN)`? Say in the `Network::StartServer()`. That should work for all the *Nix including MacOS, so it just need to be guarded against `_WIN32`.

**Comment by henu** [comment]
Finally a reply! :D

In my opinion your solution looks nice. I guess it only needs to be called when socket is created?

But I can try the ignoring if you like that more. I already tried it in my own code, but not in the library code. I can try that at some point during this weekend.

**Comment by weitjong** [comment]
Thanks for your patience :smile:

I reckon the Network::StartServer() is only being called once per server app, so it would be good place to put the code for ignoring the SIGPIPE.

**Comment by weitjong** [comment]
The `SO_NOSIGPIPE` option only works for some BSD flavors of *Nix and not works for Linux. The option need to be set when start listening to the socket, as you already guess. So using this, still require the bit you have already proposed for Linux. Which is why I don’t like it. And prefer the latter approach I mentioned. I hope that clarifies.

**Comment by weitjong** [comment]
@henu Any update?

**Comment by henu** [comment]
@weitjong Ah sorry, I forgot this whole thing and I have been doing other projects :(

I tested it now, but I was unable to prevent the crash with signal ignoring. I tried to put it in the `Network::StartServer()` and since it didn't work, I also tried `NetworkWorkerThread::MainLoop()` which is the actual thread where the crash happens. But no luck.

I suggest I make those BSD/Darwin modifications you mentioned, but unfortunately I cannot test them.

**Comment by weitjong** [comment]
Thanks for checking it and making a new commit.

**Pull request merged**
