### PR TITLE
New logo

### PR DESCRIPTION
**Pull request by Modanung**
Cropped the black and white logo (svg) and placed it at the top of the readme.
Also I replaced the logo in the sample (png) with the one with colour again. Could it _pretty please_ stay there? I really like how it turned out, goes on all backgrounds and has some colour of the previous logo (and Ogre) in it.
Just look at that

### CODE REVIEW

**Comment by Modanung** [comment]
The [file history on LibreGameWiki](https://libregamewiki.org/File:Urho3D.svg) holds a lot of versions for anyone who's interested.

**Comment by Modanung** [comment]
Here's one for the band:
Urho Band Logo

**Comment by cadaver** [comment]
This is fine. Will merge.

**Comment by Modanung** [comment]
Thanks, and sorry for being pushy.

**Comment by cadaver** [comment]
Merged.

**Comment by Modanung** [comment]
Awesome :)

**Pull request closed without merging**
