### PR TITLE
Pengfei666/bordless window without position

### PR DESCRIPTION
**Pull request by pengfei666**
For issue https://github.com/urho3d/Urho3D/issues/1970

pho95i owyi_0mzasmdj 4

### CODE REVIEW

**Comment by cadaver** [comment]
Thanks. Will need to review. I believe the original intention of borderless has been to be a substitute for fullscreen, in which case the position wouldn't matter.

**Comment by eugeneko** [comment]
If borderless window is used without specifying position/size, it is fullscreen in version _before_.
How does it behave in version _after_?

**Comment by pengfei666** [comment]
Okay. Wait a moment. I will paste the picture.

**Comment by pengfei666** [comment]
z681fhjf w3i z 1vp l k

**Comment by cadaver** [comment]
Since we got just some time ago the ability to position the window on any monitor in multi-monitor setups, that might get broken now for borderless windows? So what it possibly needs to do is to still do the auto-positioning for both borderless & fullscreen, if a position was not explicitly specified. How to detect that situation, is another thing.

**Comment by castiel520** [comment]
yeah, I think window positioning is fixed for borderless if a position was specidied. 
but what if we want to drag a borderless window?

**Comment by cadaver** [comment]
I believe I managed to make a change that should enable borderless monitor select to still work properly. May not be perfect but can be improved later. Will merge / push shortly.

**Comment by cadaver** [comment]
Merged, with changes.

**Pull request closed without merging**
