### PR TITLE
Benchmark

### PR DESCRIPTION
**Pull request by 1vanK**

### CODE REVIEW

**Comment by eugeneko** [comment]
FYI: JSON scenes are unstable in general because Urho loads component attributes in _random_ order from JSON.
If you get unlucky, your component will fail to load and you will be unable to do anything about it.

**Comment by 1vanK** [comment]
Thanks for the information. The scenes are just stubs now, so it won't be a problem to replace them with xml

**Comment by 1vanK** [comment]
@eugeneko I haven't done any tests, but it seemed to me that xml scenes load much faster than json. I assumed it would be the other way around since xml is a much more complex and verbose format.

**Comment by 1vanK** [comment]
https://www.youtube.com/watch?v=bw3lsSqlxgM

**Comment by 1vanK** [comment]
The idea taken from here https://www.youtube.com/watch?v=71rhWjM6aMo

**Pull request merged**
