### PR TITLE
Cppformat

### PR DESCRIPTION
**Pull request by hdunderscore**
I was interested in the suggestion posted in this issue: https://github.com/urho3d/Urho3D/issues/472

This adds cppformat to Urho3D and exposes some python-like string formatting functions that can be used in script too.

This is a WIP and open to suggestion.

### CODE REVIEW

**Comment by weitjong** [comment]
Nice one!

**Comment by cadaver** [comment]
If float conversion performance isn't affected much, then shouldn't be a problem to merge. Will just have to do some before/after measurements.

**Comment by hdunderscore** [comment]
I've only briefly touched on the lua bindings without testing them yet.

**Comment by hdunderscore** [comment]
I reverted the changes to the float-to-string parts of the code to avoid any performance hits -- if one day cppformat gets the update to that part of the code, it can be added again.

Lua gets the String::Format via the global ToString(const String& formatString, const Vector<StringArg>& args), as I noticed there was already a similar global ToString function (although I don't believe the existing bindings for that work in lua?).

Here's an Angelscript test demonstrating the bindings:

```c++
#include "Scripts/Utilities/Sample.as"

void Start()
{
    // Execute the common startup for samples
    SampleStart();

    // Disable default execution of AngelScript from the console
    script.executeConsoleCommands = false;

    // Subscribe to console commands and the frame update
    SubscribeToEvent("ConsoleCommand", "HandleConsoleCommand");
    SubscribeToEvent("Update", "HandleUpdate");

    // Subscribe key down event
    SubscribeToEvent("KeyDown", "HandleEscKeyDown");

    // Hide logo to make room for the console
    SetLogoVisible(false);

    // Show the console by default, make it large
    console.numRows = graphics.height / 16;
    console.numBufferedRows = 2 * console.numRows;
    console.commandInterpreter = "ScriptEventInvoker";
    console.visible = true;
    console.closeButton.visible = false;

    // Show OS mouse cursor
    input.mouseVisible = true;

    // Open the operating system console window (for stdin / stdout) if not open yet
    // Do not open in fullscreen, as this would cause constant device loss
    if (!graphics.fullscreen)
        OpenConsoleWindow();
        
        
    RunTests();
}

void RunTests()
{
    String formatString("");
    Array<StringArg> args;
    for (uint i = 0; i < 1000; ++i)
    {
        formatString += "{} ";
        args.Push(StringArg(i, i));
    }
    // Large number of arguments:
    Print(formatString.Format(args));
    // ill-formed format string:
    Print(Format(formatString + " }", args));
    // format string requesting too many arguments:
    Print(Format(formatString + " {}", args));
        
    // performance test:
    float t = time.elapsedTime;
    for (uint i =0; i < 100; ++i)
    {
        formatString.Format(args);
    }
    args.Clear();
    args.Push(StringArg(time.elapsedTime - t));
    Print("Time elapsed: {} seconds".Format(args));
    
    // named arguments test:
    Array<StringArg> vocab;
    vocab.Push(StringArg("noun0", Variant("house")));
    vocab.Push(StringArg("noun1", Variant("car")));
    vocab.Push(StringArg("noun2", Variant("man")));
    vocab.Push(StringArg("noun3", Variant("Peter")));
    vocab.Push(StringArg("noun4", Variant("potato")));
    vocab.Push(StringArg("noun5", Variant("rock")));
    vocab.Push(StringArg("noun6", Variant("earth")));
    vocab.Push(StringArg("noun7", Variant("tree")));
    vocab.Push(StringArg("noun8", Variant("Sally")));
    vocab.Push(StringArg("noun9", Variant("truck")));
    
    vocab.Push(StringArg("verb0", Variant("explode")));
    vocab.Push(StringArg("verb1", Variant("fell")));
    vocab.Push(StringArg("verb2", Variant("drove")));
    vocab.Push(StringArg("verb3", Variant("strike")));
    vocab.Push(StringArg("verb4", Variant("rolled")));
    vocab.Push(StringArg("verb5", Variant("ran")));
    vocab.Push(StringArg("verb6", Variant("flew")));
    vocab.Push(StringArg("verb7", Variant("sunk")));
    vocab.Push(StringArg("verb8", Variant("phase")));
    vocab.Push(StringArg("verb9", Variant("teleport")));
    
    
    for (uint i = 0; i < 10; ++i)
    {
        args.Clear();
        args.Push(StringArg(int(Random(10))));
        args.Push(StringArg(int(Random(10))));
        args.Push(StringArg(int(Random(10))));
        formatString = "{{noun{}}} {{verb{}}} to {{noun{}}}".Format(args);
        Print(formatString);
        
        Print(formatString.Format(vocab));
    }
    
    // variant types test:
    args.Clear();
    args.Push(StringArg(Variant(Vector2(1.23456,2.34567))));
    args.Push(StringArg(Variant(Vector3(1.23456,2.34567,3.45678))));
    args.Push(StringArg(Variant(Vector3(4.56789,5.67890,6.78901))));
    Print("{} | {} | {}".Format(args));
}

void HandleConsoleCommand(StringHash eventType, VariantMap& eventData)
{
    if (eventData["Id"].GetString() == "ScriptEventInvoker")
        HandleInput(eventData["Command"].GetString());
}

void HandleUpdate(StringHash eventType, VariantMap& eventData)
{
    // Check if there is input from stdin
    String input = GetConsoleInput();
    if (input.length > 0)
        HandleInput(input);
}

void HandleEscKeyDown(StringHash eventType, VariantMap& eventData)
{
    // Unlike the other samples, exiting the engine when ESC is pressed instead of just closing the console
    if (eventData["Key"].GetInt() == KEY_ESC)
        engine.Exit();
}

void HandleInput(const String&in input)
{
    String inputLower = input.ToLower().Trimmed();
    if (inputLower.empty)
    {
        Print("Empty input given!");
        return;
    }

    if (inputLower == "quit" || inputLower == "exit")
        engine.Exit();
}

// Create XML patch instructions for screen joystick layout specific to this sample app
String patchInstructions =
        "<patch>" +
        "    <add sel=\"/element/element[./attribute[@name='Name' and @value='Button2']]\">" +
        "        <attribute name=\"Is Visible\" value=\"false\" />" +
        "    </add>" +
        "    <add sel=\"/element/element[./attribute[@name='Name' and @value='Hat0']]\">" +
        "        <attribute name=\"Is Visible\" value=\"false\" />" +
        "    </add>" +
        "</patch>";
```

**Comment by hdunderscore** [comment]
Going to close this for now, I'll reopen when I clean up the source.

**Comment by weitjong** [comment]
Any update on this one?

**Comment by hdunderscore** [comment]
The main issue I was having with this was unclean includes, I wasn't too happy about including so much extra stuff in an Urho header.

I can post the last changes I made if you want to take a crack at it, otherwise it might be something that makes more sense in the code exchange.

**Comment by weitjong** [comment]
Sounds good to me.

Best regards,
YaoWT

**Comment by hdunderscore** [comment]
I just checked my local commit, there were only insignificant changes after all.

**Pull request closed without merging**
