### PR TITLE
Support building engine with multiple graphics API

### PR DESCRIPTION
**Pull request by 1vanK**

### CODE REVIEW

**Comment by 1vanK** [comment]
@weitjong any ideas?

**Comment by 1vanK** [comment]
Problem with LUA on iOS started from [Minimize usage URHO3D_OPENGL](https://github.com/urho3d/Urho3D/pull/2885/commits/c69c9c514ac2bfc33185e6c33b45115b791b8522) but header files not changed

**Comment by weitjong** [comment]
I am sorry. I don’t have any spare time for the project now. It is difficult for me to see what went wrong just by looking at those commits, especially when a few commit IDs now become invalid (probably due to force push or something). I also promise myself not to touch those old CMake build scripts anymore.

**Comment by 1vanK** [comment]
Building:
```
cmake.exe repo -B build_vs -G "Visual Studio 17" -A x64^
 -D URHO3D_OPENGL=1 -D URHO3D_D3D9=1 -D URHO3D_D3D11=1^
 -D URHO3D_LIB_TYPE=STATIC -D URHO3D_STATIC_RUNTIME=0 -D URHO3D_HASH_DEBUG=0^
 -D URHO3D_ANGELSCRIPT=1 -D URHO3D_FORCE_AS_MAX_PORTABILITY=0 -D URHO3D_LUA=1 -D URHO3D_LUAJIT=1 -D URHO3D_GENERATEBINDINGS=0^
 -D URHO3D_SAMPLES=1 -D URHO3D_TOOLS=0 -D URHO3D_DOCS=0^
 -D URHO3D_NETWORK=1 -D URHO3D_DATABASE_SQLITE=1 -D URHO3D_TRACY_PROFILING=0 -D URHO3D_PHYSICS2D=1 -D URHO3D_URHO2D=1
```

Running:
```
18_CharacterDemo_d.exe -opengl
18_CharacterDemo_d.exe -d3d9
18_CharacterDemo_d.exe -d3d11
```

**Comment by eugeneko** [comment]
Just curious, what's the performance impact on Sample 20 (Debug and Release)?
Maybe I'll test that myself but I don't know when I will be able to.

**Comment by eugeneko** [comment]
Sample 20 with instancing off shows 15% performace degradation in both debug and release. Still not that much given the nature of the sample and conditions.

image

**Comment by 1vanK** [comment]
I will check it. As an optimization we can use function pointers instead of using `if (gapi == x) then call func_x();`

**Comment by eugeneko** [comment]
Note that I have disabled instancing to measure draw command queuing itself (which was affected by PR).
With instancing on there are very few draw calls and probably no difference.

**Comment by 1vanK** [comment]
Old release 
изображение

New Release:

изображение

Old Debug:

изображение

изображение

**Comment by eugeneko** [comment]
Okay, I just tried it and got totally different numbers, maybe some weird shit in drivers. I tested OpenGL btw.
Anyway, I don't think this impact matters, as I said. Even 15% in artificial corner case is okay.

**Comment by 1vanK** [comment]
> I tested OpenGL btw

The same. API is printed on bottom of Debug Hud

**Comment by 1vanK** [comment]
Mingw x64 release

Old:
old

New:
new

**Pull request merged**
