### PR TITLE
An intersection test for IntRect

### PR DESCRIPTION
**Pull request by tederis**

### CODE REVIEW

**Comment by eugeneko** [comment]
The check is incorrect: `IntRect{ 0, 0, 1, 1 }` and `IntRect{ 1, 1, 2, 2 }` don't intersect.

**Comment by 1vanK** [comment]
as far as I remember, in urho right and bottom borders do not belong to a rectangle, but left and upper belong to the rectangle

**Comment by tederis** [comment]
I have made two separated commits contain different strateges: with and without implying right-bottom borders are owned by rect. I think the final variant is correct and best suitable with this particular Urho3D implementation.

**Comment by eugeneko** [comment]
Looks good for me

**Pull request merged**
