### PR TITLE
Paint selection and origins

### PR DESCRIPTION
**Pull request by MonkeyFirst**
Hi folks! 
I took feature from my fork for editor and tried to put it on new rails of new version of the engine. 
if this needed for editor, checkout this please

- PaintSelection tool on KEY_C (use origins)
- Origins for show and select nodes (empty, light), button in toolbar + KEY_SPACE for show/hide names

* currently range visibility of origins is 32 units, but may increased to 64 or 128...

### CODE REVIEW

**Comment by cadaver** [comment]
Is there new key shortcuts? Does the editor documentation need updates? If not I think this could go in as is, if yes it shouldn't be a large work.

**Comment by MonkeyFirst** [comment]
little question: the proc DeselectNode() was removed for some reason from new editor, but I bring it back. but it's seems not working properly now in new behavior. Is there exist another proc for deselecting node from EditorHierarchyWindow ?

**Comment by cadaver** [comment]
I have no memory of that function.

**Comment by MonkeyFirst** [comment]
Deselecting work in std.mode with Ctrl, so I'm change this key for both modes.
I think for now it's ready. Checkout.

**Comment by cadaver** [comment]
Thanks. Will check soon.

**Comment by cadaver** [comment]
Merged.

**Pull request merged**
