### PR TITLE
Input mousemode updates

### PR DESCRIPTION
**Pull request by hdunderscore**
Some fixes to the input issues that have popped up on the Web platform, and an attempt to make the mouse modes compatible with the Console.

Related issue: https://github.com/urho3d/Urho3D/issues/917

```
- Added a way to suppress mouse mode and mouse grab changes (SetMouseMode(mode, suppress = false), 
SetMouseGrabbed(grab, suppress = false)), and reset them to a previous unsuppressed state (ResetMouseMode, 
ResetMouseGrabbed).
- Updated Console to react to mouse modes, similarly to mouse visibility previously.
- Console will utilize UI cursor if available.
- Fixed a bug with mouse modes not calling SetMouseGrab correctly.
- Updated samples to use different mouse modes where necessary.
- Updated samples to request pointer lock on mouse down event (Web platform).
- Updated samples that show the UI cursor to show the OS cursor if pointer lock (ie, mouse mode MM_RELATIVE) 
isn't acquired. This conceals a visual bug in UI cursor position (Web platform).
```

### CODE REVIEW

**Comment by cadaver** [comment]
Nice update!

**Comment by hdunderscore** [comment]
I think that can work, when absolute + hidden mouse, we request pointerlock, when absolute + visible mouse we leave pointerlock. Then it would be consistent with desktop and it should be quite seamless after the initial request.

I am not able to reproduce that appveyor segfault, and only one thing comes to mind about the potential source (in samples-> InitMouseMode called before CreateConsoleAndHUD), so I'll shuffle that around.

Anyone able to test these changes on mobile? I haven't had a chance to do so yet.

**Comment by weitjong** [comment]
> I am not able to reproduce that appveyor segfault, and only one thing comes to mind about the potential source (in samples-> InitMouseMode called before CreateConsoleAndHUD), so I'll shuffle that around.

The random crash of crowd navigation sample app is a known issue (#1200), so you should not be concerned about it.

**Comment by cadaver** [comment]
A quick test of NinjaSnowWar on Android at least didn't reveal anything to be broken.

**Comment by cadaver** [comment]
Hmm, I quickly tested the 06_SkeletalAnimation sample in Emscripten, windowed mode. The behavior seemed like before (mouse cursor is hidden, but it's not confined to the window, and pointer lock request dialog did not turn up)

**Comment by cadaver** [comment]
Emscripten samples indeed seemed to work nicely now. But on Windows I got a crash when I pressed right mouse button down in the editor. Didn't investigate further yet.

**Comment by hdunderscore** [comment]
Thanks for testing it out! That crash is concerning, hopefully it's easy to track down.

I've been slowly working at the MM_ABSOLUTE behavior, haven't quite got it nailed down yet.

**Comment by cadaver** [comment]
The crash is due to AngelScript bindings not being updated when the SetMouseMode function gained an additional parameter. Because the mousemode is a property which can only have one parameter, you need to create a wrapper function. Probably best to also expose SetMouseMode as a function so that user can supply "true" to the suppressEvent parameter.

**Comment by hdunderscore** [comment]
Nice catch, I'll update that.

**Comment by TheComet93** [comment]
The shared build (DLL) on Windows x64 seems to be very fragile. I had the same sample (39_CrowdNavigation) segfault on my last push, but it worked fine before that and I really didn't change anything other than renaming a symbol.

Double check you're not sharing memory across DLL boundaries. If you are, make sure you're correctly exporting it. That seemed to help.

**Comment by weitjong** [comment]
The crash could happen on both STATIC and SHARED 64-bit build. For future discussion on this issue may I suggest to use #1200. I have just unlock it for public discussion.

**Comment by hdunderscore** [comment]
Just an update, I'm inching closer to solution on this, it's a bit of a moving target as I find new little issues.

The latest change I've made is to turn off the event polling loop for emscripten and make use of SDL_AddEventWatch-- this means if you request pointerlock from an Urho input event with my upcoming changes, it will activate right in that event from the browsers perspective.

Previously, since we were polling for the events, regardless of where you requested pointerlock it would always occur in the next input event. This was all occurring very subtly due to this: https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/Input/Input.cpp#L132  The second argument (deferUntilInEventHandler) concealed the issue.

This meant for example, if you wanted to switch into MM_RELATIVE on mouse down, and switch out on mouse up, it wouldn't work before because the request in mouse down would be deferred to the next input event (commonly mouse up).

**Comment by cadaver** [comment]
Ah, makes sense, thanks for continued looking into this!

**Comment by hdunderscore** [comment]
I have pushed my changes-- I still need to update the script samples and perhaps polish some things off (also just spotted some whitespace issues).

To simplify testing, I have made the mouse controls slightly different in some of the samples to provide test cases and identify bugs. I need help with testing, let me know if you notice any issues.

- One known issue is LoseFocus/GainFocus behaviour is a bit different now, mouse modes don't immediately re-engage on GainFocus.
- On web, right click can sometimes open context menu.
- A possible issue could exist with this change too (I removed the if-guard on the delta changes, so they could be used by UI cursor): https://github.com/urho3d/Urho3D/commit/157d22b09caef0ec43679417b29860f80b7c3947#diff-eeea0f0ea09c3078b218adad26e10f10L1583
- This should probably be flipped back to true for the general case: https://github.com/hdunderscore/Urho3D/commit/157d22b09caef0ec43679417b29860f80b7c3947#diff-eeea0f0ea09c3078b218adad26e10f10R164

**Comment by cadaver** [comment]
Excellent! I should be able to test the web examples shortly.

**Comment by cadaver** [comment]
Tested on Windows desktop first. No crashes :) Editor and NinjaSnowWar worked great.

However the control scheme seemed changed on some examples, and it didn't seem to always work consistently. For example in 06_SkeletalAnimation I need to hold down right mouse to move with WASD (and debug geometry toggling doesn't work), while in 08_Decals I don't need to hold RMB to move

If the Emscripten pointer lock logic works OK in absolute mode now, could even all the samples be left unmodified compared to master branch?

**Comment by hdunderscore** [comment]
Thanks for testing !

We can definitely keep the samples unmodified after we test across platforms and don't spot any issues-- I noticed on the forums etc that it's hard to predict how people will use the mouse modes so I wanted to test different cases, and I was definitely able to spot and squash issues while developing the PR with the different tests.

**Comment by hdunderscore** [comment]
Actually thinking about it a bit more, some of the sample changes are needed, eg:
- Need a consistent way to request pointerlock, otherwise if the user misses the first prompt they will have to reload the page. This can be changed to be more consistent with existing sample style though.
- It can take a while to load an online html5 sample, so limiting the 'exit engine' logic is important to prevent confusion.
- The escape key logic moved to key up was needed to prevent a full exit of pointerlock with the console open.

**Comment by cadaver** [comment]
Ah ok, naturally those changes are necessary.

**Comment by cadaver** [comment]
Didn't have time to test everything yet, but at least StaticScene, AnimatingScene, SkeletalAnimation & Decals worked great, and similarly on web & desktop.

**Comment by hdunderscore** [comment]
Just rebased with master to try with SDL 2.0.4, I haven't done any significant testing yet.

**Comment by hdunderscore** [comment]
I made some changes and I think it's ready for merge, if there are no further issues identified.

**Comment by cadaver** [comment]
Tested examples & script examples quickly on desktop and didn't notice anything off.

**Comment by cadaver** [comment]
It's now in. Thanks again!

**Pull request merged**
