### PR TITLE
Add Http Request demo sample.

### PR DESCRIPTION
**Pull request by cosmy1**
Commited just AngelScript version for now to avoid CI failure as require #1381 to be merged first. (Lua version have some issues with Deserializer API, I need to investigate because may be a bug in Urho3D/tolua++).

### CODE REVIEW

**Comment by cadaver** [comment]
#1381 was OK and merged.

**Comment by cosmy1** [comment]
The lua sample have some issue with ```ReadLine()```.
http://puu.sh/p26Oj/ea45e0b8d3.png

I will look in depth later.

**Comment by cadaver** [comment]
I recommend to just commit the offending code, that way more people can look into it.

**Comment by cosmy1** [comment]
Ok commited.

**Comment by cadaver** [comment]
Merged. The crash was related to multiple inheritance and was fixed by copying the Deserializer functions into HttpRequest .pkg file, similar to File.pkg, instead of letting tolua++ know that HttpRequest is a Deserializer subclass.

**Comment by cosmy1** [comment]
:+1:

**Pull request merged**
