### PR TITLE
Update rapidjson to Version 1.0.2

### PR DESCRIPTION
**Pull request by svifylabs**

### CODE REVIEW

**Comment by Stinkfist0** [comment]
The Urho3D-specific modification(s) are lost and should be preserved.

**Comment by weitjong** [comment]
We are slowly moving toward using "git subtree" to manage all our future
3rd-party library updates. We already have a set of rake tasks to aid this
migration process. However, they are designed for the Urho3D project
members with push privilege. The objective of this migration is exactly to
avoid our modification for Urho3D getting lost.

Best regards,
YaoWT

**Comment by svifylabs** [comment]
hmm ok so i should close it ? 
what are the modifications ? 
tested it with the scene load example using json to save and load the scene.

**Comment by Stinkfist0** [comment]
The modifications should be only three lines, look for "Urho3D" in the originals files (prettywriter.h might be the only file with modifications).

**Pull request closed without merging**
