### PR TITLE
Adding Urho3DAll.h

### PR DESCRIPTION
**Pull request by 1vanK**

### CODE REVIEW

**Comment by weitjong** [comment]
This is a duplicate of #629. IMHO, this is a bad practice. Sure it is convenient but it slows the build unnecessarily. It makes the source code depends on all the Urho3D headers that it really needs. The dependency is being checked on each build and when any single Urho3D header does change, your source code will be rebuilt totally instead of incrementally. Also, it would add burden to contributors to maintaining this header file manually when we change our code base.

**Comment by 1vanK** [comment]
Any user can use the old way if he wants to. But now he has an alternative :) And add a few lines is not so difficult for contributors.

**Comment by MonkeyFirst** [comment]
I have something similar - common.h with most used urho's headers files within (for Precompiled)
it's speedup compiling.

**Comment by weitjong** [comment]
Don't get me wrong. Adding a few more headers that you think are commonly used by your own project to your own project's Precompiled.h is fine. But adding **all** headers into a single header file just for saving the developer to include the required headers the code actually needs is another matter. It would not be any better even when this single header file is getting precompiled. You can do a quick google search on why this is a bad practice. But, hey, you can do what you want within your own project. For Urho3D project though, my original opinion still stands. Personally I would not promote bad practice. Just my two cents.

**Pull request closed without merging**
