### PR TITLE
Update FreeType to 2.8.

### PR DESCRIPTION
**Pull request by iainmerrick**
This is needed for correct handling of fractional sizes (issue #1952).

I downloaded http://download.savannah.gnu.org/releases/freetype/freetype-2.8.tar.gz and copied over the src, include and docs directories. I kept the Urho3D patch in src/gzip. Compiles and seems to work. :)

If you have a more formal process for updating third-party libraries, let me know!

### CODE REVIEW

**Comment by cadaver** [comment]
For 3rd party libraries that aren't yet as own repos and used as subtrees, this procedure is fine. Note that documentation refers to lib versions (README.md and Urho3d.dox). Can fix in this case. Will now make a branch for complete CI-testing first.

**Comment by cadaver** [comment]
CI builds looked ok, merged now!

**Comment by Florastamine** [comment]
Just a very minor thing: IMO the `docs/` folder should be removed as there's no real need for it.

**Comment by cadaver** [comment]
True, at least the reference folder seems extraneous, since we don't keep full API documentations to other 3rdparty libs either.

**Pull request merged**
