### PR TITLE
Str: allow move assignment to self

### PR DESCRIPTION
**Pull request by moneromooo**
It's used for instance when shuffling a std::vector of String

### CODE REVIEW

**Comment by eugeneko** [comment]
This is actually good point. Can you revise other move-assignments in Urho and fix them as well if they are broken? Shouldn't be too many.

**Comment by eugeneko** [comment]
Thanks! I will merge it when build passes

**Comment by 1vanK** [comment]
Maybe just put the check to `Swap()`?

**Comment by 1vanK** [comment]
The question remains, which is more of an impact on performance: additional branching due by `if` or unnecessary copying of a variable.

**Comment by eugeneko** [comment]
I don't believe that this branching have any significant contribuition in any case.

Having said that... probably branching has more impact than redundant swap just because statistically `this == &rhs` happens rarely. So maybe it would be slightly better to keep swaps w/o asserts.

**Pull request merged**
