### PR TITLE
Application wide global variable implementation

### PR DESCRIPTION
**Pull request by BlueMagnificent**
This extends the AngelScript scoped global variable implementation (globalVars) to cover the entire application

### CODE REVIEW

**Comment by weitjong** [comment]
Nice!

**Comment by 1vanK** [comment]
But variantMap has more, than two methods :)

**Comment by 1vanK** [comment]
In C++ I just register my own subsystem, if I need global variables and functions

**Comment by weitjong** [comment]
This PR is still nice to bring the feature parity to Lua scripting environment and C++.

**Comment by BlueMagnificent** [comment]
@1vanK , the idea leans more towards being a global variable storage than a global VariantMap. As it is, the application has no idea of how the global variable is implemented within the context, all it sees are the getter and setter methods

**Comment by cadaver** [comment]
Good work, thanks! Will compare this to the node / UIElement vars implementation, there the functions are called SetVar() / GetVar(), so the global var access function names could be shortened too.

**Comment by 1vanK** [comment]
Also UIElement has
```
const VariantMap& GetVars() const { return vars_; }
```

**Comment by cadaver** [comment]
True. In AngelScript it's exposed as a modifiable VariantMap, since in practice that doesn't do harm to allow direct non-const access, so the same could be done for these, as a global property.

**Comment by BlueMagnificent** [comment]
Cool. Would do some refactoring right away and push the commits.

**Comment by cadaver** [comment]
Please go ahead. We can also do further adjustments before merge, if necessary.

**Comment by BlueMagnificent** [comment]
Quite a couple of changes have been effected. Shortened function name to GetGlobalVar() and SetGlobalVar(). That seems to be the shortest I could get that conveys the meaning :( . globalVariables_ was also renamed to globalVars_ and exposed as a global property to AngelScript as rightfully suggested.

**Pull request merged**
