### PR TITLE
No need to do versioning on binaries

### PR DESCRIPTION
**Pull request by richelbilderbeek**
As .a files are created from source, no need to do versioning on those files.

### CODE REVIEW

**Comment by weitjong** [comment]
Thanks for your PR.

IMHO, the ```*.a``` is never ever going to be checked in into our source code repository, so there is no need to add ```*.a``` into the ```.gitignore``` file. The ```*.cmake```, however, does not necessarily mean generated file (See our CMake modules and toolchains for example). So, it should not be added into the ```.gitignore``` file.

Your changes for Clamp() function seem to be not relevant to this PR (No need to do versioning on binaries). May I suggest you to raise a separate PR for that because I am going to close this one now.

**Comment by weitjong** [comment]
Note that even in a non out-of-source build-tree scenario, the generated ```*.a``` archived library would be located in the ```/lib*/``` directory which we already added into the ```.gitignore``` file. But perhaps, there is a merit to change ```/lib*/``` to just ```lib*/``` (and also the rest of the output directories in the current ```.gitignore``` file) so that it also works for relative build-tree inside the project root. You are welcome to make another PR or reopen this one for this.

**Comment by richelbilderbeek** [comment]
> IMHO, the *.a is never ever going to be checked in into our source code repository, 
> so there is no need to add *.a into the .gitignore file.
Perhaps you don't have this problem in some way, when I build Urho3D, `git status` wants me to add all these `.a` files. IMHO, `git status` should indicate it has nothing new to do versioning on.

> The *.cmake, however, does not necessarily mean generated file 
> (See our CMake modules and toolchains for example). 
> So, it should not be added into the .gitignore file.
The `*.cmake` files that are relevenant are already versioned. When I build Urho3D, `git status` wants me to add all the newly generated `.cmake` files. IMHO, `git status` should indicate it has nothing new to do versioning on. 

I can do a new PR for the (trivial) Clamp function, but I'd first like git to behave properly on my build and changes.

**Comment by weitjong** [comment]
We recommend our users to generate the so-called out-of-source build tree. Since the build tree is outside of the project root, all the cmake-related stuffs and all the generated stuffs (like object files and binary files) are not actually located within the project root. Do ```./cmake_generic.sh /absolute/path/build-tree``` instead of ```./cmake_generic.sh .``` or ```./cmake_generic.sh relative/path/build-tree```. The latter two would generate non out-of-source build trees. Although this is a supported usage, it may clobber Urho3D project root (git repository) as you have observed. Changing the existing ```/lib*/``` entry in the ```.gitignore``` to ```lib*/``` should fix the ```*.a``` found in the ```relative/path/build-tree/lib``` though.

I am in the middle of something else. I may come back to change the ```.gitignore``` file if you have not done so.

**Comment by richelbilderbeek** [comment]
Would be awesome! Thanks for your consideration and time. I look forward to make some non-trivial contributions in the future.

**Pull request closed without merging**
