### PR TITLE
Urho3D Editor: Preview drag-moving rotation problem are fixed.

### PR DESCRIPTION
**Pull request by neat3d**
Hi, this is my first PR, if something wrong just correct me.

The preview drag-moving did not  work properly while you re-click the mouse button to rotate a object, it always reset the rotation to zero.

Fixed...

### CODE REVIEW

**Comment by weitjong** [comment]
Thanks for the PR. If you know how to perform an interactive rebase, I think you should squash the first commit so it does not get into our master commit history when the PR is being merged by the author of  Urho3D project.

**Comment by neat3d** [comment]
OK, I close this PR and repull later.

**Comment by weitjong** [comment]
Actually you can still rebase or even add more commits, i.e. make more changes, to an already opened PR without closing it first. You need force-push for the former and normal-push for the later. Sorry for the trouble.

**Comment by neat3d** [comment]
Hi weitjong,
I can't find a rebase button from github, so I redo all the things again...sorry about this, I am new to git, I think there are a lot to learn from you, however it is not the place to teach me how to git :p  
Thank you all the same for your advice!

**Pull request closed without merging**
