### PR TITLE
Fixed constraint

### PR DESCRIPTION
**Pull request by 1vanK**
I try to add Fixed constrant but I'm still not very good at it and I need help:

When I use raw bullet calls in my app all works
```
std::shared_ptr<btFixedConstraint> rawCons
...
    rawCons.reset(new btFixedConstraint(*body->GetBody(),
             *otherBody->GetBody(),
            btTransform(btQuaternion::getIdentity(), btVector3(-1, 0, 0)),
            btTransform(btQuaternion::getIdentity(), btVector3(1, 0, 0)) ) );
  
    btDiscreteDynamicsWorld* world = scene_->GetComponent<PhysicsWorld>()->GetWorld();
    world->addConstraint(rawCons.get(), false);
```

but when I test PR objects are move to one point
```
        Constraint* con = charNode->CreateComponent<Constraint>();
        con->SetConstraintType(ConstraintType::CONSTRAINT_FIXED);
        con->SetOtherBody(otherBody);
        con->SetDisableCollision(true);
        con->SetPosition(Vector3(-1.0f, 0.0f, 0.0f));
        con->SetOtherPosition(Vector3(1.0f, 0.0f, 0.0f));
```

Also I'm not sure about using axis (FORWARD or RIGHT?)

### CODE REVIEW

**Comment by 1vanK** [comment]
It is strange, but all works when I set type after all
```
        Constraint* con = charNode->CreateComponent<Constraint>();
        con->SetOtherBody(otherBody);
        //con->SetDisableCollision(true);
        con->SetPosition(Vector3(-1.0f, 0.0f, 0.0f));
        con->SetOtherPosition(Vector3(1.0f, 0.0f, 0.0f));

       con->SetConstraintType(ConstraintType::CONSTRAINT_FIXED); // !!!
```

**Comment by 1vanK** [comment]
I'm using a workaround and now it works, pls check

**Comment by eugeneko** [comment]
> It seems is bug in Bullet. Lib have FIXED_CONSTRAINT_TYPE but use D6_SPRING_2_CONSTRAINT_TYPE instead

This is feature
http://bulletphysics.org/Bullet/phpBB3/viewtopic.php?f=9&t=10698&view=previous

**Comment by Lumak** [comment]
missing get/set limit functions

**Comment by 1vanK** [comment]
I'm not sure there is no any limits, it is hard connection of two bodies

**Comment by Lumak** [comment]
Since the btFixedConstraint class is inherited from btGeneric6DofSpring2Constraint, excluding the spring dynamics settings, there are 6 DoF limits that you can apply.

But I'm with you. I don't know whether the implied "FixedConstraint" would mean that all six degrees are strictly limited to the default settings or some would want to have the freedom to limit some angle or linear limit.  

I'm guessing the former would be more popular. I'm good with this PR. Nice work.

**Comment by 1vanK** [comment]
```
btFixedConstraint::btFixedConstraint(btRigidBody& rbA,btRigidBody& rbB, const btTransform& frameInA,const btTransform& frameInB)
:btGeneric6DofSpring2Constraint(rbA,rbB,frameInA,frameInB)
{
	setAngularLowerLimit(btVector3(0,0,0));
	setAngularUpperLimit(btVector3(0,0,0));
	setLinearLowerLimit(btVector3(0,0,0));
	setLinearUpperLimit(btVector3(0,0,0));
}
```

**Comment by 1vanK** [comment]
> Since the btFixedConstraint class is inherited from btGeneric6DofSpring2Constraint, excluding the spring dynamics settings, there are 6 DoF limits that you can apply.

I could be wrong, but
```
btFixedConstraint::btFixedConstraint(btRigidBody& rbA,btRigidBody& rbB, const btTransform& frameInA,const btTransform& frameInB)
:btGeneric6DofSpring2Constraint(rbA,rbB,frameInA,frameInB)
{
	setAngularLowerLimit(btVector3(0,0,0));
	setAngularUpperLimit(btVector3(0,0,0));
	setLinearLowerLimit(btVector3(0,0,0));
	setLinearUpperLimit(btVector3(0,0,0));
}
```
is fixed and also user set offset and angles for bodies manually. Is it all DoF?

**Comment by Lumak** [comment]
Yes, three angular limits and three linear limits, and are all set to equal (value is not relevant).  When lowerLimit == upperLimit then there's no freedom.

**Comment by 1vanK** [comment]
Actually I did not test it anymore, so I do not know if there are any problems here

**Pull request closed without merging**
