### PR TITLE
AS Autobindings: guard implicitly declared destructor wrappers by def…

### PR DESCRIPTION
**Pull request by 1vanK**
…ines

### CODE REVIEW

**Comment by 1vanK** [comment]
quick fix to allow build with disabled parts of engine

**Comment by eugeneko** [comment]
Oh, I must have missed merge of AS bindings. Are they finished now?

**Comment by 1vanK** [comment]
No, merged as is, still a lot work. Read this https://github.com/urho3d/Urho3D/pull/2639

**Comment by weitjong** [comment]
Thanks for quick fix.

**Comment by 1vanK** [comment]
I will try to do the sorting classes by name tomorrow

**Comment by weitjong** [comment]
Thanks in advanced.

BTW, I have also merged my current dev branch into the main branch as is. Just in time to replace Travis-CI because it suddenly becomes so slow and choke since last night. The bad news is, we are not in the clear yet. The Web build still failing. I have no time to check yet, need to get back to my day work.

**Comment by 1vanK** [comment]
BackgroundLoader have no URHO3D_API but used externally somehow.

**Pull request merged**
