### PR TITLE
SoundSource: send E_SOUNDFINISHED to the source object too

### PR DESCRIPTION
**Pull request by moneromooo**
It might not have a node

### CODE REVIEW

**Comment by UkoeHB** [comment]
If there is no node, wouldn't it crash trying to dereference the pointer?

**Comment by eugeneko** [comment]
> wouldn't it crash trying to dereference the pointer?

It will. So this change doesn't actually change anything.

If you have node, you will get event both before and after.
If you don't have node, you will get a crash both before and after.

**Comment by moneromooo** [comment]
True. I don't quite remember now, I'll look into old commits. It was background music, so it might be the node's parent (ie, not in the scene). I'll comment when I worked it out.

**Comment by moneromooo** [comment]
This is not needed. I was registering to the sound source, but it works if I register to the node instead. It's confusing at start so that's why it did not work originally I think. I remember something about the sound source's node having no node itself, but since it works this patch is not needed.

**Pull request closed without merging**
