### PR TITLE
Update GLEW to 1.13.

### PR DESCRIPTION
**Pull request by cosmy1**
Its time to update GLEW as 1.9 is from 2012.

### CODE REVIEW

**Comment by cosmy1** [comment]
@cadaver What happened to the stale freetype-update branch? Now is old but I would like to know if you encountered any issues as I want to update FreeType to 2.6.3 when I find a bit of more free time.

**Comment by cadaver** [comment]
If I remember correctly a Freetype update was done in master after that branch. You just need to watch out for Freetype's compilation or configuration potentially changing, since we have our own CMakeLists for it, and check if the built-in example fonts still render OK. Particularly the UI default / editor font has been picky when Freetype's hinting implementation changes.

**Comment by cadaver** [comment]
Yeah, compiles OK, hinting is ugly.

**Comment by cosmy1** [comment]
Ok thanks.

**Comment by cadaver** [comment]
GLEW itself seems OK to merge. It still has the bug of requiring glewExperimental to be set, as it doesn't know how to read extensions properly on a GL3 core context.

**Pull request merged**
