### PR TITLE
Prevent canvas resize while the window size is still changing

### PR DESCRIPTION
**Pull request by ArnisLielturks**
Wait till the viewport resizing is actually finished, then wait 1s to actually apply the new viewport size.

### CODE REVIEW

**Comment by ArnisLielturks** [comment]
This greatly reduces this bug: https://github.com/urho3d/Urho3D/issues/2627

**Comment by eugeneko** [comment]
Same question. Can you please provide live samples to try it out?

**Comment by ArnisLielturks** [comment]
@eugeneko don't you trust me? Here's the link: https://demo.frameskippers.com/39_CrowdNavigation.html

All the samples are there, just replace the name of it

**Comment by eugeneko** [comment]
Tried it, feels fine.

**Comment by ArnisLielturks** [comment]
@kannsokusha can you also check the samples mentioned in my previous comment?

**Comment by ArnisLielturks** [comment]
@eugeneko let's merge this!

**Pull request merged**
