### PR TITLE
Added support for JSON scene and node loading, materials

### PR DESCRIPTION
**Pull request by hjmediastudios**
As the title says. I basically went through all the load/save XML functionality for scenes and nodes (but not for the UI-specific XML loading) and replicated it to add scene loading and saving to and from JSON data.

### CODE REVIEW

**Comment by cadaver** [comment]
Cool!

**Comment by hjmediastudios** [comment]
Note that this isn't a replacement for the XML capability, but just adds the ability to save/load scenes to and from JSON as well. I've also added support for material definitions in JSON and will likely expand this to allow all current XML-based resources to also support JSON. Why?

- Flexibility- more formats supported improves compatibility with other tools in the pipeline. The Blender-based scene editor I'm working on currently exports to JSON and allows me to edit my scenes in a mature tool I'm very familiar with, with much easier support for custom components.   
- Ease of use for manually creating material files, etc. JSON is far less "dense" and easier to manually type than XML. Clarity is also improved, in my view- a "parameters: [X:Y, A:B, C:D]" seems much more intuitive to edit and understand than "<parameter name=X, value=Y> <parameter name=A, value=B> <parameter name=C, value=D>."
- File size- uncompressed JSON data has a much greater data-to-markup ratio than XML.
- Speed- in my tests, loading JSON-based large files is faster than the same file expressed in XML.
- Relative ease- the parsed data can be stored in the same structures as XML, allowing no extra runtime overhead.

**Comment by JoshEngebretson** [comment]
This is really fantastic @hjmediastudios :+1:

**Comment by neat3d** [comment]
Cool feature! thx!
As I know, it is one of the unity3d version 5.30 features. 
So, Urho3D is ahead of unity3d, haha!
And maybe we can exchange some data with unity3d in the future?

**Comment by cadaver** [comment]
neat3d: Loading Unity files is unrealistic. Their prefabs/scenes are proprietary formats, which only refer to resources by project-specific uuids.

**Comment by cadaver** [comment]
Will test shortly, but two improvements / missing things come to mind: Since materials and scenes can now be JSON, please add the extensions to the editor file selectors. And, add some brief documentation to the Doxygen pages (Docs directory) to the relevant pages, to mention that JSON loading is also supported.

**Comment by rikorin** [comment]
This is great. The only thing I don't like about Urho is the usage of XML format. I'll add JSON support for UI files too while I work on the editor.

**Comment by hjmediastudios** [comment]
@rikorin: Oh, please do. I tried implementing JSON-loadable UI files and was horrified at the problems involved with maintaining XML support as well.

**Comment by cadaver** [comment]
Thanks for the update. Merged and did some scene load/save fixes. I thought I hallucinated it working earlier out of the box (on a different machine)

**Pull request merged**
