### PR TITLE
Fix for #2326

### PR DESCRIPTION
**Pull request by alex-rass-88**
Remove '-ffast-math' option.
Remove GCC 8.x check in Matrix3x4.h

-ffast-math dangerous option.

### CODE REVIEW

**Comment by alex-rass-88** [comment]
I can test on gcc 7.3 with the option enabled and disabled

**Comment by alex-rass-88** [comment]
tested gcc 7.3.0 on samples 12_PhysicsStressTest and 20_HugeObjectCount. There is no difference in performance.

**Comment by weitjong** [comment]
I suppose the difference depends on how frequent functions from the math library are being called in an actual game application.

**Comment by alex-rass-88** [comment]
'-ffast-math' does not always provide performance gains.

**Pull request merged**
