### PR TITLE
Bloom and BloomHDR PostProcess Fix

### PR DESCRIPTION
**Pull request by PsychoCircuitry**
Updated the render target names so the uniforms will work correctly in the shaders.

### CODE REVIEW

**Comment by ArnisLielturks** [comment]
@Modanung @eugeneko Any comments about the PR? Looks good for me. Also tested it and it works as expected.

**Comment by eugeneko** [comment]
Nope, looks fine for me.

**Comment by weitjong** [comment]
Please hold on for this one. See #2542

**Comment by ArnisLielturks** [comment]
@PsychoCircuitry are you planning to add fixes for other post processes too in this PR?

**Comment by ArnisLielturks** [comment]
@weitjong I would suggest merging this PR and add additional fixes in a separate PR.

**Comment by weitjong** [comment]
I actually afraid we/I have introduced a bug somewhere that causes all these. So, I would rather fix the root cause, if it is indeed the case. Having said that, I really don't have the time debug it myself.

**Comment by ArnisLielturks** [comment]
@weitjong no problem. I have been looking at the graphics pipeline lately and noticed couple more  bugs regarding the shaders so I will pick this up.

**Comment by ArnisLielturks** [comment]
@weitjong @Modanung This issue is caused by https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/Graphics/View.cpp#L1866-L1869
since now we have case sensitive stringhashes. 
We could find how many shaders are impacted by searching `c[rtname]InvSize` and `c[rtname]Offsets` usage in shaders

**Comment by ArnisLielturks** [comment]
So in the case of Bloom shaders the blur would actually blur out region of 0 radius, since the uniforms would not be initialized with the actual values.

**Comment by Modanung** [comment]
Wouldn't it also be better to use `static_cast<float>(...)` instead of C-style `(float)`?

**Comment by ArnisLielturks** [comment]
Blur and auto exposure fixes provided in a seperate commit.

**Pull request merged**
