### PR TITLE
Scale kerning values correctly (closes #2007)

### LINKED ISSUE #2007: Kerning values are not scaled correctly
When reading TrueType kerning tables, we don't currently scale the kerning values to match the size of the font. This means the kerning is too tight at small font sizes, as seen in this screenshot (the smallest size actually ends up with negative width):

kerning_bug

### PR DESCRIPTION
**Pull request by iainmerrick**

### CODE REVIEW

**Comment by 1vanK** [comment]
after some patches example 35_SignedDistanceFieldText does not works correctly

**Comment by iainmerrick** [comment]
Ack! I'll take a look.

**Comment by iainmerrick** [comment]
The C++ version of 35_SignedDistanceFieldText works, but the AngelScript version doesn't. Looks like the text geometry is wrong -- it's squished into thin strips. Most likely some bug in the API bindings.

**Comment by iainmerrick** [comment]
Filed issue #2035

**Comment by 1vanK** [comment]
Thanks!

**Pull request merged**
