### PR TITLE
Add info about shapes to PhysicsEvents2D

### PR DESCRIPTION
**Pull request by 1vanK**
Sometimes it is necessary to identify collided shapes: http://www.iforce2d.net/b2dtut/jumpability

Can we also add to components name_, tags or vars? (currently I compare pointers to identify shape)

EDIT: May be move "name", "vars" and "tags" to Animatable (or Serializable) class?

### CODE REVIEW

**Comment by 1vanK** [comment]
What for is needed NodeImpl?

**Comment by eugeneko** [comment]
> What for is needed NodeImpl?

To make Node class more light-weight for some performance stuff.

**Comment by 1vanK** [comment]
> To make Node class more light-weight for some performance stuff.

For example?

**Comment by eugeneko** [comment]
> For example?

Check related commits, there were some performance degradation.

BTW, why have you removed Name attribute from ::RegisterObject? Have you checked e.g. Editor?

**Comment by 1vanK** [comment]
Thanks, I think it copys base attributes, but it not

**Comment by 1vanK** [comment]
> UPD: fee755e

I still do not understand the circumstances under which performance is improved

**Comment by 1vanK** [comment]
Hm, I should add
```
URHO3D_ACCESSOR_ATTRIBUTE("Name", GetName, SetName, String, String::EMPTY, AM_DEFAULT);
```
to every derived Component
or create Component::RegisterObject() and URHO3D_COPY_BASE_ATTRIBUTES() to every derived Component

**Comment by 1vanK** [comment]
Should I add
```
URHO3D_ACCESSOR_ATTRIBUTE("Name", GetName, SetName, String, String::EMPTY, AM_DEFAULT);
```
to every derived components

or create Component::RegisterObject(Context* context) and add URHO3D_COPY_BASE_ATTRIBUTES to every derived components

**Comment by eugeneko** [comment]
> I still do not understand the circumstances under which performance is improved

I can't find an issue, but you can check some heavy benchmarks like Demo 20

**Comment by cadaver** [comment]
The point with NodeImpl is to reduce the binary size of the Node class to make it fit into cache better for "hot" access like a Drawable asking its world transform. 

I can cherrypick the first commit from this PR but don't think will be taking the Node / Animatable change. That's btw. also why I find master branch PR's a bit scary, because master usually represents author's continuing development. Separate feature branch for PR would tell more clearly that it's this specific change (mentioned in the PR) you want to be pulled in now, and it won't be changing in the meanwhile.

**Comment by 1vanK** [comment]
Any another way to identify components?

**Comment by 1vanK** [comment]
Box2D uses UserData for identification, but curently UserData is pointer to Component

**Comment by cadaver** [comment]
Currently there's not much else than the index order within the parent node's component list. When you know e.g. specific shape components are for specific parts of the object, you could hold them in pointers / handles in logic code.

**Comment by 1vanK** [comment]
> you could hold them in pointers / handles in logic code.

Yes, I am doing so, but it is not very convenient (sensors placed all around main collision shape and is needed compare with every)

**Comment by 1vanK** [comment]
It is possible to accept only first commit or I should modify PR?

**Comment by cadaver** [comment]
I will cherrypick and merge, you don't have to do anything. The hash changes so it will not show the exact same commit you made, but I don't think that's an issue.

**Comment by cadaver** [comment]
First commit merged.

**Pull request closed without merging**
