### PR TITLE
Remove misplace explicits from smart pointers.

### PR DESCRIPTION
**Pull request by eugeneko**
@weitjong Want to revert some autorefactored things...

### CODE REVIEW

**Comment by weitjong** [comment]
I only put "NOLINT" for types that I consider can be used interchangeably, with the exception case like construct from null pointer and helper operator. So, I am agree that some of the auto-fixed `explicit` specifier should be reverted back (those were probably done during the rush `git rebase` before the year ended. However, I am not sure about the potentially upcasting copy-ctor to be excluded from the linter as well. Do you think it is a good idea to treat those types as interchangeable?

**Comment by eugeneko** [comment]
Implicit upcasting from derived to base is natural for raw pointers. STL pointers do the same.
So I think that Urho's smart pointers could expose the same functionality.

**Comment by weitjong** [comment]
Just to be sure we are talking about the same thing. The specifier doesn't prevent any of this. It just forces developer to be explicit about it when it is intended.

If you are sure it is better this way then I have no objection.

**Comment by eugeneko** [comment]
I see. Yep, I think that implicit conversions are better here.
More handy to e.g. return pointers from functions or push 'em to containers and so on.. And no pitfalls except minor performance cost of copying.

**Pull request merged**
