### PR TITLE
Fixed GLTF import

### PR DESCRIPTION
**Pull request by niansa**
I noticed glTF2Importer::CanRead not returning the right value on success :wink:

### CODE REVIEW

**Comment by weitjong** [comment]
Thanks!

**Comment by 1vanK** [comment]
need comment for changes in 3rd-libs

**Comment by weitjong** [comment]
Ideally, yes. However, this bug fix is so glaring that I would not be surprised if it has been fixed in upstream long time ago.

**Comment by 1vanK** [comment]
https://github.com/assimp/assimp/blob/master/code/AssetLib/glTF2/glTF2Importer.cpp#L114-L126

**Comment by 1vanK** [comment]
Actually I don't understand why the function returns true if no check was successful

**Comment by weitjong** [comment]
The upstream is preparing for the Release 5.1.0. If no one has done so, I/we should submit the PR for this bug fix to upstream.

**Comment by weitjong** [comment]
I think we just have to keep this fix locally as the version of code has changed in the upstream's master branch. See the thread in the upstream for the funny story. Morale of the story: don't just trust the tool with CLI, eye ball the code manually :smiley:. For some reason my eye also just locked in to the last return statement when 1vank showed the code 2 days ago here. 

p.s. It seems the 5.1.0 is in fact already out. Anyone, who is interested in upgrading the Assimp, can just safely override this local (unmarked) patch of ours with the newer release.

**Pull request merged**
