### PR TITLE
support resource drag to scene

### PR DESCRIPTION
**Pull request by 299299**

### CODE REVIEW

**Comment by cadaver** [comment]
Will have to check if there's already code for offsetting a model in the spawn editor, in that case GetNodeSize() would be redundant and can be replaced with the existing code.

**Comment by 299299** [comment]
found this variable : alignToAABBBottom

**Comment by cadaver** [comment]
Thanks for the modification, will check now.

**Comment by cadaver** [comment]
Merged. Did some further cleanup and support for raycasting the world position based on cursor pos.

**Pull request closed without merging**
