### PR TITLE
Update Recast & Detour lib

### PR DESCRIPTION
**Pull request by 1vanK**

### CODE REVIEW

**Comment by 1vanK** [comment]
How to change case of letters for folders in the repository? Recast/detour now use folders "Source" and "Include" instead "source" and "include" https://github.com/recastnavigation/recastnavigation/tree/master/Detour

**Comment by 1vanK** [comment]
ok, hack
```
git mv Source/ThirdParty/Detour/include Source/ThirdParty/Detour/include_
git mv Source/ThirdParty/Detour/include_ Source/ThirdParty/Detour/Include
```
for every folder helped me

**Comment by weitjong** [comment]
Thanks for your PR.

**Comment by weitjong** [comment]
Sorry for the delay. I just merged your commit into a new test branch for full CI tests.

**Comment by 1vanK** [comment]
No problems

**Comment by weitjong** [comment]
It is merged now. Thanks again.

**Pull request closed without merging**
